InternLM/lmdeploy

lmdeploy/pytorch/chat.py
这个错误是由于 warnings.warn 函数被错误地调用。这个函数的第二个参数（category参数）应该是一个 Warning 的子类，但在代码中，这个参数被设定为了一个字符串，这导致了 TypeError。
=> fix warnings.warn of `lmdeploy/pytorch/chat.py` 

benchmark/profile_serving.py
While profiling with concurrency, not all thread will be assigned the same number of requests (if sample % concurrency != 0), so the length of stats variables may also be different.
=> Fix possible errors in benchmark script

README.md, README_zh-CN.md
Telling user disable ECC could free up 10% GPU memory.
=> docs(README): disable ECC

lmdeploy/lite/apis/get_small_sharded_hf.py
Split HuggingFace model to the smallest sharded checkpoints, to support low RAM machine load large model.
Add `lmdeploy/lite/apis/get_small_sharded_hf.py`
1. …
=> [Feature] Add script to split HuggingFace model to the smallest sharded checkpoints

docs/en/quantization.md, docs/zh_cn/quantization.md, lmdeploy/lite/apis/kv_qparams.py, src/turbomind/kernels/decoder_masked_multihead_attention.h, src/turbomind/kernels/decoder_masked_multihead_attention/decoder_masked_multihead_attention_template.cuh, src/turbomind/models/llama/LlamaDecoderLayerWeight.cc, src/turbomind/models/llama/LlamaDecoderSelfAttentionLayer.cc, src/turbomind/models/llama/llama_kernels.cu
kv_cache 改非对称量化，跑 llama 7B 没问题。
公式
```bash
数值范围 [-127,+127]
zp = (min+max) / 2
scale = (max-min) / 255
quant: q = round( (f-zp) / scale)
dequant: f = q * scale + zp
```
https://github.com/InternLM/lmdeploy/pull/60/files
7B 精度测试结果
|     task      |     dataset     |    metric     | int8  | fp16  | diff  |
| :-----------: | :-------------: | :-----------: | :---: | :---: | :---: |
|   Language    |   winogrande    |   accuracy    | 60.77 | 61.48 | -0.71 |
|   Knowledge   |       nq        |     score     | 2.69  | 2.60  | +0.09 |
|   Reasoning   |      gsm8k      |   accuracy    | 33.28 | 34.72 | -1.44 |
|   Reasoning   |       bbh       | naive_average | 20.12 | 20.51 | -0.39 |
| Understanding | openbookqa_fact |   accuracy    | 82.40 | 82.20 | +0.20 |
| Understanding |   eprstmt-dev   | …
=> feat(quantization): kv cache use asymmetric

lmdeploy/serve/turbomind/deploy.py, src/turbomind/models/llama/LlamaBatch.cc, src/turbomind/models/llama/LlamaV2.cc, src/turbomind/models/llama/LlamaV2.h, src/turbomind/models/llama/LlamaWeight.cc, src/turbomind/models/llama/LlamaWeight.h
To resolve #266 
Pad 'tok_embedding.weight' and 'output.weight' if their shape is not divisible by TP
The following models are tested:
1. Pre-commit or other …
=> Pad tok_embedding and output weights to make their shape divisible by TP

.readthedocs.yml
Fix https://readthedocs.org/projects/lmdeploy/builds/21738675/
`The configuration key "build.os" is required to build your documentation.` Read more at https://docs.readthedocs.io/en/stable/config-file/v2.html#build-os
2. The modification is covered by complete unit tests. If not, please …
=> Fix readthedocs building

README.md
incorrect links for quantization docs on README.md
`README.md`
2. The …
=> [Doc] Fix quantization docs link

docs/en/build.md, docs/zh_cn/build.md
Use conda to install openmpi, nccl and rapidjson
Conda will automatically install the required version of GCC.
=> [Docs] Simplify `build.md`

lmdeploy/serve/openai/api_server.py
bug fix : when using stream=False, the continuous batching is not working.
See details in this issue: https://github.com/InternLM/lmdeploy/issues/308
In non-streaming mode, the main thread which is responsible for receiving request is stuck in the following code since self.que.get() will wait until the queue is not empty.
But when using non-stream mode, the queue is always empty unless a request is finished.
So the newly coming request won't be processed before the last request is done. So the batching doesn't work.
```python
while True:
while self.que.qsize() > 1:
self.que.get()
finish, tm_outputs = self.que.get()
outputs = _tm_dict_to_torch_dict(tm_outputs)
```
I modify here to avoid the long wait. just see the commits.
I'm not sure if there is a better way to fix this. If any, please …
=> bug-fix: when using stream is False, continuous batching doesn't work

.github/workflows/docker.yml
Fix disk space limit for building docker image
tested workflow https://github.com/RunningLeon/lmdeploy/actions/runs/6154601980/job/16700202668
Remove unused files in `/opt/hostedtoolcache` to save disk space.
```
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        84G   63G   21G  76% /
tmpfs           3.4G  [17](https://github.com/RunningLeon/lmdeploy/actions/runs/6154601980/job/16700202668#step:3:18)2K  3.4G   1% /dev/shm
tmpfs           1.4G  1.1M  1.4G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/sda15      105M  6.1M   99M   6% /boot/efi
/dev/sdb1        14G  4.1G  9.0G  31% /mnt
tmpfs           694M   12K  694M   1% /run/user/1001
```
```
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        84G   53G   31G  64% /
tmpfs           3.4G …
```
=> Fix disk space limit for building docker image

lmdeploy/pytorch_poc/engine/engine.py, lmdeploy/pytorch_poc/patch/llama.py
As `q_seq_info` is always required in paged attention and it is ready when making inputs, I moved it into context, in order to simply supporting new models in future. 
The result is the same as computing these values based on position ids. 
+ some other improvements
=> Move `q_seq_info` into `context`

lmdeploy/serve/openai/api_server.py
=> Fix token count bug

lmdeploy/pytorch_poc/paging/scheduler.py
It seems that logic blocks are assigned with 1 more block, which make history length calculation wrong. As shown in below debug. 
After fixing this, falcon output the same as the original hf version.
=> reduce logic block

src/turbomind/models/llama/LlamaV2.cc, src/turbomind/models/llama/LlamaV2.h, src/turbomind/models/llama/Request.h, src/turbomind/utils/allocator.h
This is a fix for LlamaV2's infinite destructor call.
A bug in the cuda allocator (in destructor) has also been fixed.
=> [feature] Graceful termination of background threads in LlamaV2

src/turbomind/models/llama/LlamaBatch.cc
I encountered segfault when I started generating a lot of requests with tensor para > 1.
It happens because threads exit from method `LlamaV2::forward` and release input/output tensors. But at the same time threads from `LlamaV2::internalThreadEntry` with rank > 0 can access these tensors.
=> [bug] Fix race condition

lmdeploy/serve/openai/api_server.py, lmdeploy/serve/openai/protocol.py
Running command 
```bash
python3 -m lmdeploy.serve.openai.api_server ./workspace 0.0.0.0 8080  --instance_num 32 --tp 1
```
and start to call the `/chat/completions` api will show error messages like this:
```
/output/.pylibs/lib/python3.8/site-packages/lmdeploy/serve/openai/api_server.py:170: PydanticDeprecatedSince20: The `json` method is deprecated; use `model_dump_json` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.3/migration/
data = …
```
=> Fix compatibility issues with Pydantic 2

benchmark/README.md, benchmark/profile_restful_api.py, benchmark/profile_serving.py
=> fix benchmark serving cannot use Qwen tokenizer

lmdeploy/serve/openai/api_server.py
Support CORS for openai api.
Add CORS headers.
=> Support CORS for openai api server

src/turbomind/triton_backend/llama/LlamaTritonModel.cc, src/turbomind/triton_backend/llama/LlamaTritonModel.h
=> Change `shared_instance` type from `weakptr` to `shared_ptr`

lmdeploy/turbomind/turbomind.py
I found the first generated token was swallowed when integrating turbomind python API to opencompass.
That's because it uses the default value of `step` as 1 in `stream_infer` API.
Changing to 0 can resolve it.
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this …
=> [Fix] Set the default value of `step` being 0

benchmark/profile_restful_api.py, docs/en/restful_api.md, docs/zh_cn/restful_api.md, lmdeploy/serve/async_engine.py, lmdeploy/serve/gradio/app.py, lmdeploy/serve/openai/api_client.py, lmdeploy/serve/openai/api_server.py, lmdeploy/serve/openai/protocol.py
#463
#408 ctrl+C
fix api_client.py reuse the old session
=> make IPv6 compatible, safe run for coroutine interrupting

src/turbomind/models/llama/LlamaV2.cc
This data is [allocated](https://github.com/InternLM/lmdeploy/blob/main/src/turbomind/models/llama/LlamaBatch.cc#L169) and  used ([1](https://github.com/InternLM/lmdeploy/blob/main/src/turbomind/models/llama/LlamaContextDecoder.cc#L189), [2](https://github.com/InternLM/lmdeploy/blob/main/src/turbomind/models/llama/LlamaContextDecoder.cc#L264), [3](https://github.com/InternLM/lmdeploy/blob/main/src/turbomind/models/llama/LlamaContextDecoder.cc#L266)) with the other shape
=> [bug] fix mismatched shape for decoder output tensor

docs/en/w4a16.md, docs/zh_cn/w4a16.md
=> [doc] Update benchmark command in w4a16.md

README.md, README_zh-CN.md, lmdeploy/model.py
=> add solar chat template

.github/workflows/lint.yml, lmdeploy/pytorch_poc/config.py, lmdeploy/pytorch_poc/engine/cache_engine.py, lmdeploy/pytorch_poc/engine/engine.py, lmdeploy/pytorch_poc/models/falcon.py, lmdeploy/pytorch_poc/models/patch.py
Tested with falcon-rw-1b, falcon-7b-instruct and (new) 40b-instruct
Modifies outside falcon to make things work:
1. add multi_query_attention in ModelConfig and let CacheEngine not to split the single k/v head. 
2. some error message on asserts, in the cache engine
=> Support Tensor parallel on Falcon models

requirements.txt
gradio >= 4.0.0 doesn't support `gr.Button.update`
make gradio version < 4.0.0
=> fix: gradio gr.Button.update deprecated after 4.0.0

src/turbomind/kernels/gpt_kernels.h, src/turbomind/kernels/sampling_penalty_kernels.cu, src/turbomind/layers/sampling_layers/TopKSamplingLayer.cu, src/turbomind/layers/sampling_layers/TopPSamplingLayer.cu, src/turbomind/models/llama/Barrier.h, src/turbomind/models/llama/LlamaBatch.cc, src/turbomind/models/llama/LlamaContextDecoder.cc, src/turbomind/models/llama/LlamaDecoder.cc, src/turbomind/models/llama/LlamaDecoderSelfAttentionLayer.cc, src/turbomind/models/llama/LlamaV2.cc, src/turbomind/models/llama/llama_utils.cu, src/turbomind/models/llama/llama_utils.h, src/turbomind/utils/memory_utils.cu
Resolve w4a16 crash in pressure test
=> Fix race condition & check for anormal values (#627)

.github/ISSUE_TEMPLATE/1-bug-report.yml, lmdeploy/cli/cli.py
Add check env sub command
- update cli to support `lmdeploy check_env`
- update issue template
None
- `lmdeploy check_env`
- `lmdeploy check_env --dump_file env.json`
```
sys.platform: linux
Python: 3.8.18 (default, Sep 11 2023, 13:40:15) [GCC 11.2.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA A100-SXM4-80GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.4, V11.4.152
GCC: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
PyTorch: 2.0.0+cu117
PyTorch compiling details: PyTorch built with:
- GCC 9.3
- C++ Version: 201703
- Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
- Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
- OpenMP 201511 (a.k.a. OpenMP 4.5)
- …
```
=> Add check env sub command

lmdeploy/tokenizer.py
fix Tokenizer load error when converting a model and the src model path is not writable.
=> fix Tokenizer load error when folder is not writable

docs/en/w8a8.md, docs/zh_cn/w8a8.md, lmdeploy/lite/apis/smooth_quant.py, lmdeploy/lite/quantization/awq.py, lmdeploy/lite/quantization/calibration.py, lmdeploy/pytorch_poc/chat.py, lmdeploy/pytorch_poc/engine/engine.py, lmdeploy/pytorch_poc/kernels/w8a8_triton_kernels.py, lmdeploy/pytorch_poc/modeling/convert_to_qmodules.py, lmdeploy/pytorch_poc/modeling/modeling_baichuan.py, lmdeploy/pytorch_poc/modeling/modeling_internlm.py, lmdeploy/pytorch_poc/modeling/modeling_llama.py, lmdeploy/pytorch_poc/models/__init__.py, lmdeploy/pytorch_poc/models/patch.py, lmdeploy/pytorch_poc/models/q_modules.py
In this step, we will run the smooth_quant.py script to generate a W8A8 quantized model that is processed by SmoothQuant. Execute the following command:
```
python lmdeploy/lite/apis/smooth_quant.py internlm/internlm-7b ./work_dir
```
This command generates a quantized model and saves it in the `./work_dir` directory.
Once you have the quantized model, you can interact with it using the chat.py script. Run the following command:
```
python lmdeploy/pytorch_poc/chat.py ./work_dir internlm-chat 
```
Upon executing this command, an interactive session starts where you can converse with your quantized model.
1. **Smooth Weights**: Start by smoothing the weights of the Language Model (LLM). This process makes the weights more amenable to quantizing.
2. **Replace Modules**: Locate DecoderLayers …
=> [Feature] w8a8 based on pytorch poc

lmdeploy/lite/apis/auto_awq.py, lmdeploy/lite/apis/calibrate.py, lmdeploy/lite/utils/__init__.py, lmdeploy/lite/utils/load.py
Supports the use of model id for calibration and auto_awq.
=> [Fix] Fix load_checkpoint_in_model bug

lmdeploy/serve/turbomind/chatbot.py, lmdeploy/serve/turbomind/triton_models/preprocessing/1/model.py, lmdeploy/serve/turbomind/triton_models/preprocessing/config.pbtxt, lmdeploy/serve/turbomind/utils.py
The tricks lmdeploy used to get bos_token_id and eos_token_id through gRPC API is wrong.
It is found that qwen's tokenizer model has no bos_token_id.   
Beside, its eos_token_id is 151643, which is not the encoding result of `</s>`
preprocessing/1/model.py
If this PR …
=> Fix wrong eos_id and bos_id obtained through grpc api

src/turbomind/models/llama/flash_attention2/flash_fwd_launch_template.h
=> fix turbomind build on sm<80

benchmark/README.md, benchmark/profile_generation.py, benchmark/profile_restful_api.py, benchmark/profile_serving.py, benchmark/profile_throughput.py, docs/en/restful_api.md, docs/zh_cn/restful_api.md, lmdeploy/cli/serve.py, lmdeploy/serve/async_engine.py, lmdeploy/serve/openai/api_server.py, lmdeploy/serve/turbomind/chatbot.py, lmdeploy/turbomind/turbomind.py
1. open stream_output in profile_generation.py
2. calculate the statistics of first_token_latency and token_latency percentile
3. set random seed when profiling serving, restful api and throughput
If this PR introduces a new feature, it is better to list some use cases …
=> Report first-token-latency and token-latency percentiles

lmdeploy/cli/cli.py, lmdeploy/turbomind/deploy/converter.py
=> convert model with hf repo_id

lmdeploy/model.py
Wrong implementation in `InternLMChat7B.messages2prompt`, because `self.assistant` already has colon at end.
As PR
No
No …
=> fix extra colon in InternLMChat7B template

.github/md-link-config.json, .github/workflows/docker.yml, docker/Dockerfile
For easy building docker image.
update dockerfile and ci
1. Automatically: a push to main branch or a released tag
2. Manually: can select a branch, tag, or SHA to build.
https://github.com/RunningLeon/lmdeploy/actions/runs/7176686142/job/19541954316
4. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness.
5. If the modification has a dependency on downstream projects of a newer version, this PR …
=> Support building docker image manually in CI

docs/zh_cn/kv_int8.md, docs/zh_cn/turbomind.md, lmdeploy/lite/apis/auto_awq.py
huggingface's transformer model saves `.safetensors` as default, which is not suitable for `lmdeploy convert` with `awq` format.
save model with `.bin`, see the modified file in this pr.
Also several document modification.
=> fix: awq should save bin files

docs/zh_cn/restful_api.md
fix ".generate" to ".chat_interactive_v1"
=> [Docs] Fix typo in `restful_api ` user guide

lmdeploy/turbomind/deploy/target_model/base.py
`torch.cuda.is_bf16_supported()` would initialize cuda, which leads to reinitialize in multiprocess environment.
=> Fix cuda reinitialization in a multiprocessing setting

lmdeploy/lite/apis/smooth_quant.py, lmdeploy/lite/utils/load.py, lmdeploy/pytorch/chat.py
In this step, we will run the smooth_quant.py script to generate a W8A8 quantized model that is processed by SmoothQuant. Execute the following command:
```
python3 -m lmdeploy.lite.apis.smooth_quant internlm/internlm-chat-7b ./work_dir/internlm-chat-7b-quant
```
This command generates a quantized model and saves it in the `./work_dir` directory.
Once you have the quantized model, you can interact with it using the chat.py script. Run the following command:
```
python3 -m lmdeploy.pytorch.chat work_dir/internlm-chat-7b-quant internlm-chat
```
Upon executing this command, an interactive session starts where you can converse with your quantized model.
1. **Smooth Weights**: Start by smoothing the weights of the Language Model (LLM). This process makes the weights more amenable to …
=> [Fix] Adapt to the pyTorch poc branch

lmdeploy/serve/gradio/api_server_backend.py, lmdeploy/serve/gradio/triton_server_backend.py, lmdeploy/serve/gradio/turbomind_coupled.py, lmdeploy/serve/openai/api_client.py
the current api server web demo is simple, I want to change some params on the web.
Just add three new params `top_p`、`temperature`、`Maximum new tokens`(`request_output_len` in the code)
1. Pre-commit or other linting tools are used to fix the potential lint issues. —— **Already run.**
2. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness. —— **I test the code change by changing the params value and then observe the model output, I think the output is right.**
=> [Feature] Add params config for api server web_ui

lmdeploy/turbomind/deploy/target_model/base.py
```
num_tokens_per_iter: int = 1
max_prefill_iters: int = 1
extra_tokens_per_iter: int = 0
```
are used to adjust the performance of prefill
base.py
No
=> export "num_tokens_per_iter", "max_prefill_iters" and etc when converting a model

requirements/runtime.txt, requirements/serve.txt
To simplify the installation section in README, which will be modified later
=> Move `api_server` dependencies from serve.txt to runtime.txt

lmdeploy/turbomind/turbomind.py
`await asyncio.sleep(0)` makes the coroutine switch too fast, making the server benchmark unstable.
=> stable api_server benchmark result by a non-zero await

lmdeploy/lite/apis/smooth_quant.py, lmdeploy/pytorch/dist_utils.py, lmdeploy/pytorch/engine/model_agent.py, lmdeploy/pytorch/models/patch.py, lmdeploy/pytorch/models/q_modules.py
主要修改为在切分权重的时候需要考虑到 buffer ，因为在 QLinear 中，Weight, Bias, Scale 都是以 buffer 形式存储的。
如果把 Weight, Bias, Scale 都注册为 Parameter ，可能需要统一修改 register parameter 的逻辑。因为 Weight 需要是 int8 类型的，将其注册为 Parameter 的时候需要将requires_grad 设为False，而 accelerator 的 [init_on_device](https://github.com/huggingface/accelerate/blob/main/src/accelerate/big_modeling.py#L123) 中重写了注册 Parameter 的机制，导致 ``` self.weight = nn.Parameter(a_int8_tensor, requires_grad=False)```这种写法是不起效果的。可能需要将所有涉及注册 Parameter 的地方都改成下面这种写法：
```
param = torch.Tensor._make_subclass(nn.Parameter, param, False)
if param.dtype == torch.int8:
param.__dict__.update({'requires_grad': False})
module.register_parameter(name, param)
```
=> [Feature] Support w8a8 tp

.github/scripts/test_triton_server.py, .github/workflows/test.yml
Output triton server log messages for better debugging.
Example of running log: https://github.com/RunningLeon/lmdeploy/actions/runs/7335746170/job/19974082238
3. If the …
=> Update test triton CI

lmdeploy/turbomind/__init__.py, lmdeploy/turbomind/chat.py, lmdeploy/turbomind/deploy/target_model/base.py, lmdeploy/turbomind/engine_config.py, lmdeploy/turbomind/turbomind.py, src/turbomind/triton_backend/llama/LlamaTritonModel.cc
=> Check-in turbomind engine config

docs/en/quantization/w4a16.md, docs/zh_cn/quantization/w4a16.md, lmdeploy/cli/lite.py, lmdeploy/lite/apis/auto_awq.py, lmdeploy/lite/apis/calibrate.py
Before this PR, AWQ quantization needs to execute two commands
```bash
lmdeploy lite calibrate  $HF_MODEL
lmdeploy lite auto_awq $HF_MODEL
```
In this PR, AWQ quantization only needs to execute one command
```bash
lmdeploy lite auto_awq $HF_MODEL
```
=> [Feature]Merge `lmdeploy lite calibrate` and `lmdeploy lite auto_awq`

lmdeploy/serve/async_engine.py
Fix the runtime error of `stop_words must be a list of str but got`
=> fix pipeline stop_words type error

lmdeploy/pytorch/chat.py, lmdeploy/serve/async_engine.py, lmdeploy/turbomind/chat.py, lmdeploy/turbomind/turbomind.py
=> suppress turbomind chat warning

benchmark/profile_generation.py
Import turbomind outside multiprocessing would trigger an error.
=> fix profile generation multiprocessing error

lmdeploy/cli/cli.py, lmdeploy/cli/entrypoint.py
run `lmdeploy`  without other args
```
File "/data/conda-envs/envs/pt2.0py38/bin/lmdeploy", line 33, in <module>
sys.exit(load_entry_point('lmdeploy', 'console_scripts', 'lmdeploy')())
File "/data/mm2.0/lmdeploy/lmdeploy/cli/entrypoint.py", line 20, in run
args.print_help()
AttributeError: 'Namespace' object has no attribute 'print_help'
```
```
usage: lmdeploy [-h] [-v] {chat,lite,serve,convert,list,check_env} ...
The CLI provides a unified API for converting, compressing and deploying large language models.
optional arguments:
-h, --help            show this help message and exit
-v, --version         show program's version number and exit
Commands:
lmdeploy has following commands:
{chat,lite,serve,convert,list,check_env}
chat                Chat with …
```
=> print help for cli in case of failure

lmdeploy/pytorch/models/baichuan.py, lmdeploy/pytorch/models/module_map.py
```python
python -m lmdeploy.pytorch.chat \
/path/to/baichuan2/Baichuan2-7B-Chat/ \
baichuan2-7b
```
```python
python -m lmdeploy.pytorch.chat \
/path/to/baichuan2/Baichuan2-7B-Chat/ \
baichuan2-7b
```
leads to different result.
=> fix module mapping error of baichuan model

docs/en/benchmark/evaluate_with_opencompass.md, docs/en/conf.py, docs/en/index.rst, docs/zh_cn/benchmark/evaluate_with_opencompass.md, docs/zh_cn/conf.py, docs/zh_cn/index.rst, requirements/docs.txt
add docs for evaluation with opencompass
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported …
=> add docs for evaluation with opencompass

lmdeploy/pytorch/engine/engine.py
- Sleep would block coroutine
- 10.6 req/s
=> optimize sleep

lmdeploy/cli/chat.py, lmdeploy/cli/cli.py, lmdeploy/cli/lite.py, lmdeploy/cli/serve.py, lmdeploy/cli/utils.py
Update adapters cli argument to accept one adapter path without given adapter name.
Related issue: https://github.com/InternLM/lmdeploy/issues/1030
3. If the modification has a dependency on downstream projects of a newer version, this …
=> Update adapters cli argument

docs/en/build.md, docs/en/quantization/kv_int8.md, docs/en/quantization/w4a16.md, docs/en/serving/restful_api.md, docs/zh_cn/build.md, docs/zh_cn/quantization/kv_int8.md, docs/zh_cn/quantization/w4a16.md, docs/zh_cn/serving/restful_api.md
update docs for kvint8
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream …
=> update docs for kvint8

src/turbomind/kernels/sampling_penalty_kernels.cu, src/turbomind/kernels/sampling_penalty_kernels.h, src/turbomind/layers/sampling_layers/BaseSamplingLayer.cc, src/turbomind/layers/sampling_layers/BaseSamplingLayer.h, tests/csrc/unittests/test_penalty_kernels.cu
address https://github.com/InternLM/lmdeploy/issues/1009 https://github.com/InternLM/lmdeploy/issues/898
去掉Shared Memory 支持更长的 session
=> repetition penalty for long context

lmdeploy/turbomind/turbomind.py
fix memory equality check
use engine_config.tp when tp is None
=> fix use engine_config.tp when tp is None

lmdeploy/api.py, lmdeploy/serve/openai/api_server.py
use `TM_LOG_LEVEL` environment variable first
When I want to print the `Turbomind`'s debug log, I set `TM_DEBUG_LEVEL=DEBUG` and `TM_LOG_LEVEL=DEBUG`. It doesn't work and I find that I must use the `--log-level DEBUG` command line argument. It's very unintuitive. 
Set log level for `Turbomind` only when environment variable `TM_LOG_LEVEL` has not been set. After this modification, when environment variable `TM_LOG_LEVEL` has been set, use it first rather than the command line config or the default config.
3. If the modification has a dependency on downstream projects of a newer version, this PR …
=> fix use TM_LOG_LEVEL environment variable first

lmdeploy/pytorch/modeling/convert_to_qmodules.py, lmdeploy/pytorch/models/q_modules.py
When using w8a8 model, it will cost a bunch of time for model loading. I found that when using 
```python
QRMSNorm.from_float()
QLinear.from_float()
```
this func cal the per_channel_quant to get the scale and quanted weight, but it is useless. Because the para not load to model yet, it is just cal for all the zero... so I fix it when init the model on inference stage.
|      | time cost(s)           |
|--------------|------------------|
| cal the scale and weight         | 17 |
| dont cal         | 0.08 |
And I tested it on internLM and internLM2
=> Speed up torch engine w8a8 model init

lmdeploy/tokenizer.py, tests/test_lmdeploy/test_tokenizer.py
When concurrency is high, Turbomind may decode nothing in stream mode. Which is a risk for api_server. A side effect of #992
=> [Fix] Add safety check for incremental decode

lmdeploy/pytorch/modeling/modeling_baichuan.py, lmdeploy/pytorch/modeling/modeling_internlm.py, lmdeploy/pytorch/modeling/modeling_internlm2.py, lmdeploy/pytorch/modeling/modeling_llama.py, lmdeploy/serve/qos_engine/inner_group_schd.py, lmdeploy/serve/qos_engine/qos_engine.py, lmdeploy/turbomind/turbomind.py, lmdeploy/turbomind/utils.py, lmdeploy/utils.py
This PR https://github.com/InternLM/lmdeploy/pull/1064 replace MMLogger with logging.Logger, but there are two differences.
1) MMLogger has [FilterDuplicateWarning](https://github.com/open-mmlab/mmengine/blob/f79111ecc0eea9fbb1b7d1361a79f7062ca1ac10/mmengine/logging/logger.py#L223)
2) MMLogger doesn't propagate
https://github.com/open-mmlab/mmengine/blob/main/mmengine/logging/logger.py#L292-L306
https://github.com/python/cpython/blob/main/Lib/logging/__init__.py#L1707-L1735
=> make logging.logger's behavior consistent with MMLogger

benchmark/profile_torch_throughput.py, lmdeploy/pytorch/engine/engine.py, lmdeploy/pytorch/engine/request.py, lmdeploy/serve/async_engine.py, lmdeploy/tokenizer.py
session is no longer bind to EngineInstance.
Tested on `chat` and `profile_pytorch_benchmark` with llama-7b
=> remove owned_session

lmdeploy/serve/async_engine.py
After PR 1064
既然 turbomind 加载 hf 模型的时候已经不依赖 model_name 了，那么 pipeline 初始化 turbomind engine 的时候，对于对话模版的处理，应该同 pytorch engine 一致。
修改之后，对于使用 pipeline 接口而言，pytorch / turbomind 的行为是一致的了，对话模版由 pipeline 处理。
=> unify engine initialization in pipeline

benchmark/profile_torch_throughput.py, lmdeploy/pytorch/engine/engine.py, lmdeploy/pytorch/engine/logits_process.py, lmdeploy/pytorch/messages.py, requirements/runtime.txt
add version check
- torch [2.0.0, 2.1.2]
- triton [2.1.0, 2.2.0)
- transformers [4.33.0, 4.37.1]
- peft [0.7.1]
fix `ignore_eos`, model eos and stop words would be moved to bad words when ignore_eos is True.
Tested on `chat` (with manually set `ignore_eos=True`), `benchmark_pytorch_throughput`
=> dependency version check & fix `ignore_eos` logic

src/turbomind/models/llama/LlamaV2.cc
embedding 的拷贝逻辑有两个问题：
1) 靠后的embedding不需要拷贝
2) byte_size 的计算有问题，因为不一定拷贝完整的embedding
考虑下面的情况
```
cacheed: C, length=7
h_input: X, length=5
normal token: A
embedding token: B
embedding offset: [4, 9), [12, 16)
CCCCCXXXXXXX        // cached + h_input
AAAABBBBBAAABBBBAAA // context
```
针对1), 第二个embedding, 7 + 5 - 1 < 12，所以不需要拷贝
针对2), 要更新 begin, end. begin = max(4, 5) = 5; (end - begin) = 4, 拷贝4个元素
=> fix embedding copy size

lmdeploy/turbomind/deploy/source_model/llama.py
some users have *.bin files in their hf model directories like `training_args.bin` which is not weight file.
=> use stricter rules to get weight file 

lmdeploy/pytorch/check_env/__init__.py, lmdeploy/pytorch/check_env/__main__.py, lmdeploy/pytorch/check_env/triton_custom_add.py, lmdeploy/pytorch/engine/engine.py
Check the environment (PyTorch, Triton) before starting the engine.
If there are any dependency failed, the processing exit(1) with error logs:
```bash
2024-02-02 16:41:23,750 - lmdeploy - ERROR - RuntimeError: Triton Error [CUDA]: device kernel image is invalid
2024-02-02 16:41:23,750 - lmdeploy - ERROR - <Triton> environment test failed. Please ensure it has been installed correctly.
```
Tested on `chat` and `profile_pytorch_generation` with/wo tp.
Traceback info has been removed since too many logs might hide the ERROR info.
It would be better if we can change the color of the error info.
=> check pytorch engine environment

docker/Dockerfile, docs/en/index.rst, docs/en/serving/restful_api.md, docs/zh_cn/index.rst, docs/zh_cn/serving/restful_api.md
To test the PR. A new docker image should be built.
```
FROM openmmlab/lmdeploy:latest
ENTRYPOINT ["lmdeploy", "serve", "api_server"]
```
=> Update Dockerfile order to launch the http service by `docker run` directly

lmdeploy/turbomind/turbomind.py
To handle scripts like the following for testing api_server.
```python
import os
import sys
from tqdm import tqdm
from concurrent.futures import ThreadPoolExecutor
from lmdeploy.serve.openai.api_client import APIClient
questions = ['你是谁'] * 1000
num_parallel = 512
def process_one(question, url='0.0.0.0', port='23333'):
client = APIClient('http://{}:{}'.format(url, port))
model_name = client.available_models[0]
msg = [dict(role='user', content=question)]
data = client.chat_completions_v1(model=model_name, messages=msg)
for item in data:
response = item
return response
with ThreadPoolExecutor(max_workers=num_parallel) as executor:
for response in tqdm(executor.map(process_one, questions)):
print(response)
```
=> Use asyncio.Lifoque for turbomind async_stream_infer

lmdeploy/serve/async_engine.py
In https://github.com/InternLM/lmdeploy/issues/1189, the error message is confused due to the usage of `ArgumentError` is not correct. 
Set the first parameter of `ArgumentError` as None to avoid this issue.
=> Fix argument error

lmdeploy/turbomind/turbomind.py
#1138 Introduced `asyncio.Lifoque` while it is not thread-safe for multi-thread function like `forward_callback` or `forward_thread`.
Use normal `LifoQueue` to avoid frequently pop-out items that may pop out the final result.
=> Use LifoQueue for turbomind async_stream_infer

lmdeploy/pytorch/engine/model_agent.py
Update device map when TP.
- If host memory is enough, The model would be loaded on the host and distributed to devices.
- If these is no enough host memory, a device map would be created to load the weight on available devices and distribute them.
=> Update torch TP device map.

lmdeploy/pytorch/models/baichuan.py, lmdeploy/pytorch/models/module_map.py
Tested on 1000 prompts
main
7B batch-size 256
```
concurrency: 256
elapsed_time: 136.351s
first token latency(s)(min, max, ave): 0.268, 14.395, 4.825
per-token latency(s) percentile(50, 75, 95, 99): [0.082, 0.092, 0.186, 0.52]
number of prompt tokens: 251952
number of completion tokens: 227002
token throughput (completion token): 1664.835 token/s
token throughput (prompt + completion token): 3512.653 token/s
RPS (request per second): 7.334 req/s
RPM (request per minute): 440.041 req/min
```
13B batch-size 128
```
concurrency: 128
elapsed_time: 185.828s
first token latency(s)(min, max, ave): 0.231, 11.174, 2.385
per-token latency(s) percentile(50, 75, 95, 99): [0.062, 0.064, 0.191, 0.52]
number of prompt tokens: 251952
number of completion tokens: 227002
token throughput (completion …
```
=> optmize baichuan in pytorch engine

docs/en/inference/pipeline.md, docs/zh_cn/inference/pipeline.md, lmdeploy/pytorch/config.py, lmdeploy/pytorch/engine/model_agent.py, lmdeploy/pytorch/models/chatglm2.py
- optimize performance
- chatglm adapter TP support
before
```
concurrency: 256
elapsed_time: 306.702s
first token latency(s)(min, max, ave): 0.281, 10.159, 1.888
per-token latency(s) percentile(50, 75, 95, 99): [0.083, 0.088, 0.271, 0.444]
number of prompt tokens: 724392
number of completion tokens: 662960
token throughput (completion token): 2161.578 token/s
token throughput (prompt + completion token): 4523.455 token/s
RPS (request per second): 9.781 req/s
RPM (request per minute): 586.889 req/min
```
after
```
concurrency: 256
elapsed_time: 261.317s
first token latency(s)(min, max, ave): 0.203, 9.053, 1.658
per-token latency(s) percentile(50, 75, 95, 99): [0.069, 0.077, 0.242, 0.409]
number of prompt tokens: 724392
number of completion tokens: 662960
token throughput (completion …
```
=> torch optmize chatglm3

lmdeploy/serve/async_engine.py
side effect brought by pr #1188
=> Fix `None` session_len

lmdeploy/pytorch/check_env/__init__.py, lmdeploy/pytorch/engine/cache_engine.py, lmdeploy/pytorch/engine/engine.py, lmdeploy/pytorch/engine/model_agent.py, lmdeploy/pytorch/models/falcon.py, lmdeploy/pytorch/models/gemma.py, lmdeploy/pytorch/models/llama.py, lmdeploy/pytorch/models/module_map.py, lmdeploy/pytorch/models/patch.py
Fix falcon tp
before
```
concurrency: 256
elapsed_time: 184.839s
first token latency(s)(min, max, ave): 0.645, 13.974, 4.690
per-token latency(s) percentile(50, 75, 95, 99): [0.139, 0.147, 0.263, 0.414]
number of prompt tokens: 242197
number of completion tokens: 220686
token throughput (completion token): 1193.938 token/s
token throughput (prompt + completion token): 2504.254 token/s
RPS (request per second): 5.410 req/s
RPM (request per minute): 324.607 req/min
after
```
concurrency: 256
elapsed_time: 128.932s
first token latency(s)(min, max, ave): 0.270, 10.948, 3.440
per-token latency(s) percentile(50, 75, 95, 99): [0.095, 0.102, 0.232, 0.441]
number of prompt tokens: 242197
number of completion tokens: 220686
token throughput (completion token): 1711.640 token/s
token throughput …
=> optimize pytorch engine inference with falcon model

lmdeploy/pytorch/kernels/multinomial_sampling.py
It is true that `bf16_tensor.softmax(1).sum(1)` is not 1.
Which leads to multinomial sampling failed on edge random value.
=> fix bf16 multinomial sampling

lmdeploy/serve/openai/api_server.py
To make the swagger UI clean if no qos functions are applied.
=> Hide qos functions from swagger UI if not applied

src/turbomind/models/llama/LlamaBatch.cc, src/turbomind/models/llama/LlamaBatch.h
In turbomind 2.1, these variables are no longer used.
as titled
=> rm unused var

benchmark/profile_restful_api.py, benchmark/profile_serving.py, benchmark/profile_throughput.py
The sampling request progress is time consuming in the benchmark script. 
Refer to [vllm script](https://github.com/vllm-project/vllm/blob/1ece1ae829dcbc4b1b19b3e2d3042457615e862f/benchmarks/benchmark_serving.py#L70), we can pre-sample the dataset before the filter step to avoid go through all the dataset.
=> Accelerate sample request in benchmark script

lmdeploy/pytorch/engine/engine.py, lmdeploy/pytorch/engine/request.py, lmdeploy/pytorch/models/patch.py, lmdeploy/pytorch/paging/scheduler.py, lmdeploy/utils.py
- log level name would be colored.
- add timer to key function in pytorch engine.
DEBUG mode could be enabled by:
```python
logger = get_logger('lmdeploy')
logger.setLevel(logging.DEBUG)
for handler in logger.handlers:
handler.setLevel(logging.DEBUG)
```
step logs in DEBUG mode:
```log
2024-03-05 15:45:32,977 - lmdeploy - DEBUG - <ScheduleDecoding> take time: 0.01 ms
2024-03-05 15:45:32,977 - lmdeploy - DEBUG - <AsyncStep>: batch_size=1
2024-03-05 15:45:32,977 - lmdeploy - DEBUG - <CreateModelInputs> take time: 0.08 ms
2024-03-05 15:45:32,997 - lmdeploy - DEBUG - <ModelForward> take time: 19.69 ms
2024-03-05 15:45:32,998 - lmdeploy - DEBUG - <SamplingLogits> take time: 1.55 ms
2024-03-05 15:45:32,999 - lmdeploy - DEBUG - <UpdateRunning> take time: 0.04 ms
2024-03-05 15:45:32,999 - …
```
=> Color log formatter

src/turbomind/kernels/attention/attention_universal.h, src/turbomind/kernels/attention/decoding.cu, src/turbomind/kernels/attention/decoding_128_bf16_sm80.cu, src/turbomind/kernels/attention/decoding_128_f16_sm80.cu, src/turbomind/kernels/attention/decoding_config.h, src/turbomind/kernels/attention/decoding_sm80.h
Benchmarks results of various `CTA_H`
A100 80G, batch size 128, seq len 1024, w/o split-kv, in microseconds
| 32:8 | 1      | 2      | 4      |
|------|--------|--------|--------|
| SIMT | 513.70 | 316.26 | 319.70 |
| TC   | 509.66 | 318.91 | 308.35 |
| 48:8 | 1      | 2      | 3      | 6      |
|------|--------|--------|--------|--------|
| SIMT | 755.17 | 382.27 | 354.37 | 367.46<sup>*</sup> |
| TC   | 756.35 | 401.28 | 319.58 | 309.31 |
| 64:8 | 1      | 2      | 4      | 8      |
|------|--------|--------|--------|--------|
| SIMT | 1020   | 497.92 | 406.27 | 985.82<sup>*</sup> |
| TC   | 993.98 | 517.86 | 319.39 | 305.12 |
| 80:8 | 1    | 2      | 5      |
|------|------|--------|--------|
| SIMT | 1260 | 616    | 485.70 |
| TC   | 1230 | 635.52 | 318.75 |
<sup>*</sup>register spill …
=> Add tensor core GQA dispatch for `[4,5,6,8]`

lmdeploy/pytorch/check_env/__init__.py
=> Check bf16 model in torch engine

benchmark/profile_serving.py, lmdeploy/serve/turbomind/chatbot.py
1. If the postprocessing grpc call failed, the `text` variable will be access but not  declared.
https://github.com/InternLM/lmdeploy/blob/e7b2833441be6a4ac374ec191001ba6ae97647e0/lmdeploy/serve/turbomind/chatbot.py#L683
3. If `num_prompts < concurrency`, the `np.concatenate()` will face issue because the array dimension in `stats` is different.
1. Add initialization for `text` variable
2. Filter empty `stats_` array.
=> Fix concatenate issue in profile serving

lmdeploy/messages.py, lmdeploy/pytorch/config.py, lmdeploy/pytorch/engine/engine.py, lmdeploy/pytorch/engine/model_agent.py, lmdeploy/utils.py
runtime intermediate memory usage might lead to OOM if too many cache blocks are using.
Since most intermediate cache are used by `lm_head` in `ModelForCausalLM`, we would leave enough space for the cache and allocate paged cache with rest of the memory.
Tested on V100, prompts with 10k+ input ids.
```python
def main():
model_path = 'Qwen1.5-7B-Chat'
backend_config = PytorchEngineConfig(
session_len=200000,
cache_max_entry_count=0.99)
pipe = pipeline(model_path, backend_config=backend_config)
print('processing...')
gen_config = GenerationConfig(max_new_tokens=1000)
result = pipe([prompt], gen_config=gen_config)
print(result[0].text)
```
=> better cache allocation in pytorch engine

docs/en/inference/vl_pipeline.md, docs/zh_cn/inference/vl_pipeline.md, lmdeploy/model.py, lmdeploy/serve/async_engine.py, lmdeploy/serve/vl_async_engine.py
Add pipeline.chat api for easy use
```python
from lmdeploy import pipeline
pipe = pipeline('InternLM/internlm2-chat-7b/')
sess = pipe.chat('中国的首都是哪个城市')
sess.response()
sess = pipe.chat('美国的首都是哪个城市', session=sess)
sess.response()
sess = pipe.chat('你刚才提到了哪两个城市', session=sess)
sess.response()
```
```python
from lmdeploy import pipeline
pipe = pipeline('/nvme/chenxin/download/tmp/Yi-VL-6B/')
sess = pipe.chat(('描述一下这个图片', 'onzc.jpg'))
sess.response()
sess = pipe.chat('丰富一下细节', session=sess)
sess.response()
```
=> Add pipeline.chat api for easy use

benchmark/profile_generation.py, benchmark/profile_throughput.py, lmdeploy/archs.py, lmdeploy/cli/chat.py, lmdeploy/cli/serve.py, lmdeploy/cli/utils.py, lmdeploy/messages.py, lmdeploy/turbomind/chat.py, lmdeploy/turbomind/deploy/target_model/base.py, tests/test_lmdeploy/test_auto_backend.py
As mentioned in https://github.com/InternLM/lmdeploy/issues/1195, `cache_block_seq_len` is an important parameter for performance. We should expose it to users.
Added argument `--cache-block-seq-len` for serve and chat api, and some benchmark scripts. The default value is 128, which is consistent with the previous internal setting.
=> Expose cache_block_seq_len to API

benchmark/profile_serving.py, lmdeploy/serve/turbomind/chatbot.py
As mentioned in https://github.com/InternLM/lmdeploy/issues/1280, the throughput of Triton inference server is only `3.4` RPS, which is unexpected.
By further investigation, we found there two factors caused the incorrect throughput:
1. The grpc result format conversion in chatbot is time consuming. By fixing it, the throughput increased to `5.0` RPS.
2. In the default setting, the prompt will be decorated by the chat template, which caused the actual prompt tokens is more than the given input. For profile setting, we'd better use fixed prompt length and output length. After disabling the prompt decoration, the throughput increased to `5.9` RPS, which is much closer to the real throughput of Triton inference server.
1. Avoid grpc result format conversion.
2. Use `capability='completion'` …
=> Fix performance issue of chatbot

lmdeploy/serve/async_engine.py, lmdeploy/serve/openai/api_server.py, lmdeploy/utils.py
=> Add more log info for api_server

src/turbomind/python/bind.cpp
In https://github.com/InternLM/lmdeploy/issues/1334#issuecomment-2017418190, there may be some memory leak in `dlpack`. 
For 5000 test prompts:
- before this change, the memory usage will increase from `3110M -> 3660M`
- after this change, the memory usage will increase from `3110M -> 3460M`
There are 200M memory reduced. 
- Return object instead of the pointer, then Python will take over the lifecycle of this object.
=> Fix dlpack memory leak

src/turbomind/triton_backend/llama/LlamaTritonModel.cc, src/turbomind/triton_backend/llama/LlamaTritonModelInstance.cc, src/turbomind/triton_backend/llama/LlamaTritonModelInstance.h
When `torch.cuda.set_device()` is lazy, newly created threads for `LlamaTritonModelInstance::forward` may have no context associated and later `cudaMallocAsync` will die.
We call `cudaSetDevice` unconditionally to ensure a valid context is associated.
=> Fix invalid context for Internstudio platform

benchmark/profile_generation.py, lmdeploy/pytorch/engine/engine.py
https://github.com/InternLM/lmdeploy/issues/1347
=> fix benchmark generation

lmdeploy/pytorch/engine/engine.py, lmdeploy/pytorch/engine/model_agent.py, lmdeploy/pytorch/kernels/pagedattention.py, lmdeploy/pytorch/tools/make_inputs.py, tests/pytorch/tools/test_make_inputs.py
=> fix window attention

src/turbomind/python/bind.cpp
https://github.com/InternLM/lmdeploy/issues/1334
This test code and `valgrind` can help debug this issue:
```python
import asyncio
from lmdeploy import GenerationConfig, TurbomindEngineConfig, pipeline
engine_config = TurbomindEngineConfig(tp=1)
engine = pipeline(model_path='/workdir/llama2_13b_chat',
model_name='llama2',
backend_config=engine_config)
async def infer(prompt, session_id):
async for output in engine.generate(messages=prompt,
session_id=session_id,
stream_response=True,
do_preprocess=False):
print(output.response)
prompts = ['hi']*10
for i, prompt in enumerate(prompts):
asyncio.run(infer(prompt, i))
```
```
valgrind --leak-check=full python test_lmdeploy.py > log.txt 2>&1
```
There are some `definitely lost` in `bind.cpp:125` and `bind.cpp:308`, that's about …
=> Fix memory leak of DLManagedTensor

lmdeploy/pytorch/models/module_map.py, lmdeploy/pytorch/models/qwen.py
update rewritings for the latest `modeling_qwen.py` as in [huggingface](https://huggingface.co/Qwen/Qwen-7B-Chat/blob/main/modeling_qwen.py)
None
=> Update rewritings for qwen

.github/scripts/check_lmdeploy.py, benchmark/profile_triton_python_backend.py, lmdeploy/serve/turbomind/triton_python_backend/README.md, lmdeploy/serve/turbomind/triton_python_backend/client.py, lmdeploy/serve/turbomind/triton_python_backend/config.pbtxt, lmdeploy/serve/turbomind/triton_python_backend/model.py
As mentioned in https://github.com/InternLM/lmdeploy/issues/1309, the Turbomind triton backend is facing some performance issues. So we propose this Python backend. 
We have conducted performance test and OpenCompass evaluation, the results are shown in https://github.com/InternLM/lmdeploy/issues/1309. Its performance is as efficient as the api_server and the evaluation result is also fine.
@lvhan028 @zhyncs
=> Support Triton inference server python backend

lmdeploy/pytorch/engine/model_agent.py
Prealloc runtime cache might leads to no GPU blocks.
This PR reduce `max_prefill_token_num` if no enough gpu blocks can be alloced.
=> update `max_prefill_token_num` for low gpu memory

lmdeploy/archs.py, lmdeploy/serve/async_engine.py
For some jupyter notebook users, the loop can not be used directly.
=> Use new event loop instead of the current loop for pipeline

examples/cpp/llama/llama_triton_example.cc
https://github.com/InternLM/lmdeploy/blob/fdb95313f7b99c44309f504b3f68b622f5fd6523/src/turbomind/models/llama/LlamaBatch.cc#L1015-L1022
=> Fix llama_triton_example

lmdeploy/model.py, lmdeploy/vl/model/llava.py
llava-v1.6-34b use chatml format
https://github.com/haotian-liu/LLaVA/blob/main/llava/eval/run_llava.py#L76
Registry in mmengine treat `.` as scope separator so I replace it with `_`
=> add llava-v1.6-34b template

.github/workflows/daily_ete_test.yml, autotest/tools/convert/test_convert.py, docs/en/benchmark/profile_triton_server.md, docs/zh_cn/benchmark/profile_triton_server.md, lmdeploy/cli/cli.py, lmdeploy/turbomind/deploy/converter.py
The following cases are verified.
```shell
lmdeploy convert llama2 /workspace/models-140/llama2/huggingface/llama-2-7b-chat/ --dst-path workspace/test-converter
lmdeploy convert internlm2 /workspace/models-140/InternLM/internlm2-chat-7b/ --dst-path workspace/test-converter --trust-remote-code
lmdeploy convert qwen /workspace/models-140/Qwen/Qwen-7B-Chat/ --dst-path workspace/test-converter/ --trust-remote-code
lmdeploy convert qwen /workspace/models-140/Qwen/Qwen1.5-7B-Chat/ --dst-path workspace/test-converter
```
=> miss --trust-remote-code in converter, which is side effect brought by pr #1406

lmdeploy/vl/model/utils.py
https://huggingface.co/deepseek-ai/deepseek-vl-1.3b-chat/tree/main
=> Fix loading single safetensor file error

lmdeploy/turbomind/deploy/source_model/qwen_awq.py
=> Support qwen1.5-*-AWQ model inference in turbomind

README.md, README_zh-CN.md, docs/en/supported_models/supported_models.md, docs/zh_cn/supported_models/supported_models.md, lmdeploy/archs.py, lmdeploy/model.py, lmdeploy/turbomind/deploy/converter.py, lmdeploy/turbomind/deploy/source_model/__init__.py, lmdeploy/turbomind/deploy/source_model/internvl.py, lmdeploy/turbomind/deploy/source_model/llama.py, lmdeploy/turbomind/supported_models.py, lmdeploy/vl/model/builder.py, lmdeploy/vl/model/internvl.py, lmdeploy/vl/templates.py, src/turbomind/models/llama/LlamaWeight.cc
support
- https://huggingface.co/OpenGVLab/InternVL-Chat-Chinese-V1-2
- https://huggingface.co/OpenGVLab/InternVL-Chat-Chinese-V1-2-Plus
- https://huggingface.co/OpenGVLab/InternVL-Chat-Chinese-V1-1
- add chat template (internvl_zh)
- add source model (InternVLModel)
- add vision model (InternVLVisionModel)
- add InternVLChatTemplateWrapper
The vision model is big, so we need to reduce kv-cache in order to load the vision model on single gpu. 
With 4 x A100, the memory usage is about 47G x 1 and  35G x 3 when using the following setting. (InternVL-Chat-Chinese-V1-2-Plus)
```
from lmdeploy import pipeline, TurbomindEngineConfig
from lmdeploy.vl import load_image
pipe = pipeline('/home/chenxin/InternVL-Chat-Chinese-V1-2-Plus/', log_level='INFO', …
```
=> support Internvl chat v1.1, v1.2 and v1.2-plus

lmdeploy/serve/vl_async_engine.py
The original implementation is easy to get OOM since there is no extra VRAM for the vl model.
=> Initialize vl encoder first to avoid OOM

lmdeploy/model.py
The generated prompts have space at the begin, but the space and the following word might be a single token. Add space after `Assistant` might lead to unexpected result.
=> remove space in deepseek template

README.md, autotest/utils/get_run_config.py, docs/en/supported_models/supported_models.md, docs/zh_cn/supported_models/supported_models.md
as titled
ref https://github.com/InternLM/lmdeploy/issues/1459
as titled
=> update doc for llama3

lmdeploy/serve/openai/api_client.py, lmdeploy/serve/openai/api_server.py, lmdeploy/serve/openai/protocol.py
https://github.com/InternLM/lmdeploy/issues/1439?notification_referrer_id=NT_kwDOAnO4m7QxMDI4Nzk5ODcyMjo0MTEzODMzMQ#issuecomment-2060474133
=> add interactive api in service for VL models

src/turbomind/layers/sampling_layers/BaseSamplingLayer.h
Topk, Topp layers are initialized by `new TopKSamplingLayer` and `new TopPSamplingLayer` and repetition_penalty_workspace_ may has a invalid ptr. When invoke `allocator_->free((void**)(&repetition_penalty_workspace_)); ` there maybe a warning `TM_LOG_WARNING("pointer_mapping_ does not have information of ptr at %p.", address);`
=> fix free repetition_penalty_workspace_ buffer

lmdeploy/model.py, tests/test_lmdeploy/test_model.py
=> Feat: format internlm2 chat template

README.md, README_zh-CN.md, docs/en/supported_models/supported_models.md, docs/zh_cn/supported_models/supported_models.md, lmdeploy/model.py, lmdeploy/pytorch/models/module_map.py, lmdeploy/pytorch/models/starcoder2.py, lmdeploy/pytorch/supported_models.py
Support starcoder2 https://huggingface.co/bigcode/starcoder2-7b
=> support starcoder2

lmdeploy/serve/async_engine.py
=> fix local variable 'response' referenced before assignment in async_engine.generate

README.md, README_zh-CN.md, docs/en/supported_models/supported_models.md, docs/zh_cn/supported_models/supported_models.md, lmdeploy/model.py, lmdeploy/turbomind/deploy/source_model/internlm2.py, lmdeploy/turbomind/deploy/source_model/internvl.py, lmdeploy/vl/model/internvl.py
support https://huggingface.co/OpenGVLab/InternVL-Chat-V1-5
=> support OpenGVLab/InternVL-Chat-V1-5

docs/zh_cn/quantization/w8a8.md
Fix a typo in w8a8.md
Fix a typo in w8a8.md
2. The modification is covered by …
=> Fix typo in w8a8.md

docs/en/build.md, docs/zh_cn/build.md
The earlier version of the build.md file lacked essential commands and prompts, leading to compilation errors.  As a reuslt, 
I've simply refined build.md.
docs/en/build.md
docs/zh-cn/build.md
=> complete build.md

requirements/runtime.txt
pip install lmdeploy will fail on windows because triton doesn't support windows.
https://pypi.org/project/triton/#files
=> fix installation requirements for windows

docs/en/serving/api_server_vl.md, docs/zh_cn/serving/api_server.md
Docs update in relation to issue https://github.com/InternLM/lmdeploy/issues/1514 
Updating documentation around Docker images for new users.
It should be made clear to users what is expected, and a way to resolve issues described.
Adding a warning about dependencies and an example of how to resolve by creating a new Docker image.
=> Update docker docs for VL api

lmdeploy/version.py
1. There are strong requests to release the inference support of internvl v1.5 soon
2. Several critical issues were resolved
- An overflow error occurred in turbomind when the context length was large
- setup error on the Windows platform
- empty chunk returned by the api_server
- inefficient pipeline
=> bump version to v0.4.1

lmdeploy/vl/utils.py
This improves the performance in a significant way when dealing with higher batch sizes on GPU servers which have lots of 'small' cores and the operations are run in sync in the same core. PNG compression effectively becomes the bottleneck which is totally unnecessary.
For sharing some numbers, on an H100 when running `xtuner/llava-llama-3-8b-v1_1-hf` (with int8 KV cache quantization), the timings go from ~6 seconds to ~3 seconds at bs=16. Its almost doubling the performance (and reducing the unutilized GPU times).
=> Use a faster format for images in VLMs

tests/test_lmdeploy/test_tokenizer.py
The following script failed with the latest transformers. The output differs from the input after encode and decode functions.
```python
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained(
'WizardLM/WizardLM-70B-V1.0', trust_remote_code=True)
prompt = ' '
encoded = tokenizer.encode(prompt)
decoded = tokenizer.decode(encoded)  # ' ' was decoded to '<s> ' actually
assert decoded == prompt
```
=> Fix transformers 4.41.0 prompt may differ after encode decode

src/turbomind/models/llama/LlamaBatch.cc
Related to #1634
Currently the scaling factor is computed by prompt_length + max_new_tokens, which may cause the scale to be slightly larger than expected.
=> Fix NTK scaling

docs/en/inference/vl_pipeline.md, docs/zh_cn/inference/vl_pipeline.md, lmdeploy/__init__.py, lmdeploy/cli/serve.py, lmdeploy/cli/utils.py, lmdeploy/messages.py, lmdeploy/serve/vl_async_engine.py, lmdeploy/turbomind/turbomind.py, lmdeploy/vl/engine.py, lmdeploy/vl/model/builder.py, lmdeploy/vl/model/deepseek.py, lmdeploy/vl/model/internvl.py, lmdeploy/vl/model/internvl_llava.py, lmdeploy/vl/model/llava.py, lmdeploy/vl/model/mini_gemeni.py, lmdeploy/vl/model/qwen.py, lmdeploy/vl/model/utils.py, lmdeploy/vl/model/xcomposer2.py, lmdeploy/vl/model/yi.py, lmdeploy/vl/templates.py, requirements/runtime.txt, src/turbomind/layers/sampling_layers/BaseSamplingLayer.cc, src/turbomind/layers/sampling_layers/TopKSamplingLayer.cu, src/turbomind/layers/sampling_layers/TopPSamplingLayer.cu, src/turbomind/triton_backend/llama/LlamaTritonModel.cc
https://github.com/InternLM/lmdeploy/issues/1563
=> Balance vision model weights on multi gpus

docs/en/inference/vl_pipeline.md, docs/zh_cn/inference/vl_pipeline.md, lmdeploy/model.py, lmdeploy/serve/vl_async_engine.py, lmdeploy/vl/templates.py, tests/test_lmdeploy/test_vl_template.py
for some models, the location of the image token is not restricted, in this case, the user should insert the image token manually.
=> Custom vl user input

lmdeploy/pytorch/kernels/pagedattention.py, tests/pytorch/kernel/test_paged_attention.py
enable tensorcore in decoding MHA kernel.
```
first token latency(s)(min, max, ave): 1.151, 20.570, 5.350
per-token latency(s) percentile(50, 75, 95, 99): [0.074, 0.087, 0.387, 0.515]
number of prompt tokens: 684711
number of completion tokens: 624144
token throughput (completion token): 1647.393 token/s
token throughput (prompt + completion token): 3454.650 token/s
RPS (request per second): 7.918 req/s
RPM (request per minute): 475.100 req/min
```
```
concurrency: 256
elapsed_time: 346.817s
first token latency(s)(min, max, ave): 2.643, 21.116, 5.051
per-token latency(s) percentile(50, 75, 95, 99): [0.065, 0.083, 0.407, 0.504]
number of prompt tokens: 684711
number of completion tokens: 624144
token throughput (completion token): 1799.636 token/s
token throughput (prompt + completion …
```
=> Optimize GQA/MQA

lmdeploy/archs.py
Fix #1717 
- remove `torchvision` from the env and test Llama3
- test llava with torchvision installed
=> lazy import VLAsyncEngine to avoid bringing in VLMs dependencies when deploying LLMs

docker/Dockerfile
Failed with `lmdeploy check_env` for latest `setuptools==70.0.0`,  use `setuptools==69.5.1` to fix it.
```
File "/opt/py38/bin/lmdeploy", line 33, in <module>
sys.exit(load_entry_point('lmdeploy', 'console_scripts', 'lmdeploy')())
File "/opt/lmdeploy/lmdeploy/cli/entrypoint.py", line 37, in run
args.run(args)
File "/opt/lmdeploy/lmdeploy/cli/cli.py", line 195, in check_env
env_info = collect_env()
File "/opt/py38/lib/python3.8/site-packages/mmengine/utils/dl_utils/collect_env.py", line 73, in collect_env
CUDA_HOME = _get_cuda_home()
File "/opt/py38/lib/python3.8/site-packages/mmengine/utils/dl_utils/collect_env.py", line 25, in _get_cuda_home
from torch.utils.cpp_extension import CUDA_HOME
File "/opt/py38/lib/python3.8/site-packages/torch/utils/cpp_extens …
```
=> lock setuptools version in dockerfile

lmdeploy/turbomind/deploy/converter.py, lmdeploy/turbomind/deploy/target_model/base.py, lmdeploy/turbomind/turbomind.py, tests/test_lmdeploy/test_turbomind/test_converter.py
The `--cache-max-entry-count` parameter is not working correctly, causing GPU RAM to be exceeded unexpectedly.
Add an initialization step immediately following the creation of the default `TurbomindModelConfig` object.
=> Fix param `--cache-max-entry-count` is not taking effect (#1758)

lmdeploy/turbomind/deploy/source_model/deepseek_vl.py, lmdeploy/turbomind/deploy/source_model/internlm2.py, lmdeploy/turbomind/deploy/source_model/internvl.py, lmdeploy/turbomind/deploy/source_model/llama.py, lmdeploy/turbomind/deploy/source_model/xcomposer2.py, lmdeploy/turbomind/deploy/source_model/xcomposer2_awq.py, tests/test_lmdeploy/test_turbomind/test_converter.py, tests/test_lmdeploy/test_utils.py
qwen2 1.5b set `tie_word_embeddings=True`.
In this case, the output layer and the token embedding layer share the same weight
=> support qwen2 1.5b

lmdeploy/vl/templates.py, lmdeploy/vl/utils.py, tests/test_lmdeploy/test_vl_encode.py
- Avoid repeated encoding or decoding of images, encode raw data to base64 format directly. 
- Skip image input if failed to get the file.
=> Encode raw image file to base64

lmdeploy/messages.py, lmdeploy/pytorch/engine/engine_instance.py
- new response type: `INPUT_LENGTH_ERROR`
- skip oversized inputs
=> skip inference for oversized inputs

lmdeploy/vl/engine.py
https://github.com/InternLM/lmdeploy/issues/1759
=> More accurate time logging for ImageEncoder and fix concurrent image processing corruption

lmdeploy/turbomind/turbomind.py
as titled
When the hf model is in awq format, there is no need to explicitly specify the model-format as awq.
```bash
python3 -m lmdeploy serve api_server /workdir/Yi-6B-Chat-4bits
```
@lvhan028 @AllentDan May you help review this pr? Thanks.
The modification is simple. I didn't write it as a function, but if needed, I am more than happy to make the changes.
1. Pre-commit or other linting tools are used to fix the potential lint …
=> feat: auto set awq model_format from hf

lmdeploy/vl/model/qwen.py
```
from lmdeploy import pipeline
from lmdeploy.vl import load_image
pipe = pipeline('/nvme/shared/Qwen-VL-Chat/', log_level='INFO')
im = load_image('tiger.jpeg')
pipe.vl_encoder.forward([im])
```
```
File "/home/chenxin/miniconda3/envs/38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
return forward_call(*args, **kwargs)
File "/home/chenxin/.cache/huggingface/modules/transformers_modules/visual.py", line 149, in forward
self._repeat(q, N) + self.pos_embed.unsqueeze(1),
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:7 and cuda:6!
```
https://huggingface.co/Qwen/Qwen-VL-Chat/blob/main/visual.py#L148-L152
=> fix qwen-vl-chat

benchmark/profile_throughput.py, lmdeploy/pytorch/chat.py, lmdeploy/serve/async_engine.py, lmdeploy/serve/gradio/vl.py, lmdeploy/tokenizer.py, lmdeploy/turbomind/chat.py
#1743
Please **note** that detokenizing with prompt token ids is slightly slower than without. The faster the model, the bigger the influence. In my testing on internlm2-chat-1_8b, it could be about 3% slower. (49.94 RPS vs 51.55 RPS).
Update: tested internlm2-chat-7b, the influence was so small that it could be dismissed (21.984 RPS vs 21.815 RPS). The current implement performs better which could be a measurement error.
=> Detokenize with prompt token ids

lmdeploy/cli/chat.py, lmdeploy/cli/cli.py
```
AssertionError: usage: lmdeploy [-h] [-v] {lite,serve,convert,list,check_env,chat} ...
lmdeploy: error: unrecognized arguments: --cap completion
```
=> [side-effect] bring back "--cap" argument in chat cli

lmdeploy/pytorch/models/qwen2.py
fix https://github.com/InternLM/lmdeploy/issues/1885
Hi @lvhan028 @grimoire @RunningLeon @AllentDan May you help review this pr? Thanks.
as titled
=> fix qwen2 cache_position for PyTorch Engine when transformers>4.41.2

lmdeploy/cli/utils.py
as titled cc @lvhan028 @AllentDan 
as titled
=> docs: update cache-max-entry-count help message

debug.sh, tests/csrc/unittests/test_sampling_layer.cu
fix SamplingDecodeTest and SamplingDecodeTest2 unittest failure
```bash
mkdir bld && cd bld && bash ../debug.sh && ninja -j48 && ./bin/unittest
```
Hi @lzhangzz @irexyc @lvhan028 May you help review this pr? Thanks.
as titled
=> fix SamplingDecodeTest and SamplingDecodeTest2 unittest failure

lmdeploy/serve/openai/api_server.py, lmdeploy/serve/openai/protocol.py
Return the usage info in stream response.
1. add `usage: Optional[UsageInfo]` in `ChatCompletionStreamResponse`
2. return `usage` in `completion_stream_generator` while `res.finish_reason is not None`
No.
No.
3. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness.
4. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all …
=> Add usage in stream response

README.md, docs/en/supported_models/supported_models.md, docs/zh_cn/supported_models/supported_models.md, lmdeploy/model.py, lmdeploy/pytorch/configurations/gemma.py, lmdeploy/pytorch/engine/engine.py, lmdeploy/pytorch/models/gemma.py, lmdeploy/pytorch/models/module_map.py, lmdeploy/pytorch/supported_models.py
Gemma and Gemma2 code share a lot in common.
=> support gemma2 in pytorch engine

lmdeploy/cli/serve.py, lmdeploy/serve/gradio/api_server_backend.py, lmdeploy/serve/gradio/app.py, lmdeploy/serve/gradio/turbomind_coupled.py, requirements/serve.txt
Please note for gradio>4. The proxy policy was changed. You may get `httpcore.ConnectTimeout: timed out` of `_do_normal_analytics_request` function.
=> Upgrade gradio

.github/scripts/eval_opencompass_config.py, .github/workflows/benchmark.yml, .github/workflows/daily_ete_test.yml, .github/workflows/evaluate.yml, .github/workflows/pr_ete_test.yml, autotest/config.yaml, autotest/interface/pipeline/test_pipeline_longtext_func.py, autotest/utils/config_utils.py, autotest/utils/get_run_config.py, autotest/utils/pipeline_chat.py, autotest/utils/run_client_chat.py
1. add internlm2.5 models into testcase and oc evaluation configs
2. fix transformers's version in dailytest, cannot do vl quatization on transformers 4.42+
3. fix opencompass's version, because newest oc code need scikit_learn==1.5.0 which need python>=3.9.
4. update vl pipeline testcase for deepseek
5. add prompt length = 1 in benchmark
6. git action is unstable because of https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/ , set env to make action use node16
=> [ci] add internlm2.5 models into testcase

lmdeploy/serve/turbomind/triton_python_backend/README.md
as titled ref https://github.com/triton-inference-server/server/issues/4996
cc @lvhan028 @zhulinJulia24 @AllentDan @grimoire @ispobock 
as titled
=> fix: set PYTHONIOENCODING to UTF-8 before start tritonserver

lmdeploy/pytorch/models/mistral.py, lmdeploy/pytorch/models/mixtral.py
as titled cc @grimoire @RunningLeon @lvhan028 
tested with `Mixtral-8x7B-Instruct-v0.1` https://huggingface.co/mistralai/Mixtral-8x7B-Instruct-v0.1
```bash
python3 -m lmdeploy serve api_server /workdir/Mixtral-8x7B-Instruct-v0.1 --tp 2
```
transformers version: 4.42.3
same as https://github.com/InternLM/lmdeploy/pull/1886
2. The modification is …
=> fix mixtral and mistral cache_position

docs/en/conf.py, docs/zh_cn/conf.py, requirements/docs.txt
Fix table rendering for readthedocs
before: https://lmdeploy.readthedocs.io/en/latest/supported_models/supported_models.html#models-supported-by-turbomind
after:  https://lmdeploy--1998.org.readthedocs.build/en/1998/supported_models/supported_models.html#models-supported-by-turbomind
- remove `sphinx_markdown_tables` in `conf.py` for docs
None …
=> Fix table rendering for readthedocs

lmdeploy/messages.py, lmdeploy/vl/engine.py
- thread-safe image encoder for multi-threaded use of pipeline api
- add exception handler to `run_in_executor`
some issues that may be related :
https://github.com/InternLM/lmdeploy/issues/1981
https://github.com/InternLM/lmdeploy/issues/1992
https://github.com/InternLM/lmdeploy/issues/2004
=> Add exception handler to imge encoder

.github/workflows/cuda11.8-whl-release.yml, .github/workflows/pypi.yml, .github/workflows/windows-x64-gpu.yml, builder/windows/setup_cuda.ps1
`Jimver/cuda-toolkit` setup is too slow.
I tested this change with https://github.com/zhyncs/lmdeploy-build/commit/6df19c57cc6f8a3867460e6a229a6b30e89fda99
And the workflow time is reduced by **half an hour**. ref https://github.com/zhyncs/lmdeploy-build/actions
cc @irexyc @RunningLeon @lvhan028 
as titled
=> misc: replace slow Jimver/cuda-toolkit

src/turbomind/utils/allocator.h
Disable peer access code because we don't have custom all-reduce yet and it slows down allocation in TP mode like A LOT.
=> Disable peer access code

lmdeploy/turbomind/turbomind.py
When starting the service, sometimes the server is successfully started, but the turbomind engine is actually not created successfully due to cuda out of memory. Current thread usage hide the exception.
some issues may be related
https://github.com/InternLM/lmdeploy/issues/1992
=> raise thread exception

lmdeploy/model.py, lmdeploy/pytorch/chat.py, lmdeploy/turbomind/chat.py, tests/test_lmdeploy/test_model.py
Since the triton inference server backend "turbomind_backend" was removed in #1986, the `session_len` accessed by the removed `Chatbot` can be deleted too.
=> Remove `session_len` and deprecated short names of the chat templates

README.md, README_zh-CN.md, docs/en/supported_models/supported_models.md, docs/zh_cn/supported_models/supported_models.md
Qwen not QWen
If this PR introduces a new feature, it is better to list some use cases here, and update the …
=> docs: fix Qwen typo

lmdeploy/model.py, tests/test_lmdeploy/test_model.py
Make modifications to the method to avoid leaking from name check. Cooperating with langgraph agent nodes tutorial.
Hello, when I was following the tutorial in [LangGraph Multi Agent System](https://langchain-ai.github.io/langgraph/tutorials/multi_agent/multi-agent-collaboration/) to build a multi-agent program, I was also deploying local LLM using our LMdeploy tool with `InternLM2.5-7b-chat`. And I was using langchain's `ChatOpenAI` class to intereact with my local serving system. Like this:
```python
llm = ChatOpenAI(model="/root/.cache/modelscope/hub/Shanghai_AI_Laboratory/internlm2_5-7b-chat", 
api_key="test",
base_url="http://localhost:23333/v1")
```
And after running their code, I found error from our serving sys:
```
INFO:     127.0.0.1:40438 - "POST /v1/chat/completions HTTP/1.1" …
```
=> Strict check for `name_map` in `InternLM2Chat7B`

lmdeploy/turbomind/deploy/target_model/base.py, src/turbomind/models/llama/LlamaBatch.cc, src/turbomind/models/llama/LlamaBatch.h, src/turbomind/models/llama/SequenceManager.cc, src/turbomind/models/llama/SequenceManager.h, src/turbomind/models/llama/llama_params.h, src/turbomind/models/llama/unified_decoder.cc, src/turbomind/models/llama/unified_decoder.h, src/turbomind/triton_backend/llama/LlamaTritonModel.cc
- Add `max_prefill_token_num`, decoupled with `max_context_token_num`
- max_prefill_token_num (>= max_batch_size): max number of prefill tokens in a forward pass
- max_context_token_num (>= session_len): max number of context tokens (including history) in a forward pass
- Fix data race in chunked prefill
Memory consumption is greatly reduced for large session_len.
=> Fix chunked prefill

.github/workflows/docker.yml, docker/Dockerfile, generate.sh
update base image to cuda12.4
requested in https://github.com/InternLM/lmdeploy/issues/2164
Change dockerfile base image and support cu118 and cu124
```
cd ~/lmdeploy
docker build . -f docker/Dockerfile -t lmdeploy:cu12 --build-arg CUDA_VERSION=cu12
```
```
cd ~/lmdeploy
docker build . -f docker/Dockerfile -t lmdeploy:cu11 --build-arg CUDA_VERSION=cu11
```
https://github.com/RunningLeon/lmdeploy/actions/runs/10211052906
1. …
=> update base image to support cuda12.4 in dockerfile

src/turbomind/kernels/stop_criteria_kernels.cu, src/turbomind/layers/DynamicDecodeLayer.cc, src/turbomind/models/llama/LlamaBatch.cc
as we don't need the value of `should_stop` at all.
=> Stop synchronizing for `length_criterion`

README.md, README_ja.md, README_zh-CN.md
I created Japanese translated README.
=> docs: add Japanese README

src/turbomind/models/llama/LlamaBatch.cc, src/turbomind/models/llama/LlamaBatch.h, src/turbomind/models/llama/LlamaV2.cc, src/turbomind/models/llama/LlamaV2.h, src/turbomind/triton_backend/llama/LlamaTritonModel.cc, src/turbomind/triton_backend/llama/LlamaTritonModelInstance.cc, src/turbomind/triton_backend/llama/LlamaTritonModelInstance.h, src/turbomind/utils/allocator.h
Add an extra allocator to allocate from peer access enabled memory pools. This may fix NCCL related errors on non-NVLink systems after #2082
#2204
#2195
=> Add peer-access-enabled allocator

lmdeploy/messages.py, lmdeploy/pytorch/engine/engine.py
=> remove eviction param

setup.py
pip 安装时根据编程语言版本过滤，python 3.12搜索不到相应的包
=> Update python support version 

src/turbomind/models/llama/LlamaDecoderLayerWeight.cc
For debugging purpose. The fused SILU is acting directly on F32 accumulator (without casting to F16 back and forth) and the result is slightly different from non-fused version (albeit having higher precision)
=> Add environment variable to control SILU fusion

lmdeploy/cli/lite.py, lmdeploy/lite/apis/gptq.py, lmdeploy/lite/modeling/__init__.py, lmdeploy/lite/modeling/internlm2_gptq.py, lmdeploy/lite/utils/calib_dataloader.py
Only supports models that auto-gptq supports.
=> Add auto_gptq to lmdeploy lite

docker/Dockerfile_aarch64_ascend
Using dlinfer instead of deeplink.framework in Dockerfile build for device=`ascend`
Update Dockerfile_aarch64_ascend, using `pip3 install dlinfer-ascend==0.1.0` to support `ascend`,
`torch_npu` is used internally.
3. If the …
=> build: update ascend dockerfile

docker/Dockerfile
nvidia-nccl-cu11 is built on cuda11.0 which is not met to capture cudagraph in TP mode.
Error log from PR #2104
```
File "/opt/py3/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 75, in wrapper
return func(*args, **kwargs)
File "/opt/py3/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2219, in all_reduce
work = group.allreduce([tensor], opts)
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:2395, invalid usage (run with NCCL_DEBUG=WARN for details), NCCL version 2.19.3
ncclInvalidUsage: This usually reflects invalid usage of NCCL library.
Last error:
NCCL cannot be captured in a graph if either it wasn't built with CUDA runtime >= 11.3 or if the installed …
```
=> build nccl in dockerfile for cuda11.8

lmdeploy/cli/serve.py, lmdeploy/cli/utils.py, lmdeploy/messages.py, lmdeploy/pytorch/engine/engine.py, lmdeploy/serve/async_engine.py, lmdeploy/turbomind/turbomind.py, lmdeploy/utils.py
Set the default value of `max_batch_size` None. 
When users don't specify this value, LMDeploy set the `max_batch_size` according to the device. 
The rules are:
A100, A800 -> 256
H100, H800 -> 512
Other cuda devices -> 128
ascend -> 16
=> automatically set max_batch_size according to the device when it is not specified

lmdeploy/cli/cli.py, lmdeploy/cli/serve.py, lmdeploy/cli/utils.py, lmdeploy/messages.py, lmdeploy/pytorch/config.py, lmdeploy/pytorch/engine/engine.py, lmdeploy/pytorch/engine/model_agent.py, lmdeploy/turbomind/chat.py, lmdeploy/turbomind/deploy/converter.py, lmdeploy/turbomind/deploy/target_model/base.py, lmdeploy/turbomind/turbomind.py, src/turbomind/kernels/attention/attention.cu, src/turbomind/python/bind.cpp, src/turbomind/triton_backend/llama/LlamaTritonModel.cc, tests/test_lmdeploy/test_turbomind/test_converter.py
User can specify data type from ['auto', 'float16', 'bfloat16']
Resolve https://github.com/InternLM/lmdeploy/issues/1846
=> Support user-sepcified data type

lmdeploy/serve/utils.py
This PR is to solve the following issue,
- #2453
Following the discussion in the above issue, I just modified one line as follows, 
https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/serve/utils.py#L219
`_logits = _logits.cpu()`   
-> `_logits = _logits.float().cpu()`
I tried the same code introduced in #2453 and confirmed it works well.
```
$ ipython
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.15.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]: from transformers import AutoTokenizer
...: from lmdeploy import pipeline
...: model_repoid_or_path='internlm/internlm2_5-7b-chat'
...: pipe = pipeline(model_repoid_or_path)
...: tokenizer = AutoTokenizer.from_pretrained(model_repoid_or_path, …
```
=> Fix "TypeError: Got unsupported ScalarType BFloat16"

lmdeploy/pytorch/backends/ascend/op_backend.py
This PR fix ascend atten_mask when (is_prefill and is_paged_prefill).
Modify the logic for calculating ascend atten_mask.
1. Pre-commit or other linting tools …
=> fix ascend atten_mask

lmdeploy/pytorch/backends/cuda/activation.py, lmdeploy/pytorch/backends/cuda/op_backend.py, lmdeploy/pytorch/kernels/cuda/activation.py, lmdeploy/pytorch/kernels/cuda/apply_rotary_pos_emb.py, lmdeploy/pytorch/kernels/cuda/fused_moe.py, lmdeploy/pytorch/kernels/cuda/rms_norm.py, tests/pytorch/kernel/test_activation.py
- Add kernel to fuse silu and mul in MLP.
- Optimize apply_rotary kernel and rmsnorm kernel.
=> Add silu mul kernel

lmdeploy/pytorch/engine/engine.py
prefill enough requests before decoding.
=> Pytorch Engine reduce TTFT

README.md, README_ja.md, README_zh-CN.md, docs/en/supported_models/supported_models.md, docs/zh_cn/supported_models/supported_models.md, lmdeploy/model.py, lmdeploy/pytorch/configurations/minicpm3.py, lmdeploy/pytorch/models/minicpm3.py, lmdeploy/pytorch/models/module_map.py
`update_weights` function is not obvious to users. @grimoire
=> Support minicpm3-4b

lmdeploy/cli/entrypoint.py
Previously, the served model name is the full path of the downloaded model, which is not user-friendly.
=> set served model name being repo_id from hub before it is downloaded

lmdeploy/pytorch/backends/ascend/op_backend.py
Through practical tests on ascend platform, it is found that the `AscendOpsBackend.update_step_context()` function has some room for performance optimization, especially in the prefill stage and when the input sequence is long (for example, when the input sequence contains more image tokens). Because the original code uses a slower loop to calculate kv_start_indices.
The goal of this PR is to **improve the performance** of the `AscendOpsBackend.update_step_context()` function with more efficient code.
This PR is only changed the `lmdeploy/pytorch/backends/ascend/op_backend.py` file. The main modification is to optimize the `kv_start_indices` calculation process from a normal loop to using `slot_tables` and `slot_indices` (inspired by `atb_models/examples/server` in the Ascend …
=> optimize performance of ascend backend's update_step_context() by calculating kv_start_indices in a new way

lmdeploy/cli/serve.py, lmdeploy/cli/utils.py, lmdeploy/serve/openai/api_server.py
This PR is to add a new argument option to disable the `/`, `/openapi.json`, `/redoc` and `/docs/oauth2-redirect`. My company doesn't allow using such endpoints in production environments. A new argument is added to disable the endpoint
reference doc: https://fastapi.tiangolo.com/tutorial/metadata/
Add argument `--disable-fastapi-docs`
N/A
```
lmdeploy serve api_server facebook/opt-125m --disable-fastapi-docs
```
- Before
- After
2. The …
=> [Feature] Add argument to disable FastAPI docs

lmdeploy/pytorch/check_env/__init__.py, lmdeploy/pytorch/models/llama.py, requirements/runtime.txt, tests/pytorch/kernel/test_apply_rotary.py, tests/pytorch/kernel/test_multinomial_sampling.py, tests/pytorch/kernel/test_rms_norm.py
- paged attention kernel does not work on triton[2.2.0~2.3.1] on device with cap7.x.
- vicuna does not have `mlp_bias`.
- 7.x device doesn't t support bf16.
=> add check for device with cap 7.x

README.md, README_ja.md, README_zh-CN.md, lmdeploy/utils.py
=> Add instruction for downloading models from openmind hub

.github/workflows/benchmark.yml, .github/workflows/daily_ete_test.yml, .github/workflows/evaluate.yml, .github/workflows/stable.yml
Currently dependency package's version release used by lmdeploy may cause testcase to fail. 
In order to adjust the dependency package's version more conveniently, use local file to specify the dependency package‘s version.
=> [ci] use local requirements for test workflow

lmdeploy/pytorch/engine/model_agent.py
As some developers would develop custom device_type for Ascend npu, it's better to resolve the exit problem with tp > 2 on  ascend platform with more general check instead of `device_type =='ascend'`. We change this behavior into checking with we have already imported 'torch_npu' module.
Change an if-branch condition to make it more general.
If so, please describe how it breaks the compatibility and how the …
=> fix: make exit_flag verification for ascend more general

lmdeploy/pytorch/engine/engine.py, lmdeploy/pytorch/engine/logits_process.py, lmdeploy/pytorch/engine/model_agent.py
After we use graph mode on Ascend device, we saw a big overhead on pre and post process. 
1. remove unnecessary to(cuda)/clone
2. only use one cuda stream …
=> refine pre-post-process

lmdeploy/pytorch/kernels/cuda/alibi_pagedattention.py, lmdeploy/pytorch/kernels/cuda/pagedattention.py
sm7.x has small smem.
reduce BLOCK_M to support MLA
=> small block_m for sm7.x

lmdeploy/pytorch/engine/model_agent.py
python 3.8 don't support  syntax like this: with (ctx1, ctx2): .
remove the extra parentheses.
=> Fix error in python3.8.

benchmark/profile_generation.py, benchmark/profile_pipeline_api.py, benchmark/profile_throughput.py, lmdeploy/cli/cli.py, lmdeploy/cli/serve.py, lmdeploy/cli/utils.py
=> add --eager-mode to cli

docs/en/get_started/ascend/get_started.md, docs/zh_cn/get_started/ascend/get_started.md
=> Update get_started tutorial about deploying on ascend platform

lmdeploy/pytorch/backends/dlinfer/activation.py, lmdeploy/pytorch/backends/dlinfer/ascend/graph_runner.py, lmdeploy/pytorch/backends/dlinfer/ascend/op_backend.py, lmdeploy/pytorch/backends/dlinfer/op_backend.py, lmdeploy/pytorch/backends/dlinfer/rotary_embedding.py, lmdeploy/pytorch/engine/logits_process.py, lmdeploy/pytorch/kernels/dlinfer/activation.py, lmdeploy/pytorch/kernels/dlinfer/apply_rotary_pos_emb.py, lmdeploy/pytorch/kernels/dlinfer/pagedattention.py, lmdeploy/pytorch/models/llama.py
Add ascend's graph mode for following models when tp=1:
Llama2, InternLM2, Qwen2
Other models aren't verified on ascend's graph mode, may or may not be worked, we show warning when using ascend's
graph mode on other models.
Add AscendGraphRunner, silu_and_mul ops and rotary_embedding ops on ascend.
=> [ascend] add ascend graph mode

docs/en/get_started/ascend/get_started.md, docs/zh_cn/get_started/ascend/get_started.md
add nnal installation into Ascend get_started.md
4. The documentation has …
=> Update ascend get_started tutorial about installing nnal

docker/Dockerfile_aarch64_ascend
In  docker/Dockerfile_aarch64_ascend we have two build errors in last updates:
1. incorrect nnal package name
2. not sourcing CANN set_env.sh, nnal build would be failed in installation
Add env source and fix package name in docker/Dockerfile_aarch64_ascend
=> fix build error in ascend dockerfile

lmdeploy/vl/model/llava_hf.py
issue #2497
python3 -m lmdeploy.serve.openai.api_server path/to/llava_hf/llava-interleave-qwen-7b-hf
```text
File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/data/willow/Repo/lmdeploy/lmdeploy/serve/openai/api_server.py", line 1376, in <module>
fire.Fire(serve)
File "/opt/py38/lib/python3.8/site-packages/fire/core.py", line 143, in Fire
component_trace = _Fire(component, args, parsed_flag_args, context, name)
File "/opt/py38/lib/python3.8/site-packages/fire/core.py", line 477, in _Fire
component, remaining_args = _CallAndUpdateTrace(
File "/opt/py38/lib/python3.8/site-packages/fire/core.py", line 693, in …
```
=> bugfix: llava-hf/llava-interleave-qwen-7b-hf (#2497)

lmdeploy/pytorch/models/qwen2_vl.py
When using qwen2-vl, it will encounter the following error. It is not clear since the [outermost scope](https://github.com/InternLM/lmdeploy/blob/v0.6.1/lmdeploy/pytorch/engine/engine.py#L772-L773) used torch.inference_mode().
related pr
https://github.com/InternLM/lmdeploy/pull/2632
```
2024-10-25 23:09:36,288 - lmdeploy - WARNING - async_engine.py:505 - Since v0.6.0, lmdeploy add `do_sample` in GenerationConfig. It defaults to False, meaning greedy decoding. Please set `do_sample=True` if sampling  decoding is needed
1402024-10-25 23:09:44,250 - lmdeploy - ERROR - request.py:21 - Engine loop failed with error: Inplace update to inference tensor outside InferenceMode is not allowed.You can make a clone to get a normal tensor before doing inplace update.See …
```
=> fix inference mode error for qwen2-vl

docs/en/get_started/ascend/get_started.md, docs/zh_cn/get_started/ascend/get_started.md, lmdeploy/pytorch/backends/dlinfer/ascend/graph_runner.py
1. Since latest InternLM2 uses NTK in RoPE, graph mode cannot support it for now. llama3-8B is tested in graph mode.
2. Since we cannot distinguish between llama3 and llama3.1, warning message always show in graph mode.
3. Since graph mode is BC-breaking feature, we made the message more noticeable.
4. The modification is covered by complete unit …
=> fix supported model list in ascend graph mode

lmdeploy/pytorch/engine/model_agent.py, lmdeploy/vl/model/llava_hf.py
Only show log if exitcode > 0.
=> Better tp exit log.

src/turbomind/models/llama/LlamaDecoderLayerWeight.cc
Fix https://github.com/InternLM/lmdeploy/issues/2689
=> miss to read moe_ffn weights from converted tm model

docs/en/supported_models/supported_models.md, docs/zh_cn/supported_models/supported_models.md
fix document: llama3.2 multimodal vision 8B(×) -> 11B(√) 
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported 
4. versions of downstream projects.
5. The documentation has been modified accordingly, like docstring or example tutorials.
=> Fix llama3.2 VL vision in "Supported Modals" documents

lmdeploy/pytorch/backends/dlinfer/rotary_embedding.py
support Dynamic NTK scaling and llama3 rotary embedding is supported in ascend graph mode
ascend rotary_embedding …
=> feat: support dynamic/llama3 rotary embedding in ascend graph mode

lmdeploy/pytorch/backends/dlinfer/linear.py, lmdeploy/pytorch/backends/dlinfer/op_backend.py, lmdeploy/pytorch/kernels/dlinfer/__init__.py, lmdeploy/pytorch/kernels/dlinfer/linear.py
This PR add linear op on dlinfer.
Add linear op on dlinfer.
2. The modification …
=> add linear op on dlinfer platform

lmdeploy/pytorch/engine/model_agent.py
=> fix tp exit code for pytorch engine

README.md, README_ja.md, README_zh-CN.md, docs/en/supported_models/supported_models.md, docs/zh_cn/supported_models/supported_models.md, lmdeploy/model.py, lmdeploy/vl/model/internvl.py, tests/test_lmdeploy/test_model.py
support [AI4Chem/ChemVLM-26B](https://huggingface.co/AI4Chem/ChemVLM-26B)  
3. If the modification has a dependency on downstream projects of a newer version, this PR should …
=> Support chemvlm

lmdeploy/pytorch/backends/dlinfer/ascend/graph_runner.py
=> feat: support multi cards in ascend graph mode

docs/en/llm/api_server_tools.md, docs/zh_cn/llm/api_server_tools.md, lmdeploy/model.py, lmdeploy/serve/async_engine.py, lmdeploy/serve/openai/api_server.py, tests/test_lmdeploy/test_model.py
https://github.com/InternLM/lmdeploy/issues/2610 的后续，支持了Qwen2.5的fuctioncall，参考了 https://github.com/InternLM/lmdeploy/pull/2147 和Qwen2.5的chatTemplate [tokenizer_config.json](https://www.modelscope.cn/models/Qwen/Qwen2.5-14B-Instruct/file/view/master?fileName=tokenizer_config.json&status=1)
modified:   lmdeploy/model.py
modified:   lmdeploy/serve/async_engine.py
modified:   lmdeploy/serve/openai/api_server.py
基于lmdeployv0.6.2.post1
```
lmdeploy serve api_server  Qwen2.5-14B-Instruct-AWQ --tp 2
```
不携带tools参数
``` python
from …
```
=> feature: support qwen2.5 fuction_call

docs/en/supported_models/supported_models.md, docs/zh_cn/supported_models/supported_models.md, lmdeploy/pytorch/models/minicpmv26.py, lmdeploy/pytorch/models/module_map.py, lmdeploy/pytorch/supported_models.py
support minicpm-v_2_6 model for pytorch engine.
- add minicpm-v_2_6 model file and map.
- update related readme file.
=> [Feature] support minicpm-v_2_6 for pytorch engine.

lmdeploy/pytorch/backends/dlinfer/ascend/op_backend.py
Simplified pre-process during decoding phase on ascend.
3. If the modification …
=> Optimize update_step_ctx on Ascend

requirements/runtime_ascend.txt
After testing, some of the required interfaces for `serve` and `chat` are implemented in the `dlinfer-ascend` 0.1.2 version. To ensure that users can smoothly use lmdeploy on Ascend, a version restriction has been added. 
Add version restrictions in `runtime_ascend.txt`
Thank you for your approval!!!
=> Add version restrictions in runtime_ascend.txt to ensure functionality

lmdeploy/pytorch/kernels/cuda/flashattention.py, lmdeploy/pytorch/kernels/cuda/pagedattention.py, lmdeploy/pytorch/models/gemma.py
**NOTE**
There is still another place that is not aligned with gemma2, but I don't think that is important.
Gemma2 implementation of RMS Norm:
```
class DefaultRMSNormImpl(RMSNormImpl):
"""RMS norm implementation api."""
def __init__(self, hidden_size: int, eps: float = 1e-6):
self.hidden_size = hidden_size
self.eps = eps
def forward(self,
x: torch.Tensor,
weight: torch.Tensor,
residual: torch.Tensor = None):
"""forward."""
input_dtype = x.dtype
if residual is not None:
x = x + residual
residual = x
x = x.to(torch.float32)
variance = x.pow(2).mean(-1, keepdim=True)
x = x * torch.rsqrt(variance + self.eps)
x = (weight.float() * x).to(input_dtype)
if residual is None:
return x
return x, residual
```
Llama does x.to(float16) * w whilst Gemma is (x * w).to(float16)
See …
=> Fix gemma2 accuracy through the correct softcapping logic

lmdeploy/pytorch/engine/cache_engine.py, lmdeploy/pytorch/engine/engine.py, lmdeploy/pytorch/engine/engine_instance.py, lmdeploy/pytorch/engine/model_agent.py
=> better kv allocate

benchmark/profile_throughput.py, lmdeploy/pytorch/backends/cuda/attention.py, lmdeploy/pytorch/engine/engine.py, lmdeploy/pytorch/engine/logits_process.py, lmdeploy/pytorch/engine/model_agent.py, lmdeploy/pytorch/kernels/cuda/activation.py, lmdeploy/pytorch/kernels/cuda/apply_rotary_pos_emb.py, lmdeploy/pytorch/kernels/cuda/fill_kv_cache.py, lmdeploy/pytorch/models/utils/cudagraph.py, tests/pytorch/engine/test_logits_process.py
=> profile throughput without new threads

lmdeploy/pytorch/backends/cuda/awq_modules.py, lmdeploy/pytorch/backends/cuda/op_backend.py
=> fix the logic to verify whether AutoAWQ has been successfully installed

lmdeploy/pytorch/backends/dlinfer/ascend/graph_runner.py
https://github.com/InternLM/lmdeploy/pull/2814 changed the kv cache layout on ascend graph, we revert it to nd format in this PR
convert kv cache to nd format in ascend graph mode
2. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the …
=> [ascend] convert kv cache to nd format in ascend graph mode

lmdeploy/serve/async_engine.py
I've noticed that several args types in the docstring don't match the types in type hints.
Replace `List[Dict]` with `List[List[Dict]]]`.
=> Fix args type in docstring

lmdeploy/turbomind/deploy/module.py, lmdeploy/turbomind/deploy/target_model/base.py
=> replicate kv for some models when tp is divisble by kv_head_num

benchmark/profile_throughput.py
Resolve #2927 
Set concurrency to num of requests when the later is smaller.
=> fix: Incorrect stats size during inference of throughput benchmark when concurrency > num_prompts

lmdeploy/pytorch/models/internlm2.py, lmdeploy/pytorch/models/internvl.py, lmdeploy/pytorch/models/patch.py, requirements/runtime_ascend.txt, requirements/runtime_cuda.txt
fix lora name and rearange lora of wqkv for internlm2
```
"target_modules": [
"attention.wo",
"attention.wqkv",
"feed_forward.w1",
"feed_forward.w3",
"feed_forward.w2"
]
```
3. If the modification has a dependency on downstream …
=> fix lora name and rearange wqkv for internlm2

lmdeploy/pytorch/backends/dlinfer/flash_attention.py, lmdeploy/pytorch/backends/dlinfer/op_backend.py, lmdeploy/pytorch/kernels/dlinfer/__init__.py, lmdeploy/pytorch/kernels/dlinfer/flash_attention.py
add DlinferFlashAttention after vl refactor.
=> [dlinfer] feat: add DlinferFlashAttention to support qwen vl.

lmdeploy/archs.py, lmdeploy/lite/apis/calibrate.py, lmdeploy/vl/model/builder.py, lmdeploy/vl/model/cogvlm.py, lmdeploy/vl/model/glm_4v.py, lmdeploy/vl/model/mllama.py, lmdeploy/vl/model/phi3_vision.py, lmdeploy/vl/model/qwen2.py
=> [side-effect] bring back quantization of qwen2-vl, glm4v and etc.

.github/workflows/benchmark.yml, .github/workflows/daily_ete_test.yml, .github/workflows/daily_ete_test_v100.yml, lmdeploy/pytorch/backends/cuda/awq_modules.py, lmdeploy/pytorch/backends/cuda/op_backend.py, lmdeploy/pytorch/check_env/model.py, lmdeploy/pytorch/kernels/cuda/awq_kernels.py
autoawq_kernel is not required.
Note that this kernel is still slower than float16 MMA when M is larger than 128.
=> Optimize awq kernel in pytorch engine

lmdeploy/model.py, lmdeploy/serve/openai/api_server.py
=> add tool role in BaseChatTemplate as tool response in messages

docs/en/quantization/w8a8.md, docs/zh_cn/quantization/w8a8.md, lmdeploy/cli/lite.py, lmdeploy/cli/utils.py, lmdeploy/lite/apis/smooth_quant.py, lmdeploy/pytorch/backends/cuda/norm.py, lmdeploy/pytorch/backends/cuda/qmodules.py, lmdeploy/pytorch/backends/norm.py, lmdeploy/pytorch/backends/qmodules.py, lmdeploy/pytorch/engine/engine.py, lmdeploy/pytorch/kernels/cuda/w8a8_triton_kernels.py, lmdeploy/pytorch/models/baichuan.py, lmdeploy/pytorch/models/chatglm2.py, lmdeploy/pytorch/models/cogvlm.py, lmdeploy/pytorch/models/deepseek.py, lmdeploy/pytorch/models/gemma.py, lmdeploy/pytorch/models/internlm2.py, lmdeploy/pytorch/models/internlm2_ve.py, lmdeploy/pytorch/models/minicpmv26.py, lmdeploy/pytorch/models/mistral.py, lmdeploy/pytorch/models/phi3.py, lmdeploy/pytorch/models/q_modules.py, lmdeploy/pytorch/models/qwen.py, lmdeploy/pytorch/models/qwen2.py, lmdeploy/pytorch/models/qwen2_moe.py, lmdeploy/pytorch/models/qwen2_vl.py, lmdeploy/pytorch/nn/linear.py, lmdeploy/pytorch/nn/norm.py, tests/pytorch/kernel/test_fused_moe.py
Support fp8 w8a8 for pt backend
Support fp8 w8a8 for pt backend
None
```
lmdeploy lite smooth_quant \
meta-llama/Meta-Llama-3-8B-Instruct \
--work-dir Meta-Llama-3-8B-Instruct-fp8-w8a8 \
--quant-dtype fp8
```
```
lmdeploy  chat Meta-Llama-3-8B-Instruct-fp8-w8a8 --backend pytorch
```
=> Support fp8 w8a8 for pt backend

lmdeploy/vl/model/xcomposer2.py
fix error when using transformers >= 4.46.0
https://github.com/huggingface/transformers/blob/v4.46.0/src/transformers/models/clip/modeling_clip.py#L244-L245
=> fix xcomposer2 when transformers is upgraded greater than 4.46 

lmdeploy/pytorch/kernels/dlinfer/apply_rotary_pos_emb.py
This pr removes useless reshape for rope kernel. Reshape for cos and sin is device-specific, and should be move into dlinfer, not lmdeploy
=> [dlinfer]rope refine

lmdeploy/serve/async_engine.py, lmdeploy/serve/utils.py, tests/test_lmdeploy/test_auto_backend.py
OC test with the following config failed
```python
from copy import deepcopy
from mmengine.config import read_base
with read_base():
from opencompass.configs.datasets.ARC_c.ARC_c_few_shot_ppl import \
ARC_c_datasets  # noqa: F401, E501
from opencompass.configs.models.hf_internlm.lmdeploy_internlm2_5_7b import \
models as lmdeploy_internlm2_5_7b  # noqa: F401, E501
turbomind_internlm2_5_7b = deepcopy(*lmdeploy_internlm2_5_7b)
for model in [v for k, v in locals().items() if k.endswith('_4bits')]:
model['engine_config']['model_format'] = 'awq'
model['abbr'] = model['abbr'] + '_4bits'
model['path'] = model['path'] + '-inner-4bits'
for model in [v for k, v in locals().items() if '_batch1' in k]:
model['abbr'] = model['abbr'] + '_batch1'
model['engine_config']['max_batch_size'] = 1 …
```
=> [hotfix] Fix get_ppl

lmdeploy/model.py, lmdeploy/pytorch/configurations/default.py, lmdeploy/pytorch/models/internlm3.py, lmdeploy/pytorch/models/module_map.py, lmdeploy/pytorch/supported_models.py
support internlm/internlm3-8b-instruct
=> support internlm3 on pt

lmdeploy/serve/openai/api_server.py
Due to historical reason, `finish_reason` is expected to be set to 'stop' when a session ends
=> fix error in interactive api

lmdeploy/pytorch/paging/block_manager/window_block_manager.py
=> fix sliding window mgr

lmdeploy/model.py, tests/test_lmdeploy/test_model.py
=> Add deepseek-r1 chat template

lmdeploy/pytorch/engine/logits_process.py
Latest transformers has removed logitswarper
=> remove logitswarper

tests/test_lmdeploy/test_model.py
For deepseek-r1 model, the chat template add "<think>\n" after "<|Assistant|>"
```
AssertionError: assert '<｜begin▁of▁s...nt｜><think>\n' == '<｜begin▁of▁s...<｜Assistant｜>'
```
Since LMDeploy allows users to add assistant content in prompt message, I think we'd better not change "deepseek-r1" in model.py but modifying the UT.
=> Fix UT of deepseek chat template

lmdeploy/pytorch/models/internvl.py, lmdeploy/vl/model/internvl.py
Model generate padded image token could lead to error after eviction.
Note that a better solution is to set a pad token that would never generated.
=> Fix internvl2.5 error after eviction

lmdeploy/pytorch/engine/engine.py, lmdeploy/serve/gradio/vl.py
Use pipeline api and remove interactive chat to support vl models like qwen2-vl
Currently with pytoch backend, it seems that the generator cannot be interrupted when sending a stop request. @grimoire 
```python
import asyncio
from lmdeploy import pipeline, PytorchEngineConfig
pipe = pipeline('/mnt/141/vicuna-7b-v1.5/', backend_config=PytorchEngineConfig())
event = asyncio.Event()
messages = '写一篇高考作文'
session_id = 0
async def inference():
step = 0
async for out in pipe.generate(messages=messages, session_id=session_id):
print(step, out)
step += 1
if (step == 5):
event.set()
print('inference done')
async def stop():
await event.wait()
await pipe.stop_session(session_id=session_id)
async def main():
await asyncio.gather(inference(), stop())
if __name__ == '__main__':
asyncio.run(main())
```
=> [fix] fix vl gradio, use pipeline api and remove interactive chat

lmdeploy/serve/async_engine.py
eos_token_id in generation_config.py may be less than defined in model.py like old llama3 model
https://huggingface.co/meta-llama/Meta-Llama-3-70B-Instruct/discussions/12
=> fix the issue that stop_token may be less than defined in model.py

requirements/runtime_ascend.txt, requirements/runtime_camb.txt, requirements/runtime_cuda.txt, requirements/runtime_maca.txt, requirements/test.txt
1. Update `peft` dependency version
2. Update `pynvml` to `nvidia-ml-py` because the former one is deprecated and not compatible with `vllm>=0.7.0`, see [pypi](https://pypi.org/project/pynvml/)
See above
None
None
=> Update runtime package dependencies

src/turbomind/layers/sampling_layers/LogitsProcessorLayer.cc, src/turbomind/layers/sampling_layers/LogitsProcessorLayer.h
=> fix min length penalty

lmdeploy/turbomind/turbomind.py
The current implementation of turbomind only supports embedding inputs on the CPU. When embedding inputs are too large, the CPU can become a bottleneck. This PR aims to enable support for embedding inputs on the GPU, thereby alleviating the CPU bottleneck.
=> Make turbomind support embedding inputs on GPU

autotest/tools/pipeline/llm_case.py, autotest/tools/pipeline/mllm_case.py, autotest/tools/pipeline/test_pipeline_chat_turbomind_llm.py, autotest/tools/pipeline/test_pipeline_chat_turbomind_mllm.py, autotest/tools/restful/test_restful_chat_hf_turbomind_llm.py, autotest/tools/restful/test_restful_chat_hf_turbomind_mllm.py, autotest/utils/config_utils.py
1. add testcase for diff communicator backend. currently cover pipeline and restful testcases in turbomind backend. 
will add --communicator native for chat cli in future pr.
2. remove pytorch models coverage in turbomind testcase for testing backend auto switching. 
will add backend auto switching in future pr.
=> [ci] add testcase for native communicator

lmdeploy/pytorch/backends/attention.py, lmdeploy/pytorch/backends/cuda/attention.py, lmdeploy/pytorch/backends/cuda/op_backend.py, lmdeploy/pytorch/config.py, lmdeploy/pytorch/configurations/deepseek_v2.py, lmdeploy/pytorch/configurations/utils.py, lmdeploy/pytorch/engine/engine.py, lmdeploy/pytorch/engine/executor/base.py, lmdeploy/pytorch/kernels/cuda/__init__.py, lmdeploy/pytorch/kernels/cuda/flash_mla.py, lmdeploy/pytorch/kernels/flash_mla.py, lmdeploy/pytorch/model_inputs.py, lmdeploy/pytorch/models/deepseek_v2.py, lmdeploy/pytorch/models/utils/cudagraph.py, lmdeploy/pytorch/nn/attention.py
Benchmark serving result with `python benchmark/profile_restful_api.py --backend lmdeploy --base-url http://0.0.0.0:23333 --dataset-name random --random-input-len 2048 --random-output-len 2048 --dataset-path ShareGPT_V3_unfiltered_cleaned_split.json --sharegpt-output-len 2048`
```
============ Serving Benchmark Result ============
Backend:                                 lmdeploy  
Traffic request rate:                    inf       
Successful requests:                     1000      
Benchmark duration (s):                  188.84    
Total input tokens:                      1025866   
Total generated tokens:                  1027062   
Total generated tokens (retokenized):    1028569   
Request throughput (req/s):              5.30      
Input token throughput (tok/s):          5432.42 …
```
=> Add flash mla

lmdeploy/pytorch/models/qwen2_5_vl.py
#3237 NPU下Qwen2.5-VL报错类型不匹配。
vis_ratary_embedding转为bf16
=> fix qwen2.5 pytorch engine dtype error on NPU

lmdeploy/messages.py, lmdeploy/serve/async_engine.py, tests/test_lmdeploy/test_messages.py
For some models such as deepseek-v3, which doesn't have `generation_config.json` file, LMDeploy failed to update the tokenizer's eos_token_id into the stop_word list.
=> [Fix] failed to update the tokenizer's eos_token_id into stop_word list

docker/Dockerfile
Add RDMA-related dependencies into the docker file.
Built on the local machine and tested on A100 GPU with llama3, functionality looks good.
=> add rdma dependencies into docker file

lmdeploy/pytorch/models/deepseek_v2.py
dsv2:
```python
if self.top_k > 1 and self.norm_topk_prob:
denominator = topk_weight.sum(dim=-1, keepdim=True) + 1e-20
topk_weight = topk_weight / denominator
else:
topk_weight = topk_weight * self.routed_scaling_factor
```
dsv3
```python
if self.top_k > 1 and self.norm_topk_prob:
denominator = topk_weight.sum(dim=-1, keepdim=True) + 1e-20
topk_weight = topk_weight / denominator
topk_weight = topk_weight * self.routed_scaling_factor # must multiply the scaling factor
```
=> fix dsv3 gate scaling

lmdeploy/cli/lite.py, lmdeploy/lite/apis/auto_awq.py, lmdeploy/lite/apis/smooth_quant.py, lmdeploy/pytorch/check_env/__init__.py, lmdeploy/pytorch/check_env/deeplink.py, lmdeploy/pytorch/kernels/cuda/__init__.py, lmdeploy/pytorch/kernels/cuda/w8a8_triton_kernels.py, lmdeploy/pytorch/kernels/default/__init__.py, lmdeploy/pytorch/kernels/default/w8a8_kernels.py, lmdeploy/pytorch/kernels/dispatcher.py, lmdeploy/pytorch/kernels/dlinfer/__init__.py, lmdeploy/pytorch/models/q_modules.py, lmdeploy/serve/vl_async_engine.py, lmdeploy/utils.py
1. support dlinfer smooth_quant
2. suppprt ascend w8a8 graph_mode
3. In order to share the per_channel_quant kernel with cuda, move the  kernel from cuda folder to default folder
4. In order to find the dlinfer folder when load_func, modify FunctionDispatcher
5. fix dynamo error in QTensor
=> support ascend w8a8 graph_mode

lmdeploy/pytorch/backends/cuda/moe.py, lmdeploy/pytorch/backends/cuda/token_dispatcher.py, lmdeploy/pytorch/backends/default/token_dispatcher.py, lmdeploy/pytorch/backends/token_dispatcher.py
=> support all2all ep

lmdeploy/vl/model/deepseek.py, lmdeploy/vl/model/qwen2.py
Fix issue #3285 
It could be confirmed that `image_token_id` of `Qwen2-VL` and `DeepSeek-VL` is not same as `pad_token_id`, so this PR add codes reloading `image_token_id` in `build_preprocessor()` of them.
For modification of `Qwen2-VL`: https://github.com/huggingface/transformers/blob/fb8e6c50e4a3a4bb1011e286d9bd26d79cd6334d/src/transformers/models/qwen2_vl/processing_qwen2_vl.py#L72-L75
For modification of `DeepSeek-VL`:
https://github.com/deepseek-ai/DeepSeek-VL/blob/681bffb4519856ad27cc17531aacde31ddf6f1a7/deepseek_vl/models/processing_vlm.py#L99
=> [Fix] fix `image_token_id` error of qwen2-vl and deepseek

lmdeploy/pytorch/models/internvl.py
=> fix mllm testcase fail

lmdeploy/model.py, tests/test_lmdeploy/test_model.py
https://github.com/InternLM/lmdeploy/issues/3422
[Qwen2.5 chat template](https://huggingface.co/Qwen/Qwen2.5-7B-Instruct/blob/main/tokenizer_config.json) system prompt is different from that of [Qwen2.5-VL chat template](https://huggingface.co/Qwen/Qwen2.5-VL-7B-Instruct/blob/main/chat_template.json) .
Comparisons of system messages in the previous implementation.
- Prompt A: `You are a helpful assistant.`
- Prompt B: `You are Qwen, created by Alibaba Cloud. You are a helpful assistant.`
|            | Transformers | LMDeploy |
|:----------:|:------------:|:--------:|
| Qwen2.5-VL |       A      |     B    |
|   Qwen2.5  |       B      |     B    |
|  Qwen2-VL  |       A      |     A    |
|    Qwen2   |       A      |     A    |
=> fix qwen2.5-vl chat template

lmdeploy/pytorch/models/deepseek_vl2.py
https://github.com/InternLM/lmdeploy/issues/3409
The [check condition](https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/pytorch/models/utils/cudagraph.py#L63), which involves `config` is introduced in FlashMLA PR. Previous DeepSeek-VL2 implementations forgot to define the class `config` attribute, which leads to errors.
Tested with latest main after fix:
=> fix dsvl2 no attr config error

requirements/runtime_ascend.txt, requirements/runtime_camb.txt, requirements/runtime_cuda.txt, requirements/runtime_maca.txt, requirements/serve.txt
To fix "import error"
```
ModuleNotFoundError: No module named 'partial_json_parser'
```
=> move partial_json_parser from ’serve.txt‘ to ‘runtime.txt‘

lmdeploy/serve/openai/api_server.py, lmdeploy/serve/openai/protocol.py
Support `min_p` param in openai completions_v1. I've tested these changes and it gets passed through properly now.
=> Support min_p in openai completions_v1

lmdeploy/pytorch/engine/model_agent.py
fix recompile on different rank. This is the root cause of #3354 and https://github.com/DeepLink-org/dlinfer/issues/201
(add `inference_mode` on `async def _async_step_background` as a decorator does not work)
=> [ascend] fix recompile on different rank

lmdeploy/pytorch/engine/executor/__init__.py, lmdeploy/pytorch/engine/executor/ray_executor.py, lmdeploy/pytorch/envs.py
> [!NOTE]  
> This PR is used to profile GPU with ray. It has nothing to do with tp=1.
```bash
LMDEPLOY_RAY_NSYS_ENABLE=1 \
LMDEPLOY_RAY_NSYS_OUT_PREFIX=/path/to/save/prefix_ \
python your_script.py
```
If you want to use non-default nsys, please update `PATH` environment before `ray start`
```bash
PATH=/path/to/new/nsys:$PATH ray start --head
```
=> ray nsys profile support

lmdeploy/cli/serve.py, lmdeploy/cli/utils.py, lmdeploy/serve/openai/api_server.py, lmdeploy/serve/proxy/proxy.py
Allow api server to be terminated through a request from a client.
None
1. start server with `--allow-terminate-by-client`
```
lmdeploy serve api_server meta-llama/Meta-Llama-3-8B-Instruct  --allow-terminate-by-client
```
2. terminate with curl
```
curl http://0.0.0.0:23333/terminate
```
4. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness.
5. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream projects.
6. The documentation has been modified accordingly, like docstring or example tutorials.
=> allow api server terminated through requests from clients

lmdeploy/pytorch/models/deepseek_v2.py, lmdeploy/pytorch/models/internlm3.py, lmdeploy/pytorch/models/qwen3.py, lmdeploy/pytorch/models/qwen3_moe.py, lmdeploy/pytorch/nn/linear.py, lmdeploy/pytorch/nn/moe.py
Rename blocked fp8 `scale` => `weight_scale_inv` in `nn.linear` and `nn.moe`, then we don't need to deal with scale suffix for each blocked-fp8 model.
=> update blockedfp8 scale name

lmdeploy/pytorch/engine/engine.py, lmdeploy/serve/async_engine.py, lmdeploy/serve/openai/api_server.py
=> start engine loop on server startup event

lmdeploy/pytorch/engine/engine.py, lmdeploy/pytorch/messages.py
=> fix stopwords kv cache

lmdeploy/pytorch/engine/cache_engine.py, lmdeploy/pytorch/engine/engine.py, lmdeploy/pytorch/messages.py, lmdeploy/pytorch/model_inputs.py, lmdeploy/pytorch/paging/scheduler.py
1. add `collect_migration_done` before `inputs_maker.prefetch_next_inputs()` because of dummy run.
2. bugfix when preemption in decode engine
3. bypass 0-shape vcache tensor migration.
=> [bug fix] fix PD Disaggregation in DSV3

lmdeploy/pytorch/engine/model_agent.py, lmdeploy/serve/openai/protocol.py
Since the serialization and deserialization of tensors need to appear in pairs to avoid memory leak, we need to update the related api to support settings of tp=1 and tp > 1. Under such a model configuration, the data format should be [serialize_tp0_data, serialize_tp1_data, ...]
related demo https://gitee.pjlab.org.cn/L1/_source/L1/chenxin/lmdeploy-rl-demo/-/blob/heads%2Fmain/demo_dp1_proxy.py
=> support update params with dp=1 for pytorch engine

lmdeploy/cli/serve.py, lmdeploy/serve/openai/api_server.py
For QwQ and Qwen3 models,  `tool-call-parser` and `reasoning-parser` can be activated simultaneously.
Related issue: [3431](https://github.com/InternLM/lmdeploy/issues/3431)
=> Unclock mutual exclusivity of argument:  `tool-call-parser` and `reasoning-parser`

lmdeploy/pytorch/engine/executor/ray_executor.py, lmdeploy/pytorch/envs.py, lmdeploy/pytorch/models/deepseek_v2.py
=> read distributed envs

lmdeploy/pytorch/backends/cuda/blockedf8_modules.py, lmdeploy/pytorch/backends/cuda/warmup_manager.py, lmdeploy/pytorch/kernels/cuda/blocked_gemm_fp8.py
latest deepgemm support nvrtc, enable with `DG_JIT_USE_NVRTC=1`
latest deepgemm requires `cuda-bindings`.
optimize warmup.
=> update deepgemm version

lmdeploy/pytorch/models/qwen2.py
Resolve the issue where Qwen2 does not adhere to the use_sliding_window setting specified in the configuration file.
=> fix bug in qwen2

lmdeploy/pytorch/engine/executor/ray_executor.py, lmdeploy/utils.py
Fix not passing env `LMDEPLOY_LOG_FILE` to ray worker.
Ray runtime env setting reference: https://docs.ray.io/en/latest/ray-core/handling-dependencies.html#environment-dependencies
2. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the …
=> Fix log file env in ray worker

lmdeploy/pytorch/backends/dlinfer/ascend/op_backend.py, lmdeploy/pytorch/engine/executor/ray_executor.py
Since Ascend 310P device need to convert linear weight from ND to NZ in graph mode. However,  for VL model, we only compile language part in graph mode and leave vision part in eager mode. So we need skip converting weight in vision part, dlinfer.framework.lmdeploy_ext has a patch for the logic that skips vision part, we need to import it at initializing time to make Ray distributed backend for VL model properly.
=> [ascend]import patch at initiazing time

lmdeploy/pytorch/backends/dlinfer/ascend/op_backend.py, lmdeploy/pytorch/backends/dlinfer/ascend/utils.py, lmdeploy/pytorch/backends/dlinfer/linear.py
This PR usesa  custom Transdata Python kernel instead of compiling TransdataOperation for Ascend 310P devices.
Copy from [vllm-ascend ](https://github.com/vllm-project/vllm-ascend/pull/1333/commits/420e794c35fe887db2be81cf9db0461f5b71da0b)
=> [ascend]use custon transdata in python kernel

lmdeploy/pytorch/engine/engine.py, lmdeploy/pytorch/engine/request.py, lmdeploy/pytorch/messages.py, lmdeploy/serve/async_engine.py
In dealing with high-frequency requests, there might be two types of errors encountered if the connection disconnected quickly
a) http request disconnected, but the engine is still process the request
b) the engine might crash (asyncio event loop closed)
test-script
```python
import time
import aiohttp
from openai import OpenAI
from threading import Thread
import asyncio
async def work():
node_url = 'http://0.0.0.0:23333'
endpoint = '/v1/completions'
request = dict(model='Qwen/Qwen2.5-7B', prompt='tell me a joke ' * 50, max_tokens=12768, stream=True)
try:
async with aiohttp.ClientSession() as session:
async with session.post(node_url + endpoint, json=request) as response:
async for _ in response.content:
pass
except Exception as e:
print(e)
async def main():
loop = …
```
=> fix pt engine stop & cancel

.github/workflows/pr_ete_test.yml, lmdeploy/pytorch/engine/executor/ray_executor.py
tensor of bfloat16 type cannot be converted to numpy
```
python -c 'import torch;torch.rand(10, dtype=torch.bfloat16).numpy()'
File "<string>", line 1, in <module>
TypeError: Got unsupported ScalarType BFloat16
```
2. The modification is covered by …
=> Fix convert bf16 to numpy

lmdeploy/pytorch/models/qwen3.py, lmdeploy/pytorch/nn/norm.py
解决qwen3_w8a8_int8模型推理报错的问题。
当使用qwen3模型的w8a8推理时，需要避免对q_norm和k_norm进行量化。
2. The …
=> [Fix]: Avoid quantize qk norm for qwen3 dense models

lmdeploy/pytorch/kernels/cuda/flashattention.py
kernel meta retrieval in attention module does not wrok on SM7X GPUs
fix the bug
No
3. If the modification has …
=> [Fix]: kernel meta retrieval for SM7X does not work

lmdeploy/cli/serve.py
When serving with CLI, arguments: max_prefill_token_num and num_tokens_per_iter weren't being set.
Added max_prefill_token_num and num_tokens_per_iter as arguments for TurbomindEngineConfig in cli api_serve after being parsed.
Taking advantage of "Dynamic SplitFuse"-like behavior using CLI.
=> fix: turbomind backend config in cli serve

lmdeploy/serve/proxy/proxy.py
The current implementation attempts to call `shelf_prefill_session` on the PD (Prefill-Decode) connection pool regardless of whether dummy prefill mode is enabled. However, when `dummy_prefill` is set to True, there is no actual prefill session migration happening, and attempting to shelf a non-existent prefill session can lead to unnecessary operations or potential errors.
```
File "/nvme2/share/root/src/LMDeploy/lmdeploy/serve/proxy/proxy.py", line 643, in chat_completions_v1
node_manager.pd_connection_pool.shelf_prefill_session((p_url, d_url), prefill_info['id'])
KeyError: 'id'
```
Added conditional guards around `node_manager.pd_connection_pool.shelf_prefill_session()` calls in two API endpoints:
- `/v1/chat/completions endpoint` [chat_completions_v1]:
Added `if not …
=> fix: add dummy_prefill guard for PD connection operations

docs/en/inference/load_hf.md, docs/zh_cn/inference/load_hf.md, lmdeploy/cli/cli.py, lmdeploy/serve/turbomind/__init__.py
Removing the converter and Triton Server Python backend (#3462) left behind some remaining files and code blocks
=> remove 'lmdeploy convert' from CLI

lmdeploy/pytorch/backends/cuda/blockedf8_modules.py, lmdeploy/pytorch/envs.py, lmdeploy/pytorch/kernels/cuda/blocked_gemm_fp8.py, lmdeploy/pytorch/third_party/__init__.py, lmdeploy/pytorch/third_party/deep_gemm/__init__.py
DeepGemm update it's python api since PR112
This PR add third-party wrap of deep-gemm. Support both 1.0 and 2.0.
Since deepgemm2.0 used cpp wrapped compile tools, logger can not be patched in it. If compile log is required, `DG_JIT_PRINT_COMPILER_COMMAND=1` or `DG_JIT_DEBUG=1` can be used.
=> support deepgemm new api

lmdeploy/pytorch/nn/rotary_embedding.py
Config may have `partial_rotary_factor` attribute without `rope_scaling` attributes.
e.g.
https://huggingface.co/zai-org/GLM-4-9B-0414/blob/main/config.json
https://huggingface.co/zai-org/GLM-4.5-Air/blob/main/config.json
Previous condition checks will miss `partial_rotary_factor` in this case, which leads to incorrect rope calculations.
This PR is the pre-requisite of GLM4-0414, GLM-4.1V, GLM-4.5 (Air), etc
- https://github.com/InternLM/lmdeploy/pull/3846
=> fix partial rotary factor

lmdeploy/serve/async_engine.py, lmdeploy/serve/vl_async_engine.py
Use positional args instead of kwargs to resolve the TypeError issue:
```
TypeError: VLAsyncEngine.chat() missing 1 required positional argument: 'prompts'
```
Check `sess.history` before accessing it.
=> fix chatting with VLM model via CLI

lmdeploy/cli/serve.py, lmdeploy/cli/utils.py, lmdeploy/messages.py, lmdeploy/pytorch/config.py, lmdeploy/pytorch/engine/engine.py, lmdeploy/pytorch/engine/engine_instance.py, lmdeploy/pytorch/engine/executor/ray_executor.py, lmdeploy/pytorch/engine/logits_process.py, lmdeploy/pytorch/engine/model_agent.py, lmdeploy/pytorch/messages.py
=> support logprobs

docker/prepare_wheel.sh
Error in https://github.com/InternLM/lmdeploy/actions/runs/17065840339/job/48556288085
FlashMLA has a large refactor after
- https://github.com/deepseek-ai/FlashMLA/pull/76
CUDA12.4 build does not support 100a, therefore we switch to an older version before the above commit.
- https://github.com/deepseek-ai/FlashMLA/issues/79
=> fix flashmla build for cuda12.4

lmdeploy/pytorch/paging/block_trie.py
In scenarios with extreme memory pressure where all leaf nodes are evicted, leave_blocks becomes an empty array. This causes self.allocator.get_ref_count(leave_blocks)to throw an unhandled exception when processing eviction candidates. I think this is a corner case caused by GPU memory exhaustion.
GPU: H20
Command:
Simulate the situation of gpu  memory limitation
```
lmdeploy serve api_server ../qwen_06B --backend pytorch --max-batch-size 256 --enable-prefix-caching --cache-max-entry-count 0.005  
```
```
python …
```
=> fix bug: leaves empty

lmdeploy/pytorch/engine/mp_engine/base.py, lmdeploy/pytorch/engine/mp_engine/base_worker.py
metrics breaks in PyTorch MP Engine mode, since `get_schedule_metrics` doesn't have an RPC call registered.
=> fix pytorch metrics in mp engine

lmdeploy/serve/async_engine.py
#3821 removed `self.hf_tm_cfg` in AsyncEngine. It causes the following error when `get_ppl` is called
```
File "/opt/py3/lib/python3.10/site-packages/lmdeploy/serve/utils.py", line 115, in get_ppl
vocab_size = self.hf_tm_cfg.vocab_size
AttributeError: 'AsyncEngine' object has no attribute 'hf_tm_cfg'. 
```
=> fix side effect brought by #3821

lmdeploy/pytorch/engine/request.py
**question1**: The function actually returns a dictionary where each RequestType
maps to a list of Request objects. This change updates the type
hint to Dict[RequestType, List[Request]] for correctness and better
IDE/static type support.
**question2**: Previously, RequestManager.step accessed `reqs_by_type[req_type]` directly, 
and the check `if req_type not in reqs_by_type or len(reqs_by_type) == 0` 
was logically incorrect. This could cause the empty request queue to keep executing, wasting resources.
Please briefly …
=> style(types): fix return type annotation for get_all_requests

docs/en/get_started/ascend/get_started.md, docs/en/get_started/camb/get_started.md, docs/en/get_started/index.rst, docs/en/get_started/maca/get_started.md, docs/en/supported_models/supported_models.md, docs/zh_cn/get_started/ascend/get_started.md, docs/zh_cn/get_started/camb/get_started.md, docs/zh_cn/get_started/index.rst, docs/zh_cn/get_started/maca/get_started.md, docs/zh_cn/supported_models/supported_models.md
update readme for other platforms
=> Dlinfer readme

lmdeploy/serve/openai/api_server.py, lmdeploy/serve/openai/protocol.py
=> cherry pick PR-3708 to return token_id

lmdeploy/messages.py, lmdeploy/serve/async_engine.py, lmdeploy/serve/openai/api_server.py, lmdeploy/serve/openai/protocol.py
=> support returning stop_str in output
