- README.md
- README_zh-CN.md
- docs/en/serving.md
- docs/zh_cn/serving.md
> docs(serving.md): typo

- README.md
- README_zh-CN.md
> [Doc] update discord and wechat link

- README.md
- README_zh-CN.md
- docs/en/serving.md
- docs/zh_cn/serving.md
[bugfix] Fix some docs' bug in 'serving'
> [bugfix] Fix some docs' bug in 'serving'

- README.md
- README_zh-CN.md
> docs: fix typo

- lmdeploy/pytorch/chat.py
```
from .accel import LoadNoInit
from .utils import get_utils
```
may raise attempted relative import error
which will set _is_transformers_available = False
> [Fix] fix attempted_relative_import

- lmdeploy/serve/turbomind/deploy.py
> print info copy-paste error

- lmdeploy/lite/apis/kv_qparams.py
- lmdeploy/lite/utils/calib_dataloader.py
- requirements.txt
1. fixed get internlm model
2. fixed randint error in get_dataset
> [Fix] Fix bug for issues #141

- .github/workflows/docker.yml
- docker/Dockerfile
1. add building and pushing docker image github action yaml config
2. modify Dockerfile so as to build docker image correctly.
> Add github action for publishing docker image 

- lmdeploy/serve/turbomind/__init__.py
- lmdeploy/serve/turbomind/chatbot.py
* add __init__.py for turbomind
* add resume function
* fix the assignment for session.response
> remove slicing reponse and add resume api

- README.md
- docs/en/quantization.md
- docs/zh_cn/quantization.md
Translated the quantization.md
> [Docs] Translate the quantization.md

- .gitignore
- builder/manywheel/Dockerfile_2014
- builder/manywheel/README.md
- builder/manywheel/build_all_docker.sh
- builder/manywheel/build_all_wheel.sh
- builder/manywheel/build_docker.sh
- builder/manywheel/build_wheel.sh
- builder/manywheel/entrypoint_build.sh
- builder/manywheel/scripts/install_conda.sh
- builder/manywheel/scripts/install_cuda.sh
- builder/manywheel/scripts/install_openmpi.sh
- setup.py
- src/turbomind/python/CMakeLists.txt
- src/turbomind/triton_backend/CMakeLists.txt
add build scripts for docker and whl package.
> Add manylinux builder

- .github/workflows/pypi.yml
> Add pypi ci

- benchmark/profile_serving.py
- lmdeploy/serve/client.py
- lmdeploy/serve/turbomind/chatbot.py
In postprocessing, decoding all new generated  tokens is time-consuming every time when a new token is generated
Change it to incremental decoding mode, i.e., only decode the new generated token in each step
chatbot.py
If this PR introduces a new feature, it is better …
> Improve postprocessing in TIS serving by applying Incremental de-tokenizing

- lmdeploy/serve/client.py
- lmdeploy/serve/turbomind/chatbot.py
- lmdeploy/turbomind/chat.py
#190 
chatbot.py
2. The modification is covered by complete unit tests. If not, …
> Add non-stream inference api for chatbot

- lmdeploy/version.py
> bump version to v0.0.3

- README.md
- README_zh-CN.md
> [Docs] Update W4A16 News

- lmdeploy/serve/turbomind/chatbot.py
- lmdeploy/serve/turbomind/triton_models/postprocessing/config.pbtxt
PR https://github.com/InternLM/lmdeploy/pull/197 brought a side effect.
If user deploys any llama-like model other than InternLM,  there is no whitespace in chatting result
Rollback chatbot.py
If this PR introduces a new feature, it is better to list some use cases …
> Fix TIS client got-no-space-result side effect brought by PR #197

- README.md
- README_zh-CN.md
- benchmark/profile_generation.py
- docs/en/serving.md
- docs/en/w4a16.md
- docs/zh_cn/w4a16.md
Present how to deploy w4a16 LLM model
w4a16.md in both English and Chinese
2. …
> Check-in user guide for w4a16 LLM deployment

- lmdeploy/model.py
> Remove chat template

- lmdeploy/serve/gradio/app.py
- lmdeploy/turbomind/turbomind.py
> adjust app.py dependency

- requirements.txt
"calibrate.py" depends on "accelerate" but failed to add it to the requirement file
requirements.txt
1. Pre-commit or other linting tools are used to fix the …
> Add 'accelerate' to requirement list

- lmdeploy/serve/turbomind/deploy.py
Verified on
and it won't break
> [Feature] Support TP for W4A16

- README.md
- README_zh-CN.md
- docs/en/kv_int8.md
- docs/zh_cn/kv_int8.md
> docs(quantization): update description

- .github/workflows/docker.yml
- docker/Dockerfile
Fix docker build CI
1. fix building image error: https://github.com/NVIDIA/cuda-repo-management/issues/10
2. update building docker image workflow
3. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness.
4. If the modification has a dependency on downstream projects of a newer version, this …
> Update workflow for building docker image

- README.md
- docs/zh_cn/faq.md
- lmdeploy/lite/apis/auto_awq.py
- lmdeploy/lite/apis/calibrate.py
- lmdeploy/lite/quantization/activation/observer.py
- lmdeploy/lite/quantization/awq.py
- lmdeploy/lite/quantization/calibration.py
> [Fix] Fix llama2 70b & qwen quantization error

- .gitignore
- benchmark/benchmark_decode.py
- lmdeploy/pytorch/decode.py
- lmdeploy/pytorch/infer_dist.py
- lmdeploy/pytorch/model.py
- tests/pytorch/test_decode.py
This is based on refactored `init_model` in #178. 
Support decode ( compute probabilities of input prompt ) with data parallel in pytorch module.
New feature. 
No. 
> [Feature] Support decode with DP in pytorch

- README.md
- README_zh-CN.md
- docs/en/kv_int8.md
- docs/zh_cn/kv_int8.md
- lmdeploy/lite/apis/kv_qparams.py
fix kv_int8 doc error  #314 
kv_int8 和 w_int4 的文档，一次性给完整的流程和方法。
> fix(kvint8): update doc

- lmdeploy/__init__.py
Fix https://github.com/InternLM/lmdeploy/issues/311
> Fix turbomind import error on windows

- docs/en/restful_api.md
- docs/zh_cn/restful_api.md
- lmdeploy/model.py
- lmdeploy/serve/async_engine.py
- lmdeploy/serve/turbomind/chatbot.py
- lmdeploy/serve/turbomind/triton_models/postprocessing/1/model.py
- lmdeploy/turbomind/chat.py
- lmdeploy/turbomind/tokenizer.py
Tested OK with InternLM, Llama2, Qwen, Puyu, Vicuna
> Decode generated token_ids incrementally

- lmdeploy/pytorch_poc/engine/engine.py
- lmdeploy/pytorch_poc/kernels/context_pagedattention.py
- lmdeploy/pytorch_poc/patch/llama.py
1. Explicitly add batch size dim for inputs and intermediate features
2. Explicitly set `use_origin` flag to switch between continuous batching and original
3. use float16 by default and accelerate init by skipping initializing parameters on cpu
4. add `model.eval()`
5. support llama for transformers >= 4.32
Does the modification introduce changes that break the …
> [Improve] Use 4d input in pytorch poc

- lmdeploy/model.py
> [Fix] update puyu model

- lmdeploy/version.py
> bump version to v0.0.8

- builder/manywheel/build_wheel.sh
- builder/manywheel/entrypoint_build.sh
use `actions/checkout@v3` repo instead of git clone
> more general pypi ci

- lmdeploy/turbomind/turbomind.py
> [Fix] output[-1] when output is empty

- docs/en/build.md
- docs/zh_cn/build.md
To make sure developer can build the lmdeploy successfully.
add this code "make -j$(nproc) && make install" behind "sh  ../generate.sh"
No
No
4. The documentation has …
> Fix build.md

- src/turbomind/layers/sampling_layers/BaseSamplingLayer.cc
- src/turbomind/triton_backend/llama/LlamaTritonModelInstance.cc
sync https://github.com/NVIDIA/FasterTransformer/commit/afdf9a9eb86f15363c0249117d166d6b45dbb371
> Fix memory leak

- lmdeploy/turbomind/chat.py
> Fix side effect brought by supporting codellama: `sequence_start` is always true when calling `model.get_prompt`

- lmdeploy/model.py
> Miss meta instruction of internlm-chat model

- lmdeploy/version.py
> bump version to v0.0.10

- lmdeploy/pytorch_poc/chat.py
- lmdeploy/pytorch_poc/engine/engine.py
- lmdeploy/turbomind/tokenizer.py
This PR is to make trust_remote_code as an CLI argument, because some model (like falcon) has both hf version and hf-nub version.
> Make trust_remote_code as cli argument

- docs/en/pytorch.md
Fixed a minor typo in `docs/en/pytorch.md`
4. The documentation has been …
> Fix typo in `docs/en/pytorch.md`

- README.md
- README_zh-CN.md
- docs/en/kv_int8.md
- docs/zh_cn/kv_int8.md
https://huggingface.co/internlm/internlm-7b/tree/main stopped updating model weight since Aug 4.
> [Doc] update huggingface internlm-chat-7b model url

- lmdeploy/serve/openai/protocol.py
Fix typing of openai protocol.
> Fix typing of openai protocol.

- lmdeploy/serve/turbomind/deploy.py
- lmdeploy/turbomind/turbomind.py
> add tp hint for deployment

- .github/workflows/docker.yml
- .github/workflows/linux-x64-gpu.yml
- .github/workflows/pypi.yml
free runner disk space to download large docker image.
> free runner disk

- lmdeploy/version.py
> bump version to v0.0.11

- lmdeploy/serve/turbomind/deploy.py
> change `model_format` to `qwen` when `model_name` starts with `qwen`

- lmdeploy/serve/async_engine.py
- lmdeploy/serve/turbomind/chatbot.py
- lmdeploy/turbomind/chat.py
> avoid splitting chinese characters during decoding

- docs/en/build.md
- docs/zh_cn/build.md
Reverts InternLM/lmdeploy#370
Using Conda to install compilation dependencies is not very robust  #584
> Revert "[Docs] Simplify `build.md`"

- benchmark/README.md
- benchmark/profile_generation.py
- lmdeploy/serve/client.py
- lmdeploy/serve/turbomind/chatbot.py
- lmdeploy/turbomind/chat.py
fix crach case when last request end with eos_id and send another sequence_end request with empty input_ids
> Fix crash and remove `sys_instruct` from `chat.py` and `client.py`

- lmdeploy/version.py
> bump version to v0.0.12

- builder/manywheel/entrypoint_build.sh
- docs/en/build.md
- docs/zh_cn/build.md
> Add "build from docker" section

- lmdeploy/version.py
#541 has been merged, which needs a new release
1. Pre-commit or other linting tools are used to …
> bump version to v0.0.13

- .pre-commit-config.yaml
- lmdeploy/pytorch_poc/engine/cache_engine.py
- lmdeploy/pytorch_poc/engine/engine.py
- lmdeploy/pytorch_poc/utils.py
- requirements.txt
use pycuda fix memroy block_size error
get physical free memory size
> fix(pytorch_poc): memory cal

- lmdeploy/pytorch_poc/engine/engine.py
- lmdeploy/pytorch_poc/kernels/alibi_pagedattention.py
- lmdeploy/pytorch_poc/kernels/biased_pagedattention.py
- lmdeploy/pytorch_poc/kernels/fill_kv_cache.py
- lmdeploy/pytorch_poc/kernels/pagedattention.py
- tests/pytorch/kernel/test_paged_attention.py
- unittest
- split-k kernel (Great bonus to long context)
> Optimize attention

- src/turbomind/kernels/gpt_kernels.h
- src/turbomind/kernels/sampling_penalty_kernels.cu
- src/turbomind/layers/sampling_layers/TopKSamplingLayer.cu
- src/turbomind/layers/sampling_layers/TopPSamplingLayer.cu
- src/turbomind/models/llama/Barrier.h
- src/turbomind/models/llama/LlamaBatch.cc
- src/turbomind/models/llama/LlamaContextDecoder.cc
- src/turbomind/models/llama/LlamaDecoder.cc
- src/turbomind/models/llama/LlamaDecoderSelfAttentionLayer.cc
- src/turbomind/models/llama/LlamaV2.cc
- src/turbomind/models/llama/llama_utils.cu
- src/turbomind/models/llama/llama_utils.h
- src/turbomind/utils/memory_utils.cu
Also, set dynamic shared memory size before invoking `batchApplyRepetitionPenalty`
> Fix race condition & check for anormal values

- lmdeploy/model.py
> [Enchance] internlm message to prompt

- lmdeploy/serve/async_engine.py
- lmdeploy/turbomind/chat.py
- lmdeploy/turbomind/turbomind.py
https://github.com/InternLM/lmdeploy/blob/373bd01394cfa784a9ab3fe0d404d6ae1beee3d0/lmdeploy/serve/turbomind/chatbot.py#L101
> update turbomind session_len with model.session_len

- lmdeploy/serve/async_engine.py
- lmdeploy/turbomind/turbomind.py
> FIX: fix stop_session func bug

- lmdeploy/turbomind/deploy/source_model/llama.py
fix tokenizer_info when convert the model.
hf llama should use HuggingFaceTokenizer
> fix tokenizer_info when convert the model

- lmdeploy/version.py
> bump version to v0.0.14

- README.md
- README_zh-CN.md
- lmdeploy/lite/apis/auto_awq.py
> [Docs] Update Supported Matrix

- docs/en/kv_int8.md
- docs/zh_cn/kv_int8.md
> [Docs] Update KV8 Docs

- lmdeploy/serve/gradio/__init__.py
- lmdeploy/serve/gradio/turbomind_coupled.py
- lmdeploy/turbomind/turbomind.py
- src/turbomind/models/llama/LlamaBatch.cc
> fix turbomind stream canceling

- README.md
- README_zh-CN.md
- docs/en/turbomind_config.md
- docs/zh_cn/turbomind_config.md
- lmdeploy/turbomind/deploy/target_model/base.py
> Check-in user guide about turbomind config

- requirements/readthedocs.txt
- requirements/runtime.txt
> Replace mmengine with mmengine-lite

- lmdeploy/version.py
> bump version to v0.1.0a0

- src/turbomind/models/llama/LlamaBatch.cc
> [Fix] Skip empty batch

- docker/Dockerfile
> [Fix] build docker image failed since `packaging` is missing

- lmdeploy/serve/turbomind/triton_models/preprocessing/config.pbtxt
Fix #748 which is brought by #644 
1. Pre-commit or other linting tools are used to fix the …
> [Fix] Rollback the data type of `input_ids` to `TYPE_UINT32` in preprocessor's proto

- lmdeploy/pytorch_poc/config.py
- lmdeploy/pytorch_poc/engine/cache_engine.py
- lmdeploy/pytorch_poc/engine/engine.py
- lmdeploy/pytorch_poc/engine/model_agent.py
- lmdeploy/pytorch_poc/models/functional.py
- lmdeploy/pytorch_poc/models/llama.py
- lmdeploy/pytorch_poc/passkey_retrieval.py
add dynamic quantization for ReRoPE
* add quant
* update testcase
Achieve precision 1.0 at 40k input token length,  75GB GPU memory
> feat(lmdeploy): add rerope quantization

- .github/scripts/test_triton_server.py
- .github/workflows/test.yml
- docker/Dockerfile
- requirements/test.txt
add triton server test and workflow yml
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported …
> add triton server test and workflow yml

- lmdeploy/version.py
> bump version to 0.1.0a1

- benchmark/profile_generation.py
- benchmark/profile_throughput.py
- docs/en/benchmark/profile_throughput.md
- docs/zh_cn/benchmark/profile_throughput.md
> Fix missed arguments when benchmark static inference performance

- src/turbomind/models/llama/BlockManager.cc
- src/turbomind/models/llama/BlockManager.h
- src/turbomind/models/llama/LlamaBatch.cc
- src/turbomind/models/llama/SequenceManager.cc
- src/turbomind/models/llama/SequenceManager.h
Simplify block manager and fix possible inconsistent state.
> Simplify block manager

- README.md
- README_zh-CN.md
- benchmark/profile_generation.py
- benchmark/profile_restful_api.py
- benchmark/profile_serving.py
- benchmark/profile_throughput.py
- docs/en/kv_int8.md
- docs/zh_cn/kv_int8.md
> simplify the header of the benchmark table

- docs/en/restful_api.md
- docs/zh_cn/restful_api.md
- lmdeploy/serve/openai/api_client.py
- lmdeploy/serve/openai/api_server.py
- lmdeploy/serve/openai/protocol.py
https://github.com/open-compass/opencompass/pull/693
> add encode for opencompass

- lmdeploy/serve/async_engine.py
> fix api_server stop_session and end_session

- lmdeploy/turbomind/deploy/target_model/base.py
> fix turbomind awq

- lmdeploy/serve/async_engine.py
- lmdeploy/turbomind/turbomind.py
#832
Thanks for @frankxyy reporting the bug and proposing the resolution.
> Fix stop requests by await before turbomind queue.get()

- lmdeploy/lite/utils/load.py
> [Fix] Fix meta tensor error

- docs/en/restful_api.md
> [Docs] Fix typo in `restful_api ` user guide

- src/turbomind/models/llama/SequenceManager.cc
- src/turbomind/models/llama/SequenceManager.h
> Return the iterator after erasing it from a map

- lmdeploy/version.py
> bump version to v0.1.0

- requirements/serve.txt
add tritonclient req that removed in https://github.com/InternLM/lmdeploy/pull/580/
3. If the modification has a dependency on downstream projects of a newer version, this …
> add tritonclient req

- lmdeploy/lite/apis/calibrate.py
- lmdeploy/lite/apis/smooth_quant.py
- lmdeploy/lite/utils/load.py
> [Fix] Fix conflicts in `lite`

- src/turbomind/kernels/activation_kernels.cu
> Fix overflow

- README.md
- README_zh-CN.md
- examples/vl/README.md
- examples/vl/app.py
- examples/vl/extract_xcomposer_llm.py
- examples/vl/qwen_model.py
- examples/vl/xcomposer_model.py
- lmdeploy/serve/gradio/constants.py
> add image chat demo

- src/turbomind/models/llama/LlamaBatch.cc
> Fix context decoding stuck issue when tp > 1

- lmdeploy/pytorch/models/module_map.py
> fix pytorch llama2 with new transformers

- benchmark/profile_torch_generation.py
- benchmark/profile_torch_throughput.py
- lmdeploy/pytorch/__init__.py
- lmdeploy/pytorch/chat.py
- lmdeploy/pytorch/config.py
- lmdeploy/pytorch/engine/__init__.py
- lmdeploy/pytorch/engine/engine.py
> pytorch engine config

- lmdeploy/model.py
> register deepseek model

- lmdeploy/serve/turbomind/chatbot.py
> fix local variable 'output_ids' referenced before assignment

- lmdeploy/turbomind/engine_config.py
- lmdeploy/turbomind/turbomind.py
> remove unused settings in turbomind engine config

- docs/en/inference/pipeline.md
- docs/zh_cn/inference/pipeline.md
- lmdeploy/turbomind/engine_config.py
- lmdeploy/turbomind/turbomind.py
> Cleanup fixed attributes in turbomind engine config

- lmdeploy/serve/gradio/app.py
- lmdeploy/serve/gradio/turbomind_coupled.py
- lmdeploy/serve/openai/api_client.py
- lmdeploy/serve/openai/api_server.py
> Refactor gradio and api_server

- lmdeploy/pytorch/utils.py
> fix get_gpu_mem

- lmdeploy/pytorch/engine/engine.py
- lmdeploy/pytorch/engine/logits_process.py
- lmdeploy/pytorch/messages.py
> add pytorch random sampling

- docs/en/benchmark/profile_triton_server.md
- docs/zh_cn/benchmark/profile_generation.md
- docs/zh_cn/benchmark/profile_triton_server.md
> Fix scripts in benchmark doc

- lmdeploy/cli/utils.py
> fix cli with special arg names

- lmdeploy/__init__.py
- lmdeploy/api.py
- lmdeploy/messages.py
- lmdeploy/tokenizer.py
- lmdeploy/turbomind/__init__.py
avoid run get_logger when import lmdeploy
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported …
> avoid run get_logger when import lmdeploy

- lmdeploy/tokenizer.py
fix logger in tokenizer, brought by https://github.com/InternLM/lmdeploy/pull/956
3. If the modification has a dependency on downstream projects of a newer version, this PR …
> fix logger in tokenizer

- lmdeploy/pytorch/adapter/adapter.py
- lmdeploy/pytorch/engine/engine.py
- lmdeploy/pytorch/engine/model_agent.py
- lmdeploy/pytorch/models/peft.py
- adapter with MLP lora linear can be used now.
- enlarge TP cache size.
- bug fixing
> support mlp s-lora

- docs/en/advance/long_context.md
- docs/zh_cn/advance/long_context.md
> update long context doc

- lmdeploy/lite/quantization/calibration.py
> [Fix] Fix `calibrate` bug when `transformers>4.36`

- lmdeploy/version.py
> bump version to v0.2.0

- README.md
- README_zh-CN.md
- docs/en/get_started.md
- docs/zh_cn/get_started.md
> add guide about installation on cuda 12+ platform

- lmdeploy/version.py
InternLM2 chat template is changed.
> bump version to v0.2.1

- lmdeploy/tokenizer.py
fix https://github.com/InternLM/lmdeploy/issues/979 …
> fix import error for triton server

- examples/vl/app.py
address https://github.com/InternLM/lmdeploy/issues/971
获取 id -> token映射的时候，qwen-vl-tokenizer 对一些特殊token id有成对出现的要求。 https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/tokenizer.py#L234-L238
> fix qwen-vl example

- lmdeploy/pytorch/engine/engine.py
- lmdeploy/pytorch/paging/scheduler.py
> hide stop word

- .github/workflows/unit-test.yml
- tests/pytorch/engine/test_logits_process.py
update ut ci to new server node …
> update ut ci to new server node

- lmdeploy/serve/openai/protocol.py
> set example values to /v1/chat/completions in swagger UI

- lmdeploy/pytorch/config.py
- lmdeploy/pytorch/engine/model_agent.py
- lmdeploy/pytorch/models/patch.py
- tests/pytorch/engine/test_logits_process.py
- Delete huggingface model would not reduce the ref-count of the weights.
- archtectures and auto_map are not required in huggingface config.
- Fix none stop words error.
> fix tp mem usage

- docs/en/advance/pytorch_new_model.md
- docs/zh_cn/advance/pytorch_new_model.md
- lmdeploy/pytorch/engine/model_agent.py
- lmdeploy/pytorch/models/llama.py
- lmdeploy/pytorch/tools/__init__.py
- lmdeploy/pytorch/tools/layout_convert.py
- lmdeploy/pytorch/tools/make_inputs.py
- tests/pytorch/tools/test_layout_convert.py
- tests/pytorch/tools/test_make_inputs.py
This tool can be used to align the rewrite module to the origin module.
Provide layout conversion, input/output extractor and context maker.
> add alignment tools

- README.md
- README_zh-CN.md
- docs/en/serving/restful_api.md
- docs/zh_cn/serving/restful_api.md
> [doc] Introduce project OpenAOE

- docs/en/faq.md
- docs/en/inference/pipeline.md
- docs/zh_cn/faq.md
- docs/zh_cn/inference/pipeline.md
- lmdeploy/messages.py
Users complains about OOM a lot
> update pipeline guide and FAQ about OOM

- docs/en/inference/turbomind_config.md
- docs/zh_cn/inference/turbomind_config.md
docs update cache_max_entry_count for turbomind config
update turmomind_config
> docs update cache_max_entry_count for turbomind config

- lmdeploy/pytorch/dist_utils.py
…ize_linear_fn
If this PR introduces a new feature, it is better to list some use cases here, and update the …
> [Fix] Support QLinear in rowwise_parallelize_linear_fn and colwise_parallelize_linear_fn

- lmdeploy/tokenizer.py
> Remove caching tokenizer.json

- lmdeploy/serve/async_engine.py
https://github.com/InternLM/lmdeploy/issues/1058
workaround by distinguishing between different backends
> fix turbomind CUDA runtime error invalid argument

- lmdeploy/turbomind/turbomind.py
> fix device for get_ppl

- docs/en/inference/pipeline.md
- docs/zh_cn/inference/pipeline.md
- lmdeploy/messages.py
- lmdeploy/serve/async_engine.py
- lmdeploy/serve/openai/api_client.py
- lmdeploy/serve/openai/api_server.py
- lmdeploy/serve/openai/protocol.py
- lmdeploy/serve/turbomind/chatbot.py
- lmdeploy/serve/turbomind/triton_models/postprocessing/1/model.py
- lmdeploy/serve/turbomind/triton_models/postprocessing/config.pbtxt
- lmdeploy/serve/turbomind/utils.py
- lmdeploy/tokenizer.py
> Add skip_special_tokens in GenerationConfig 

- lmdeploy/serve/async_engine.py
> use default stop words for turbomind backend in pipeline

- docs/en/inference/pipeline.md
- docs/zh_cn/inference/pipeline.md
- lmdeploy/messages.py
- lmdeploy/serve/async_engine.py
Users from the community wants to get the token number of input prompts when using pipeline
> Add input_token_len to Response and update Response document

- README.md
- README_zh-CN.md
- docs/en/inference/pipeline.md
- docs/zh_cn/inference/pipeline.md
- lmdeploy/messages.py
- lmdeploy/pytorch/engine/engine.py
- lmdeploy/turbomind/deploy/converter.py
- lmdeploy/turbomind/turbomind.py
- lmdeploy/turbomind/utils.py
- lmdeploy/utils.py
support loading model from modelscope
https://github.com/InternLM/lmdeploy/issues/1038
> Support loading model from modelscope

- lmdeploy/lite/apis/smooth_quant.py
- lmdeploy/pytorch/modeling/modeling_internlm2.py
> [Fix] configuration_internlm.py -> configuration_internlm2.py

- lmdeploy/pytorch/adapter/adapter.py
- requirements/runtime.txt
peft remove constant value `COMMON_LAYERS_PATTERN` now.
tested on peft==0.7.1 and peft==0.8.2 with adapters [Llama2-Chinese-7b-Chat-LoRA](https://huggingface.co/FlagAlpha/Llama2-Chinese-7b-Chat-LoRA) and [Chinese-Llama-2-LoRA-7B](https://huggingface.co/seeledu/Chinese-Llama-2-LoRA-7B)
> fix pytorch engine with peft==0.8.2

- docs/en/advance/debug_turbomind.md
- docs/zh_cn/advance/debug_turbomind.md
add debug Turbomind guide
add debug Turbomind guide in `advance` section
> docs add debug turbomind guide

- lmdeploy/pytorch/kernels/pagedattention.py
- requirements/runtime.txt
This PR fix `tl.ravel` which used in paged attention kernel.
Note that problems of ptxas are not fixed.
> support triton2.2

- docs/en/inference/pipeline.md
- docs/zh_cn/inference/pipeline.md
- lmdeploy/messages.py
- lmdeploy/pytorch/check_env/__init__.py
- lmdeploy/pytorch/check_env/triton_custom_add.py
- lmdeploy/pytorch/config.py
- lmdeploy/pytorch/engine/engine.py
- lmdeploy/pytorch/engine/model_agent.py
> Support torch cache_max_entry_count

- lmdeploy/serve/openai/api_server.py
- lmdeploy/serve/openai/protocol.py
- lmdeploy/serve/qos_engine/qos_engine.py
> Add `top_k` in ChatCompletionRequest

- benchmark/profile_generation.py
Fix issue https://github.com/InternLM/lmdeploy/issues/1145
Make sure session_len >= prompt_tokens + completion_tokens to avoid insufficient generation length issue.
4. …
> Fix session length for profile generation

- docs/en/index.rst
- docs/zh_cn/index.rst
- lmdeploy/pytorch/engine/engine.py
- lmdeploy/pytorch/passkey_retrieval.py
Fix bug in torch engine infer method …
> fix torch engine infer

- README.md
- README_zh-CN.md
Added tutorial document for deploying lmdeploy on Jetson series boards. 
添加了对Jetson系列板卡部署LMDeploy的教程文档。
> Added tutorial document for deploying lmdeploy on Jetson series boards. 

- docs/en/inference/pipeline.md
- docs/zh_cn/inference/pipeline.md
- lmdeploy/messages.py
- lmdeploy/turbomind/deploy/target_model/base.py
- lmdeploy/turbomind/turbomind.py
Fix OOM for large context length
> Add parameter `max_prefill_token_num`

- lmdeploy/pytorch/models/module_map.py
> fix module map

- lmdeploy/serve/gradio/api_server_backend.py
- lmdeploy/serve/gradio/turbomind_coupled.py
> [Fix] Correct session length warning

- lmdeploy/serve/openai/api_server.py
> [Fix] Use distinct session id instead of random

- lmdeploy/model.py
> Fix falcon chatglm2 template

- lmdeploy/pytorch/engine/engine.py
- lmdeploy/pytorch/engine/logits_process.py
- lmdeploy/pytorch/engine/request.py
- lmdeploy/pytorch/kernels/__init__.py
- lmdeploy/pytorch/kernels/multinomial_sampling.py
- lmdeploy/pytorch/messages.py
- tests/pytorch/engine/test_logits_process.py
- tests/pytorch/kernel/test_multinomial_sampling.py
Inputs with different sampling parameters can be batched together now.
- add custom multinomial sampling kernel.
- batchlize all sampling processor
- repetition penalty
> Batched sampling

- requirements/test.txt
pytest upgrade to 8.1.0
the testcase are incompatible in the newest version
> fix pytest version

- docs/en/index.rst
- docs/zh_cn/index.rst
Update the document index so we can access it at https://lmdeploy.readthedocs.io/en/latest/.
minor
> update doc index

- src/turbomind/models/llama/LlamaBatch.cc
address https://github.com/InternLM/lmdeploy/issues/1232
> fix different stop/bad words length in batch

- lmdeploy/pytorch/kernels/pagedattention.py
`_NV_CAP = torch.cuda.get_device_capability()` would raise runtime error when torch and cuda driver version mismatch.
And it would bypass `env_check` if we put it in global field.
> lazy load convert_pv jit function

- lmdeploy/pytorch/paging/block_manager/window_block_manager.py
fix the case when num_used_blocks < 0 
1. Pre-commit or other linting tools are used to fix the …
> [BUG] fix the case when num_used_blocks < 0 

- lmdeploy/pytorch/check_env/__init__.py
> fix bf16 check

- benchmark/profile_serving.py
- lmdeploy/serve/turbomind/chatbot.py
@zhulinJulia24 May have a check.
> [Fix] fix triton server chatbot init error

- lmdeploy/cli/serve.py
- lmdeploy/serve/gradio/app.py
- lmdeploy/serve/gradio/vl.py
add vl gradio demo based on VLAsyncEngine
lmdeploy serve gradio /nvme/chenxin/download/tmp/llava-v1.6-vicuna-7b/ --server-port 7008
> Serve VLM by gradio

- lmdeploy/pytorch/models/peft.py
> fix torch tp lora adapter

- lmdeploy/archs.py
address https://github.com/InternLM/lmdeploy/pull/1299#issuecomment-2003590415
> Fix crash when api_server loads a turbomind model

- README.md
- README_zh-CN.md
add citation in readme
add citation in readme
None
> add citation in readme

- lmdeploy/model.py
- tests/test_lmdeploy/test_model.py
https://huggingface.co/deepseek-ai/deepseek-coder-33b-instruct/blob/main/tokenizer_config.json
> add chat template for deepseek coder model

- lmdeploy/serve/gradio/vl.py
- lmdeploy/serve/vl_async_engine.py
https://github.com/InternLM/lmdeploy/pull/1286 add a new arg to `AsyncEngine._get_prompt_input`
> add missed argument

- src/turbomind/kernels/sampling_penalty_kernels.cu
> fix batchApplyRepetitionPenalty

- lmdeploy/vl/model/qwen.py
accelerate import lmdeploy.pipeline
> lazy import accelerate.init_empty_weights for vl async engine

- lmdeploy/turbomind/turbomind.py
- lmdeploy/vl/engine.py
- lmdeploy/vl/model/llava.py
- lmdeploy/vl/model/qwen.py
- lmdeploy/vl/model/yi.py
address https://github.com/InternLM/lmdeploy/issues/1333
> fix vlm inference with tp

- README.md
- README_zh-CN.md
- docs/en/supported_models/supported_models.md
- docs/zh_cn/supported_models/supported_models.md
- lmdeploy/pytorch/models/module_map.py
- lmdeploy/pytorch/models/qwen2_moe.py
- lmdeploy/pytorch/supported_models.py
- requirements/runtime.txt
Support qwen2 moe for pytorch engine
Model: [Qwen/Qwen1.5-MoE-A2.7B-Chat](https://huggingface.co/Qwen/Qwen1.5-MoE-A2.7B-Chat)
Doc: [qwen2_moe](https://huggingface.co/docs/transformers/main/model_doc/qwen2_moe#qwen2moe)
> [!WARNING]
> qwen2-moe PR https://github.com/huggingface/transformers/pull/29377 is not on a released version. You may need to install [transformers](https://huggingface.co/docs/transformers/installation#installing-from-source) from the source.
If this PR …
> Support qwen2 moe for pytorch engine

- tests/test_lmdeploy/test_model.py
> [Fix] fix the unit test of model name deduce

- docs/en/benchmark/a100_fp16.md
The test result in the doc does not specify the model name, so it will be confusing for people reading the data.
After searching the change history of the doc, I find that this [commit](https://github.com/InternLM/lmdeploy/commit/9e4205613aecc772a07998c5afd11a611250da5e#diff-2172237336541d38f9fe7078311c37c7ce46eafd125d1ebe1b8648485c67b901) remove the model name of the test data. So add "llama-7b" back.
> Add model name corresponding to the test data in the doc

- lmdeploy/pytorch/kernels/multinomial_sampling.py
- tests/pytorch/kernel/test_multinomial_sampling.py
sampling kernel failed on triton>=2.2.0
> fix sampling kernel

- lmdeploy/serve/turbomind/triton_python_backend/README.md
as titled
@lvhan028 @AllentDan To mitigate the prolonged integration cycle experienced with the prior pull request, which included Docker image version modifications, we've refined the documentation. These additions are intended to help users preemptively address memory leak concerns.
ref https://github.com/InternLM/lmdeploy/issues/1363 https://github.com/InternLM/lmdeploy/pull/1371
as titled …
> add the recommendation version for Python Backend

- lmdeploy/pytorch/check_env/__init__.py
- requirements/runtime.txt
> warning transformers version

- .github/workflows/unit-test.yml
> change cutlass url in ut

- lmdeploy/pytorch/engine/model_agent.py
> set infinity timeout to nccl

- lmdeploy/lite/apis/auto_awq.py
- lmdeploy/lite/apis/calibrate.py
- lmdeploy/lite/quantization/awq.py
- lmdeploy/lite/quantization/calibration.py
> Add qwen1.5 awq quantization

- lmdeploy/api.py
- lmdeploy/cli/entrypoint.py
- lmdeploy/serve/openai/api_server.py
> get model in advance to fix downloading from modelscope error

- README.md
- README_zh-CN.md
as titled ref https://github.com/InternLM/lmdeploy/issues/1472 @lvhan028 @AllentDan @grimoire 
as titled
> update supported models for Baichuan

- benchmark/profile_restful_api.py
- lmdeploy/serve/openai/api_client.py
Adding api_key and model_name parameters to the restful benchmark.
> Adding api_key and model_name parameters to the restful benchmark

- README.md
- README_zh-CN.md
> update readme wechat qrcode

- lmdeploy/turbomind/__init__.py
This pr https://github.com/InternLM/lmdeploy/pull/956 move bootstrap to turbomind folder but forget to change the lib path.
> Fix turbomind import in windows

- benchmark/profile_pipeline_api.py
- lmdeploy/serve/async_engine.py
after #1507 
addressing issue #1494 
python >= 3.10 is recommended.
> add benchmark script to profile pipeline APIs

- lmdeploy/turbomind/deploy/converter.py
> Fix convert qwen2 to turbomind

- docs/en/quantization/w8a8.md
update typo from ”4bit“ to "8bit"
> Fix typo in w8a8.md 

- lmdeploy/cli/cli.py
- lmdeploy/pytorch/chat.py
add chat-template args to chat cli
Requested by https://github.com/InternLM/lmdeploy/issues/1519 …
> add chat-template args to chat cli

- lmdeploy/utils.py
Side effect of https://github.com/InternLM/lmdeploy/pull/1550
> fix logger init

- lmdeploy/pytorch/kernels/w8a8_triton_kernels.py
Kernel would not recompile when M changes.
The performance on small batch size and short context is still not fast enough. Since triton kernel launch takes too much time.
> Optimize w8a8 kernel

- lmdeploy/serve/qos_engine/qos_engine.py
Bugfix 
Bugfix: fix bugs with error info:"
if gen_config.stop_words is None:
AttributeError: 'bool' object has no attribute 'stop_words'",which is caused by assign gen_config with value 'True'.
> Bugfix: wrongly assign gen_config with True 

- .github/workflows/cuda11.8-whl-release.yml
- .github/workflows/pypi.yml
- builder/manywheel/Dockerfile_2014
- builder/manywheel/build_all_wheel.sh
- builder/manywheel/entrypoint_build.sh
- requirements/runtime.txt
- src/turbomind/kernels/stop_criteria_kernels.cu
> support python 3.12

- lmdeploy/vl/model/xcomposer2.py
> Fix xcomposer2 vision model process

- lmdeploy/vl/model/deepseek.py
> fix deepseek-vl when tp is 1

- lmdeploy/pytorch/kernels/fused_moe.py
> fix fused-moe in triton2.2.0

- benchmark/profile_restful_api.py
> Align tokenizers in pipeline and api_server benchmark scripts

- lmdeploy/vl/model/xcomposer2.py
> [side-effect] fix UnboundLocalError for internlm-xcomposer2-4khd-7b

- lmdeploy/serve/openai/api_server.py
> Add health endpoint

- requirements/runtime.txt
> upgrade the version of the dependency package peft

- autotest/utils/run_restful_chat.py
- lmdeploy/serve/async_engine.py
- tests/test_lmdeploy/test_async_engine.py
> Follow the conventional model_name

- docs/en/faq.md
- docs/zh_cn/faq.md
- lmdeploy/vl/utils.py
> Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily receiving feedbacks. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.
When sending a request including an `image_url` to an external domain, if the external server fails to respond in a timely manner, the OpenAPI server and client both hang. This change adds a timeout to the `requests.get` call to cause a timeout exception and also fail the call on the client side. I chose what I thought was a conservative value `1 second`, but this could be increased or decreased. It may also be a good idea to make this a configurable parameter, since some servers are slow.
In order to reproduce, please …
> API Image URL fetch timeout 

- docker/Dockerfile
- docs/en/get_started.md
- docs/en/multi_modal/cogvlm.md
- docs/zh_cn/get_started.md
- docs/zh_cn/multi_modal/cogvlm.md
- lmdeploy/vl/model/cogvlm.py
update setuptools in dockerfile to fix `pkg_resources.ContextualVersionConflict` for lmdeploy cli
update docs for cogvlm …
> update dockerfile and docs

- lmdeploy/messages.py
fix https://github.com/InternLM/lmdeploy/issues/1732
@lvhan028 @irexyc May you help review this? Thanks.
as titled
> feat: align with OpenAI temperature range

- lmdeploy/serve/openai/api_server.py
fix https://github.com/InternLM/lmdeploy/pull/1733#issuecomment-2154180040
@lvhan028 @AllentDan @irexyc 
as titled
> feat: align with OpenAI temperature range in api server

- README.md
- README_zh-CN.md
Recently, BentoML conducted a benchmark https://www.bentoml.com/blog/benchmarking-llm-inference-backends comparison of mainstream LLM inference frameworks in the industry, including an example of how to integrate with bentoml. As bentoml has a large user base overseas, I believe this is beneficial for promoting LMDeploy. Perhaps we may add it in the README. @lvhan028 @lzhangzz 
as titled
4. The documentation has been modified accordingly, …
> docs: add BentoLMDeploy in README

- lmdeploy/pytorch/engine/engine.py
Fix: The last generated token will not be cached.
> fix uncached stop words

- .github/resources/opencompass-hf-results.json
- .github/workflows/daily_ete_test.yml
- autotest/config.yaml
- autotest/interface/pipeline/test_pipeline_func.py
- autotest/interface/pipeline/test_pipeline_longtext_func.py
- autotest/interface/restful/test_restful_chat_func.py
**1. add Qwen/Qwen2-7B-Instruct into testcase.
2. fix fail testcase because of param temperature's upper limit change to 2.0.**
3. fix typo in daily test case yaml file.
> add qwen2 model into testcase

- lmdeploy/pytorch/config.py
- lmdeploy/pytorch/configurations/__init__.py
- lmdeploy/pytorch/configurations/builder.py
- lmdeploy/pytorch/configurations/chatglm.py
- lmdeploy/pytorch/configurations/cogvlm.py
- lmdeploy/pytorch/configurations/dbrx.py
- lmdeploy/pytorch/configurations/default.py
- lmdeploy/pytorch/configurations/falcon.py
- lmdeploy/pytorch/configurations/gemma.py
- lmdeploy/pytorch/configurations/qwen.py
> refactor config

- lmdeploy/pytorch/kernels/pagedattention.py
- lmdeploy/pytorch/models/llama.py
falcon-7b has 71 heads, leads to attention kernel error.
> fix falcon attention

- lmdeploy/serve/async_engine.py
- lmdeploy/turbomind/turbomind.py
#1788
The pytorch backend still hangs. @grimoire is going to fix it.
> Refine AsyncEngine exception handler

- requirements/runtime.txt
> fix: prevent numpy breakage

- lmdeploy/pytorch/check_env/__init__.py
add a special error log when device kernel image invalid.
> check driver mismatch

- lmdeploy/model.py
- tests/test_lmdeploy/test_model.py
The tokenizer in transformers < 4.34.0 doesn't have `chat_template` attributes.
https://github.com/huggingface/transformers/blob/v4.34.0/src/transformers/tokenization_utils_base.py#L1640
> fix best_match_model

- src/turbomind/models/llama/LlamaV2.cc
> Fix Request completed log

- lmdeploy/pytorch/engine/request.py
- lmdeploy/serve/async_engine.py
related PR: #1789
optimize performance of pytorch engine threadsafe mode.
> AsyncEngine create cancel task in exception.

- lmdeploy/vl/engine.py
fix small typo
fix small typo
If this PR introduces a new feature, it is better to list some use cases here, and …
> Update engine.py to fix small typos

- lmdeploy/lite/quantization/calibration.py
- lmdeploy/pytorch/models/internlm2.py
compat internlm2 for pytorch engine
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions …
> compat internlm2 for pytorch engine

- lmdeploy/vl/engine.py
remove error message when exit program
https://github.com/InternLM/lmdeploy/issues/1818
> fix image encoder request queue 

- lmdeploy/turbomind/turbomind.py
- src/turbomind/models/llama/LlamaBatch.cc
> Harden stream callback

- lmdeploy/pytorch/messages.py
as titled
Hi @grimoire @lzhangzz @lvhan028 May you help review this? Thanks.
ref TurboMind
https://github.com/InternLM/lmdeploy/blob/c59a70413c3600fb22e683c46e085758272e4178/src/turbomind/kernels/sampling_penalty_kernels.cu#L149-L161
https://github.com/InternLM/lmdeploy/blob/c59a70413c3600fb22e683c46e085758272e4178/src/turbomind/kernels/sampling_penalty_kernels.cu#L75-L86
as titled
4. The documentation has been modified accordingly, like …
> misc: align PyTorch Engine temprature with TurboMind

- .github/scripts/action_tools.py
- .github/scripts/eval_opencompass_config.py
- .github/workflows/evaluate.yml
1. make pt_internlm2-chat-7b's max batch size to 64, becuase of OOM when  max batch size is 128
2. react config template of internlm2、llama3 and qwen1.5
3. add config template of qwen2
4. add a choice by using local eval config
5. by using -r option when doing evaluation, if one model is failed we can rerun
> react test evaluation config

- lmdeploy/archs.py
- lmdeploy/utils.py
- tests/test_lmdeploy/test_utils.py
> Fix vl session-len

- lmdeploy/model.py
- tests/test_lmdeploy/test_model.py
fix model name matching for internvl
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions …
> fix model name matching for internvl

- lmdeploy/serve/gradio/vl.py
> fix gradio vl "stop_words"

- src/turbomind/models/llama/LlamaDecoderLayerWeight.cc
- src/turbomind/models/llama/LlamaDecoderLayerWeight.h
- src/turbomind/models/llama/LlamaDenseWeight.h
- src/turbomind/models/llama/LlamaFfnLayer.cc
- src/turbomind/models/llama/LlamaFfnLayer.h
- src/turbomind/models/llama/LlamaV2.cc
- src/turbomind/models/llama/LlamaV2.h
- src/turbomind/models/llama/LlamaWeight.cc
- src/turbomind/models/llama/LlamaWeight.h
- src/turbomind/models/llama/llama_gemm.cc
- src/turbomind/models/llama/unified_attention_layer.cc
- src/turbomind/models/llama/unified_attention_layer.h
- src/turbomind/triton_backend/llama/CMakeLists.txt
- src/turbomind/triton_backend/llama/LlamaTritonModel.cc
- src/turbomind/triton_backend/llama/LlamaTritonModel.h
- src/turbomind/triton_backend/llama/LlamaTritonModelInstance.cc
- src/turbomind/triton_backend/llama/LlamaTritonModelInstance.h
- src/turbomind/triton_backend/transformer_triton_backend.cpp
- src/turbomind/triton_backend/transformer_triton_backend.hpp
>  Fix error link reference

- lmdeploy/lite/quantization/calibration.py
> Fix internlm-xcomposer2-vl awq search scale

- docs/en/faq.md
- docs/zh_cn/faq.md
as titled
Hi @lzhangzz @irexyc @lvhan028 May you help review this pr? Thanks.
as titled …
> docs: update faq for turbomind so not found

- docs/en/.readthedocs.yaml
- docs/en/_static/css/readthedocs.css
- docs/en/conf.py
- docs/en/index.rst
- docs/en/switch_language.md
- docs/zh_cn/.readthedocs.yaml
- docs/zh_cn/_static/css/readthedocs.css
- docs/zh_cn/conf.py
- docs/zh_cn/index.rst
- docs/zh_cn/switch_language.md
- requirements/docs.txt
use sphinx-book-theme for readthedocs
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions …
> [Doc]: Change to sphinx-book-theme in readthedocs

- src/turbomind/kernels/attention/attention_template.h
- src/turbomind/kernels/attention/attention_universal.h
- src/turbomind/kernels/attention/decoding_template.h
Smem size for fused reduction is not accounted for, this PR fixes it.
1. Pre-commit or other …
> Fix smem size for fused split-kv reduction

- lmdeploy/serve/openai/api_client.py
as titled, trivial modification
cc @AllentDan @grimoire @lvhan028 
as titled
> misc: add default api_server_url for api_client

- lmdeploy/cli/utils.py
- lmdeploy/tokenizer.py
ref https://github.com/InternLM/lmdeploy/issues/1903#issuecomment-2205599678 cc @grimoire 
tested with `python3 -m lmdeploy serve api_server /workdir/Qwen2-72B-Instruct --log-level WARNING --tp 4`
Hi @lzhangzz @irexyc @grimoire @AllentDan @lvhan028 May you help review this pr? Thanks.
as titled
> misc: add transformers version check for TurboMind Tokenizer

- README.md
- README_zh-CN.md
as titled cc @lvhan028 @AllentDan @grimoire 
Compared with vLLM and TensorRT LLM, LMDeploy can simultaneously utilize these performance-optimizing features. It has excellent compatibility and is a highlight-worthy point.
as titled
> docs: update compatibility section in README

- lmdeploy/cli/cli.py
as titled cc @lvhan028 @AllentDan @grimoire 
```bash
python3 -m lmdeploy check_env
```
```
NVIDIA Topology:
GPU0	GPU1	mlx5_0	mlx5_1	mlx5_2	mlx5_3	mlx5_4	mlx5_5	mlx5_6	mlx5_7	CPU Affinity	NUMA Affinity
GPU0	 X 	NV12	SYS	SYS	SYS	SYS	NODE	NODE	PXB	PXB	48-95,144-191	1
GPU1	NV12	 X 	SYS	SYS	SYS	SYS	NODE	NODE	PXB	PXB	48-95,144-191	1
mlx5_0	SYS	SYS	 X 	PIX	NODE	NODE	SYS	SYS	SYS	SYS
mlx5_1	SYS	SYS	PIX	 X 	NODE	NODE	SYS	SYS	SYS	SYS
mlx5_2	SYS	SYS	NODE	NODE	 X 	PIX	SYS	SYS	SYS	SYS
mlx5_3	SYS	SYS	NODE	NODE	PIX	 X 	SYS	SYS	SYS	SYS
mlx5_4	NODE	NODE	SYS	SYS	SYS	SYS	 X 	PIX	NODE	NODE
mlx5_5	NODE	NODE	SYS	SYS	SYS	SYS	PIX	 X 	NODE	NODE
mlx5_6	PXB	PXB	SYS	SYS	SYS	SYS	NODE	NODE	 X 	PIX
mlx5_7	PXB	PXB	SYS	SYS	SYS	SYS	NODE	NODE	PIX	 X
Legend:
X    = Self
SYS  = Connection traversing PCIe as well as the SMP …
```
> feat: add gpu topo for check_env

- lmdeploy/model.py
- tests/test_lmdeploy/test_model.py
> fix llama3 chat template

- lmdeploy/tokenizer.py
- tests/test_lmdeploy/test_tokenizer.py
hot fix cc @AllentDan @RunningLeon @grimoire @lvhan028 
ref https://huggingface.co/OpenGVLab/InternVL2-26B/blob/main/config.json#L14
as titled
> fix transformers version check for InternVL2

- lmdeploy/turbomind/deploy/source_model/internvl.py
address https://github.com/InternLM/lmdeploy/issues/1965
> Fix internvl2-40b model export

- lmdeploy/pytorch/models/llama.py
- lmdeploy/turbomind/supported_models.py
Support [OpenGVLab/InternVL2-1B](https://huggingface.co/OpenGVLab/InternVL2-1B) for pytorch engine
related issue: https://github.com/InternLM/lmdeploy/issues/1963
3. If the …
> support internvl2-1b

- docs/en/index.rst
- docs/zh_cn/index.rst
as titled cc @lvhan028 @RunningLeon 
fix https://github.com/InternLM/lmdeploy/issues/1975 ref https://github.com/InternLM/lmdeploy/issues/1975#issuecomment-2220157740
as titled
> docs: sync the core features in README to index.rst

- lmdeploy/utils.py
- tests/test_lmdeploy/test_turbomind/test_converter.py
- tests/test_lmdeploy/test_utils.py
The `scaling_factor` can not be used to determine the context window size
> Fix the session_len assignment logic

- lmdeploy/messages.py
- lmdeploy/pytorch/engine/devices/ascend.py
- lmdeploy/pytorch/engine/devices/dipu.py
- lmdeploy/pytorch/kernels/ascend/__init__.py
- lmdeploy/pytorch/kernels/default/__init__.py
- lmdeploy/pytorch/kernels/default/multinomial_sampling.py
- lmdeploy/pytorch/kernels/dipu/__init__.py
- lmdeploy/pytorch/kernels/dipu/apply_rotary_pos_emb.py
- lmdeploy/pytorch/kernels/dipu/fill_kv_cache.py
- lmdeploy/pytorch/kernels/dipu/fused_rotary_emb.py
- lmdeploy/pytorch/kernels/dipu/pagedattention.py
- lmdeploy/pytorch/kernels/dipu/rms_norm.py
- lmdeploy/pytorch/models/internlm2.py
- lmdeploy/pytorch/models/llama.py
- lmdeploy/pytorch/models/module_map.py
* support llama2 and internlm2 on 910B.
* optimize paged_attention
* optimize rotary_emb
* fix module map
* optimize rotary_emb and move multinomial_sampling into default folder
> feat: support llama2 and internlm2 on 910B

- docs/en/quantization/w4a16.md
as titled cc @lvhan028 @AllentDan 
as titled
> docs: fix Ada compatibility

- docs/en/multi_modal/xcomposer2d5.md
- docs/zh_cn/multi_modal/xcomposer2d5.md
- lmdeploy/lite/apis/auto_awq.py
- lmdeploy/model.py
- lmdeploy/turbomind/deploy/source_model/xcomposer2.py
- lmdeploy/turbomind/deploy/target_model/plora_w4.py
- lmdeploy/vl/model/xcomposer2.py
- lmdeploy/vl/templates.py
- lmdeploy/vl/tools/__init__.py
- lmdeploy/vl/tools/merge_xcomposer2d5_task.py
- tests/test_lmdeploy/test_model.py
support [internlm-xcomposer2d5-7b](https://huggingface.co/internlm/internlm-xcomposer2d5-7b)
related issues https://github.com/InternLM/lmdeploy/issues/1920
> support internlm-xcomposer2d5-7b

- README.md
- README_zh-CN.md
- docs/en/supported_models/supported_models.md
- docs/zh_cn/supported_models/supported_models.md
- lmdeploy/model.py
- tests/test_lmdeploy/test_model.py
support [THUDM/codegeex4-all-9b](https://huggingface.co/THUDM/codegeex4-all-9b)
3. If the modification has a dependency on downstream projects of a newer version, this PR …
> add chat template for codegeex4

- lmdeploy/turbomind/deploy/source_model/internvl.py
> Fix internvl2-40b awq inference

- docs/en/multi_modal/xcomposer2d5.md
- docs/zh_cn/multi_modal/xcomposer2d5.md
> update xcomposer2d5 docs

- src/turbomind/layers/sampling_layers/TopKSamplingLayer.cc
- src/turbomind/utils/allocator.h
> add debug log for topk

- .github/ISSUE_TEMPLATE/1-bug-report.yml
as titled cc @lvhan028 @RunningLeon @AllentDan 
as titled
> misc: update bug issue template

- README.md
review not overview，wrong expression
If this PR introduces a new feature, it is better to list some use cases here, …
> wrong expression

- lmdeploy/pytorch/kernels/cuda/pagedattention.py
- lmdeploy/pytorch/models/gemma.py
> support logit softcap

- src/turbomind/kernels/gemm_s_f16/cta_iterator.h
Fix the WAW(write after write) conflict bug in awq gemm CUDA kernel.
Before, this kernel use a wrong offset computation(gmem -> smem, dim-N).
Now, use a var(upper_n_) to avoid WAW conflict.
> Fix gmem to smem WAW conflict in awq gemm kernel

- lmdeploy/model.py
- tests/test_lmdeploy/test_model.py
https://github.com/InternLM/lmdeploy/issues/2161
> Support specifying a prefix of assistant response

- README.md
- README_zh-CN.md
> update news about cooperation with modelscope/swift

- src/turbomind/models/llama/unified_attention_layer.cc
opt-in with `TM_DEBUG_LEVEL=DEBUG`
> Check errors for attention kernels

- lmdeploy/turbomind/deploy/source_model/internvl.py
- lmdeploy/turbomind/deploy/source_model/llama.py
- lmdeploy/turbomind/deploy/source_model/qwen.py
> support VLMs with Qwen as the language model

- README.md
- docs/en/supported_models/supported_models.md
- docs/zh_cn/supported_models/supported_models.md
> clearify the model type LLM or MLLM in supported model matrix

- lmdeploy/model.py
- lmdeploy/serve/async_engine.py
- lmdeploy/serve/gradio/turbomind_coupled.py
> Fix gradio serve using a wrong chat template

- lmdeploy/vl/model/minicpmv.py
- lmdeploy/vl/templates.py
> adapt MiniCPM-Llama3-V-2_5 new code

- benchmark/profile_generation.py
> Fix typos in profile_generation.py

- lmdeploy/serve/openai/api_client.py
> Remove duplicate code

- README.md
- README_ja.md
- README_zh-CN.md
- docs/en/get_started.md
- docs/en/multi_modal/cogvlm.md
- docs/zh_cn/get_started.md
- docs/zh_cn/multi_modal/cogvlm.md
- lmdeploy/version.py
> bump version to v0.5.3

- docs/en/supported_models/supported_models.md
- docs/zh_cn/supported_models/supported_models.md
awq with old baichuan2 7b version not supported.
https://huggingface.co/baichuan-inc/Baichuan2-7B-Chat/commit/2ce891951e000c36c65442608a0b95fd09b405dc
> cancel support baichuan2 7b awq in pytorch engine

- lmdeploy/pytorch/configurations/phi3_vision.py
- lmdeploy/serve/vl_async_engine.py
- lmdeploy/vl/engine.py
- lmdeploy/vl/model/base.py
- lmdeploy/vl/model/internvl.py
- lmdeploy/vl/templates.py
Support custom image process parameters in openai input format.
```python
from openai import OpenAI
client = OpenAI(base_url='http://0.0.0.0:23333/v1', api_key='abc')
response = client.chat.completions.create(
model="/nvme/shared/InternVL2-26B/",
messages=[
{
"role": "user",
"content": [
{"type": "text", "text": "What’s in this image?"},
{
"type": "image_url",
"image_url": {
"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Gfp-wisconsin-madison-the-nature-boardwalk.jpg/2560px-Gfp-wisconsin-madison-the-nature-boardwalk.jpg",
"detail": "low",
},
},
],
}
],
max_tokens=300,
)
```
> support vlm custom image process parameters in openai input format

- lmdeploy/turbomind/deploy/converter.py
- lmdeploy/turbomind/turbomind.py
> fix side-effect: failed to update tm model config with tm engine config

- requirements/build.txt
> fix Windows compile error

- .github/workflows/pypi.yml
- .github/workflows/windows-x64-gpu.yml
> fix: follow up #2303

- lmdeploy/serve/openai/api_server.py
- lmdeploy/serve/openai/protocol.py
> Add stream options to control usage

- lmdeploy/cli/cli.py
- lmdeploy/cli/serve.py
- lmdeploy/cli/utils.py
- lmdeploy/turbomind/chat.py
add device type for pytorch engine in cli
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported …
> add device type for pytorch engine in cli

- lmdeploy/cli/cli.py
- lmdeploy/cli/lite.py
- lmdeploy/cli/serve.py
- lmdeploy/cli/utils.py
Change to use device instead of device-type in cli …
> Change to use device instead of device-type in cli

- lmdeploy/turbomind/turbomind.py
- src/turbomind/models/llama/LlamaBatch.cc
- src/turbomind/models/llama/LlamaV2.cc
- src/turbomind/models/llama/Request.h
Since all the threads except rank-0 are useless.
> Use single thread per model instance

- docker/Dockerfile
add cache to speed up docker building.
https://github.com/moby/buildkit/issues/1463
3. If the modification has a dependency on downstream projects of a newer version, this …
> add cache to speed up docker building

- lmdeploy/cli/serve.py
- lmdeploy/cli/utils.py
> add max_prefill_token_num argument in CLI

- lmdeploy/messages.py
- lmdeploy/pytorch/engine/engine.py
- lmdeploy/pytorch/engine/logits_process.py
- lmdeploy/pytorch/messages.py
- lmdeploy/serve/openai/api_server.py
- lmdeploy/serve/openai/protocol.py
```python
from lmdeploy import pipeline
from lmdeploy.messages import GenerationConfig, PytorchEngineConfig
model = 'InternLM/internlm2-chat-1_8b'
pipe = pipeline(model, backend_config=PytorchEngineConfig(), log_level='INFO')
def process_token(token_ids, logits):
logits[6623] = -9999.999 
logits[4853] = -9999.999
logits[630] = -9999.999
logits[985] = -9999.999
return logits
gen_config = GenerationConfig(logits_processors=[process_token])
response = pipe(['Make a self introduction please.', 'hi']*2, gen_config=gen_config)
print(response)
```
> Support custom logits processors

- lmdeploy/cli/utils.py
- lmdeploy/messages.py
- lmdeploy/turbomind/chat.py
> Default rope_scaling_factor of TurbomindEngineConfig to None

- README.md
- README_ja.md
- README_zh-CN.md
- docs/en/multi_modal/index.rst
- docs/en/multi_modal/phi3.md
- docs/en/supported_models/supported_models.md
- docs/zh_cn/multi_modal/index.rst
- docs/zh_cn/multi_modal/phi3.md
- docs/zh_cn/supported_models/supported_models.md
- lmdeploy/model.py
- lmdeploy/pytorch/models/module_map.py
- lmdeploy/pytorch/models/phi3_moe.py
- lmdeploy/pytorch/supported_models.py
- tests/test_lmdeploy/test_model.py
Support [phi3.5](https://huggingface.co/collections/microsoft/phi-3-6626e15e9585a200d2d761e3) for pytorch engine
`lmdeploy chat /mnt/bigdisk/microsoft/Phi-3_5-mini-instruct` …
> Support phi3.5 for pytorch engine

- lmdeploy/pytorch/models/baichuan.py
- lmdeploy/pytorch/models/chatglm2.py
- lmdeploy/pytorch/models/deepseek.py
- lmdeploy/pytorch/models/falcon.py
- lmdeploy/pytorch/models/internlm.py
- lmdeploy/pytorch/models/phi3.py
- lmdeploy/pytorch/models/starcoder2.py
Fix https://github.com/InternLM/lmdeploy/issues/2383 …
> fix cache position for pytorch engine

- lmdeploy/pytorch/check_env/__init__.py
- lmdeploy/serve/vl_async_engine.py
vlm model inference causes cuda error on huawei device.
import dlinfer before imageencoding(which causes cuda error) …
> import dlinfer before imageencoding

- .pre-commit-config.yaml
- docs/en/get_started/ascend/get_started.md
- docs/zh_cn/get_started/ascend/get_started.md
this pr added get_started doc for huawei ascend device
added new get_started into doc folder …
> add Ascend get_started

- .github/workflows/cuda11.8-whl-release.yml
- .github/workflows/pypi.yml
> update actions/download-artifact to v4 to fix security issue

- lmdeploy/pytorch/engine/logits_process.py
- tests/pytorch/engine/test_logits_process.py
inplace function has been named with postfix `_`.
> inplace logits process as default

- lmdeploy/vl/model/minicpmv.py
fix https://github.com/InternLM/lmdeploy/issues/2452
> fix tensors on different devices when deploying MiniCPM-V-2_6 with tensor parallelism

- lmdeploy/pytorch/backends/cuda/multinomial_sampling.py
- lmdeploy/pytorch/nn/multinomial_sampling.py
> fix MultinomialSampling operator builder

- src/turbomind/layers/sampling_layers/SamplingLayer.cc
- tests/csrc/unittests/test_sampling_kernels.cu
https://github.com/InternLM/lmdeploy/issues/2459
> Fix initialization of runtime_min_p

- README.md
- README_zh-CN.md
- docker/Dockerfile_aarch64_ascend
- docs/en/get_started/ascend/get_started.md
- docs/en/get_started/installation.md
- docs/en/supported_models/supported_models.md
- docs/zh_cn/get_started/ascend/get_started.md
- docs/zh_cn/get_started/installation.md
- docs/zh_cn/supported_models/supported_models.md
- lmdeploy/version.py
> bump version to v0.6.0

- lmdeploy/serve/gradio/vl.py
> fix vl gradio

- lmdeploy/utils.py
> support downloading models from openmind_hub

- docs/en/quantization/w4a16.md
- requirements/docs.txt
https://github.com/sphinx-doc/sphinx/issues/13002
1. Pre-commit or other linting tools are used to …
> [Doc]: Lock sphinx version

- README.md
This PR fixes a minor spacing issue in the Ascend part of the README.
> Fix spacing in README

- lmdeploy/pytorch/backends/cuda/graph_runner.py
fix https://github.com/InternLM/lmdeploy/issues/2544
> set capture mode thread_local

- lmdeploy/pytorch/backends/dlinfer/moe.py
- lmdeploy/pytorch/kernels/dlinfer/__init__.py
- lmdeploy/pytorch/kernels/dlinfer/fused_moe.py
This PR refactor fused_moe (ascend).
Add fused_moe kernel (ascend).
Related PR https://github.com/DeepLink-org/dlinfer/pull/63
1. Pre-commit or other linting …
> [ascend] refactor fused_moe on ascend platform

- lmdeploy/cli/utils.py
- lmdeploy/messages.py
- lmdeploy/pytorch/backends/dlinfer/__init__.py
- lmdeploy/pytorch/backends/dlinfer/maca/__init__.py
- lmdeploy/pytorch/backends/dlinfer/maca/op_backend.py
- lmdeploy/pytorch/backends/selector.py
- lmdeploy/pytorch/check_env/__init__.py
- lmdeploy/pytorch/models/module_map.py
- lmdeploy/utils.py
> [maca] add maca backend support.

- lmdeploy/pytorch/check_env/__init__.py
- lmdeploy/pytorch/check_env/triton_custom_add.py
- lmdeploy/pytorch/kernels/cuda/pagedattention.py
- Update check for triton
- recovery pagedattention `BLOCK_M` update which is removed accidentally when merge PR.
> update check for triton

- requirements/runtime.txt
> match torch and vision version

- tests/pytorch/kernel/test_fill_kv_cache.py
Sometimes, `(kv - amin) / scales)` might be different from `kv/scales - amin/scales` for quantization.
> Align UT with triton fill_kv_cache_quant kernel

- docker/Dockerfile_aarch64_ascend
ascend platform has already support graph mode, update Dockerfile for the dependencies.
update Dockerfile_aarch64_ascend for:
1. dlinfer-asccend 0.1.0.post1 -> 0.1.1
2. torch 2.1.0 -> 2.3.1 (torch_npu as well)
3. add nnal installation …
> update ascend dockerfile

- docker/Dockerfile_aarch64_ascend
> fix syntax in Dockerfile_aarch64_ascend

- docker/Dockerfile_aarch64_ascend
Always use the latest dlinfer-ascend package from pypi, this would reduce the change of Dockerfile_aarch_ascend
dlinfer-ascend==0.1.1.post1 is about to be published for hotfix.
remove the version constrain in docker/Dockerfile_aarch_ascend
If this PR introduces a new …
> remove dlinfer version

- .github/scripts/eval_chat_config.py
- .github/workflows/daily_ete_test.yml
- .github/workflows/daily_ete_test_v100.yml
- autotest/config-v100.yaml
- autotest/interface/pipeline/test_pipeline_func.py
- autotest/utils/benchmark_utils.py
- autotest/utils/config_utils.py
- autotest/utils/pipeline_chat.py
- autotest/utils/quantization_utils.py
- autotest/utils/run_client_chat.py
- autotest/utils/run_restful_chat.py
- benchmark/profile_generation.py
- benchmark/profile_throughput.py
> [ci] support v100 dailytest 

- docs/en/get_started/ascend/get_started.md
- docs/zh_cn/get_started/ascend/get_started.md
> fix ascend get_started.md link

- docs/en/llm/pipeline.md
- docs/zh_cn/llm/pipeline.md
- lmdeploy/serve/utils.py
Fix https://github.com/InternLM/lmdeploy/issues/2693
> fix index error when computing ppl on long-text prompt

- src/turbomind/triton_backend/llama/LlamaTritonModel.cc
Wait for pinned buffers to be allocated for all ranks, otherwise tuning will hang due to concurrent kernel launch & cudaMallocHost.
> Fix turbomind TP

- lmdeploy/model.py
- lmdeploy/pytorch/engine/logits_process.py
- lmdeploy/serve/async_engine.py
Internlm2_5-2-b-chat model with tool calling.
```python
from openai import OpenAI
tools = [{"type":"function","function":{"name":"search","description":"BING search API","parameters":{"type":"object","properties":{"query":{"type":"string","description":"list of search query strings"}},"required":["location"]}}}]
messages = [{'role': 'user', 'content': '搜索最近的人工智能发展趋势'}]
client = OpenAI(api_key='YOUR_API_KEY', base_url='http://0.0.0.0:23333/v1')
model_name = client.models.list().data[0].id
response = client.chat.completions.create(
model=model_name,
messages=messages,
temperature=0.8,
top_p=0.9,
stream=False,
tool_choice="required",
tools=tools)
print(response)
```
> Add ensure_ascii = False for json.dumps

- lmdeploy/pytorch/kernels/cuda/pagedattention.py
- tests/pytorch/kernel/test_paged_attention.py
Fix decoding kernel for GQA with large `kv_group`.
> fix decoding kernel for deepseekv2

- lmdeploy/version.py
> bump version to 0.6.2.post1

- lmdeploy/pytorch/backends/cuda/moe.py
- lmdeploy/pytorch/backends/dlinfer/moe.py
- lmdeploy/pytorch/backends/moe.py
- lmdeploy/pytorch/kernels/cuda/fused_moe.py
- lmdeploy/pytorch/nn/moe.py
> Support ep, column major moe kernel.

- docs/en/get_started/ascend/get_started.md
- docs/zh_cn/get_started/ascend/get_started.md
update graph-mode in ascend readme …
> Update ascend readme

- docs/en/get_started/ascend/get_started.md
- docs/en/supported_models/supported_models.md
- docs/zh_cn/get_started/ascend/get_started.md
- docs/zh_cn/supported_models/supported_models.md
update ascend supported model list …
> Update supported models & Ascend doc

- autotest/config.yaml
- lmdeploy/lite/apis/calibrate.py
- lmdeploy/lite/quantization/awq.py
- lmdeploy/lite/utils/batch_split.py
- lmdeploy/vl/model/qwen2.py
> Support qwen2-vl AWQ quantization

- lmdeploy/serve/vl_async_engine.py
- lmdeploy/vl/engine.py
- lmdeploy/vl/model/base.py
- lmdeploy/vl/model/cogvlm.py
- lmdeploy/vl/model/deepseek.py
- lmdeploy/vl/model/glm_4v.py
- lmdeploy/vl/model/internvl.py
- lmdeploy/vl/model/internvl_llava.py
- lmdeploy/vl/model/llava.py
- lmdeploy/vl/model/llava_hf.py
- lmdeploy/vl/model/llava_next.py
- lmdeploy/vl/model/mini_gemeni.py
- lmdeploy/vl/model/minicpmv.py
- lmdeploy/vl/model/mllama.py
- lmdeploy/vl/model/molmo.py
- lmdeploy/vl/model/phi3_vision.py
- lmdeploy/vl/model/qwen.py
- lmdeploy/vl/model/qwen2.py
- lmdeploy/vl/model/xcomposer2.py
- lmdeploy/vl/model/yi.py
> Refactor VLM modules v2

- lmdeploy/pytorch/backends/dlinfer/ascend/op_backend.py
> Resolve conflicts

- lmdeploy/api.py
> disable prefix-caching for vl model

- docker/Dockerfile
> add openssh-server installation in dockerfile

- lmdeploy/pytorch/backends/dlinfer/maca/op_backend.py
- lmdeploy/pytorch/kernels/dlinfer/pagedattention.py
change the paged_prefill_attention impl.
1. change dlinfer kv_cache layout and ajust paged_prefill_attention api;
2. opt update_step_ctx on maca.
> [dlinfer] change dlinfer kv_cache layout and ajust paged_prefill_attention api.

- lmdeploy/pytorch/backends/dlinfer/linear.py
add env to support different mm layout on maca.
> [maca] add env to support different mm layout on maca.

- requirements/runtime_ascend.txt
> Update dlinfer-ascend version in runtime_ascend.txt

- lmdeploy/pytorch/models/patch.py
> [Feature] Support for loading lora adapter weights in safetensors format

- lmdeploy/pytorch/engine/cache_engine.py
> fix cpu cache

- lmdeploy/pytorch/engine/engine_checker.py
> [dlinfer] fix engine checker

- docker/Dockerfile
unfeeze torch version in dockerfile
ref run log: https://github.com/RunningLeon/lmdeploy/actions/runs/12370297388/job/34523956129
3. If the modification has a dependency on downstream projects of a newer version, this PR should be …
> unfeeze torch version in dockerfile

- lmdeploy/pytorch/backends/dlinfer/moe.py
- lmdeploy/pytorch/kernels/dlinfer/fused_moe.py
add renormalize para for moe op on dlinfer backend.
> [dlinfer] fix moe op for dlinfer.

- lmdeploy/pytorch/config.py
fix bug when torch_dtype is torch.dtype, not str …
> fix torch_dtype

- lmdeploy/pytorch/models/internvl.py
- lmdeploy/pytorch/nn/linear.py
- lmdeploy/pytorch/nn/utils.py
> support unaligned qkv heads

- .github/workflows/unit-test.yml
- lmdeploy/pytorch/models/mllama.py
fix mllama infer without image https://github.com/InternLM/lmdeploy/issues/2940
fix ut
1. …
> fix mllama inference without image

- lmdeploy/vl/engine.py
This is a temp solution. 
I will update it after #2968
> add a thread pool executor to control the vl engine traffic

- lmdeploy/serve/gradio/vl.py
Fix https://github.com/InternLM/lmdeploy/issues/2974 which is a side effect cause by #2810
> [side-effect] fix gradio demo error

- docs/en/get_started/installation.md
- docs/en/supported_models/supported_models.md
- docs/zh_cn/get_started/installation.md
- docs/zh_cn/supported_models/supported_models.md
- lmdeploy/version.py
> Bump version to v0.6.5

- lmdeploy/pytorch/backends/cuda/lora.py
- lmdeploy/pytorch/kernels/cuda/fused_lora.py
- remove elementwise sum
- compute column with same CTA
> Optimize lora kernel

- docker/Dockerfile_aarch64_ascend
- docs/en/get_started/ascend/get_started.md
- docs/zh_cn/get_started/ascend/get_started.md
> Fix ascend dockerfile

- docs/zh_cn/quantization/w4a16.md
Update model name to internlm2_5-7b-chat
> Fix typo in w4a16 guide

- lmdeploy/pytorch/backends/cuda/moe.py
- lmdeploy/pytorch/kernels/cuda/blocked_fp8_fused_moe.py
add A scale mask.
change B layout.
> fix blocked fp8 moe kernel

- lmdeploy/pytorch/backends/cuda/moe.py
- lmdeploy/pytorch/backends/moe.py
- lmdeploy/pytorch/kernels/cuda/w8a8_fused_moe.py
- lmdeploy/pytorch/nn/moe.py
> support-moe-fp8

- lmdeploy/model.py
- lmdeploy/serve/async_engine.py
- lmdeploy/turbomind/deploy/source_model/llama.py
- lmdeploy/turbomind/supported_models.py
> add internlm3-dense(turbomind) & chat template

- src/turbomind/kernels/gemm/moe_utils_v2.cu
- src/turbomind/kernels/gemm/moe_utils_v2.h
- src/turbomind/kernels/gemm/test/test_moe_utils.cu
- src/turbomind/models/llama/moe_ffn_layer.cc
Softmax must be done before masking the scores.
> Fix MoE gating for DeepSeek V2

- README.md
- README_ja.md
- README_zh-CN.md
- docs/en/supported_models/supported_models.md
- docs/zh_cn/supported_models/supported_models.md
> add internlm3 to supported models

- lmdeploy/pytorch/backends/dlinfer/ascend/graph_runner.py
- lmdeploy/pytorch/backends/dlinfer/rotary_embedding.py
- lmdeploy/pytorch/kernels/dlinfer/flash_attention.py
fix ascend qwen2_vl graph_mode
related PR https://github.com/DeepLink-org/dlinfer/pull/163
> [dlinfer] fix ascend qwen2_vl graph_mode

- lmdeploy/serve/openai/api_client.py
- lmdeploy/serve/openai/api_server.py
> More arguments in api_client, update docstrings

- docs/en/get_started/installation.md
- docs/zh_cn/get_started/installation.md
- lmdeploy/version.py
> bump version to v0.7.0.post2

- lmdeploy/serve/gradio/app.py
#3102 
Change the URL judgment logic from ":" to "://"
> [Fix] fix the URL judgment problem in Windows

- lmdeploy/pytorch/models/cogvlm.py
- lmdeploy/pytorch/models/phi3_v.py
- lmdeploy/vl/model/cogvlm.py
- lmdeploy/vl/model/phi3_vision.py
fix cogvlm and phi3v as in https://github.com/InternLM/lmdeploy/issues/3121
3. If the modification has a dependency on downstream projects of a newer version, this PR should …
> Fix cogvlm and phi3vision

- lmdeploy/pytorch/engine/engine.py
> fix typing

- src/turbomind/models/llama/LlamaBatch.cc
> fix default temperature value

- lmdeploy/pytorch/models/chatglm2.py
- lmdeploy/pytorch/models/cogvlm.py
- lmdeploy/pytorch/models/internvl.py
- lmdeploy/pytorch/models/llava.py
- lmdeploy/pytorch/models/phi3_v.py
- lmdeploy/pytorch/models/qwen2_vl.py
- lmdeploy/vl/model/base.py
- lmdeploy/vl/model/cogvlm.py
- lmdeploy/vl/model/deepseek.py
- lmdeploy/vl/model/glm_4v.py
- lmdeploy/vl/model/internvl.py
- lmdeploy/vl/model/llava.py
- lmdeploy/vl/model/llava_hf.py
- lmdeploy/vl/model/llava_next.py
- lmdeploy/vl/model/minicpmv.py
- lmdeploy/vl/model/phi3_vision.py
- lmdeploy/vl/model/qwen.py
- lmdeploy/vl/model/qwen2.py
- lmdeploy/vl/model/xcomposer2.py
- lmdeploy/vl/model/yi.py
Fix https://github.com/InternLM/lmdeploy/issues/3078 …
> Use pad_token_id as image_token_id for vl models

- lmdeploy/model.py
- tests/test_lmdeploy/test_model.py
https://github.com/InternLM/lmdeploy/issues/3058
> Fix tool call prompt for InternLM and Qwen

- lmdeploy/pytorch/messages.py
set `temperature=1, topk=1` if input temperature is 0.
> fix temperature=0

- lmdeploy/pytorch/models/deepseek_v2.py
[Issue 3187](https://github.com/InternLM/lmdeploy/issues/3187), deepseek-vl2 series has `use_mla` attributes while deepseek-v2 series doesn't, need to change the check condition
> fix deepseekv2 has no attribute use_mla error

- lmdeploy/turbomind/chat.py
> fix unstoppable chat

- lmdeploy/pytorch/engine/engine.py
> remove update badwords

- lmdeploy/cli/cli.py
> Fix missing cli chat option

- lmdeploy/pytorch/engine/executor/__init__.py
> defaullt executor ray

- docs/en/benchmark/benchmark.md
- docs/zh_cn/benchmark/benchmark.md
If using main, api may not compatible with installed version
> Specifiy lmdeploy version in benchmark guide 

- lmdeploy/pytorch/backends/default/op_backend.py
- lmdeploy/pytorch/backends/dlinfer/ascend/op_backend.py
- lmdeploy/pytorch/backends/selector.py
- lmdeploy/pytorch/devices/device_manager.py
- lmdeploy/pytorch/distributed.py
- lmdeploy/pytorch/engine/executor/base_worker.py
- lmdeploy/pytorch/engine/executor/mp_executor.py
> [ascend] fix multi-card distributed inference failures

- lmdeploy/pytorch/engine/engine.py
- lmdeploy/pytorch/kernels/cuda/blocked_fp8_fused_moe.py
> fix for small cache-max-entry-count

- lmdeploy/pytorch/backends/dlinfer/ascend/graph_runner.py
fix glm-4v graph mode on ascend
related PR has already merged(https://github.com/DeepLink-org/dlinfer/pull/184)
2. The modification is covered by complete unit tests. If not, please add more unit …
> [dlinfer] fix glm-4v graph mode on ascend

- docs/en/get_started/ascend/get_started.md
- docs/zh_cn/get_started/ascend/get_started.md
> [ascend] add Ascend docker image

- lmdeploy/utils.py
Avoid users forgetting to set max_batch_size, which may lead to performance degradation.
2. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the …
> change ascend&camb default_batch_size to 256

- lmdeploy/pytorch/engine/executor/dist_utils.py
- lmdeploy/pytorch/engine/executor/ray_executor.py
remove `TORCHELASTIC_USE_AGENT_STORE` on multi-device launch, support torchrun.
> remove torchelastic flag

- docs/en/get_started/ascend/get_started.md
- docs/zh_cn/get_started/ascend/get_started.md
Update ascend docs for docker running.
Ascend get_started.md, both zh-cn and en. …
> docs: update ascend docs for docker running

- lmdeploy/pytorch/configurations/utils.py
do not warning flash-mla on sm<90
> disable flashmla warning on sm<90

- lmdeploy/pytorch/kernels/cuda/activation.py
- lmdeploy/pytorch/kernels/cuda/blocked_gemm_fp8.py
- lmdeploy/pytorch/kernels/cuda/utils.py
- tests/pytorch/kernel/test_activation.py
- tests/pytorch/kernel/test_gemm_fp8.py
> fix activation grid oversize

- benchmark/profile_restful_api.py
> add env var to control timeout

- docs/en/get_started/installation.md
- docs/zh_cn/get_started/installation.md
- lmdeploy/version.py
> bump version to v0.7.2.post1

- lmdeploy/pytorch/paging/block_manager/window_block_manager.py
> fix sliding window multi chat

- lmdeploy/pytorch/backends/cuda/graph_runner.py
- lmdeploy/pytorch/engine/engine.py
- lmdeploy/pytorch/engine/engine_instance.py
- lmdeploy/pytorch/engine/executor/ray_executor.py
- lmdeploy/pytorch/engine/model_agent.py
- lmdeploy/pytorch/engine/request.py
- lmdeploy/pytorch/model_inputs.py
> Verbose log

- lmdeploy/turbomind/deploy/config.py
- lmdeploy/turbomind/deploy/module.py
- lmdeploy/turbomind/deploy/source_model/qwen.py
- lmdeploy/turbomind/supported_models.py
- src/turbomind/kernels/norm/rms_norm.cu
- src/turbomind/kernels/norm/rms_norm.h
- src/turbomind/models/llama/LlamaDecoderLayerWeight.cc
- src/turbomind/models/llama/LlamaDenseWeight.h
- src/turbomind/models/llama/llama_params.h
- src/turbomind/models/llama/unified_attention_layer.cc
- src/turbomind/models/llama/unified_attention_layer.h
- src/turbomind/triton_backend/llama/LlamaTritonModel.cc
ref https://github.com/huggingface/transformers/pull/36878
> Add Qwen3 and Qwen3MoE

- lmdeploy/pytorch/models/module_map.py
- lmdeploy/pytorch/models/qwen3.py
- lmdeploy/pytorch/models/qwen3_moe.py
Qwen3 and Qwen3-MOE as shown in https://github.com/huggingface/transformers/pull/36878
It might require further refinements. Documentations will be added once Qwen3 is officially released.
> [Feature] support qwen3 and qwen3-moe for pytorch engine

- lmdeploy/pytorch/kernels/cuda/flashattention.py
qwen2.5-vl has head_dim=80，v bound check is required.
> add `v` check

- lmdeploy/pytorch/kernels/cuda/fill_kv_cache.py
- lmdeploy/pytorch/kernels/cuda/flashattention.py
- lmdeploy/pytorch/kernels/cuda/flatten_kv_cache.py
load v is not necessary since it is slice of k.
> optimize mla, remove load v

- lmdeploy/serve/openai/api_server.py
- lmdeploy/serve/openai/protocol.py
> Fix finish reasons

- lmdeploy/serve/openai/reasoning_parser/deepseek_r1_reasoning_parser.py
> remove think_end_token_id in streaming content

- lmdeploy/pytorch/kernels/cuda/blocked_gemm_fp8.py
- grid size match sm
- alignment hint
- small cta
- share kernel between normal fp8 and tma fp8
- double performance on (4096, 2560)
> optimize quant-fp8 kernel

- lmdeploy/serve/openai/api_server.py
> Fix the finish_reason

- lmdeploy/pytorch/backends/dlinfer/ascend/graph_runner.py
- lmdeploy/pytorch/kernels/dlinfer/apply_rotary_pos_emb.py
related PR https://github.com/DeepLink-org/dlinfer/pull/199
> refactor dlinfer rope

- lmdeploy/pytorch/backends/dlinfer/ascend/graph_runner.py
enable qwenvl2.5 graph mode on ascend …
> enable qwenvl2.5 graph mode on ascend

- lmdeploy/pytorch/backends/cuda/graph_runner.py
- lmdeploy/pytorch/backends/graph_runner.py
- lmdeploy/pytorch/engine/model_agent.py
- lmdeploy/pytorch/models/utils/cudagraph.py
> fix dp cudagraph

- lmdeploy/pytorch/backends/cuda/op_backend.py
> fix flashmla eagermode

- autotest/interface/pipeline/test_pipeline_func.py
> [ci] add vl models into pipeline interface testcase

- lmdeploy/cli/lite.py
- lmdeploy/lite/apis/auto_awq.py
- lmdeploy/lite/apis/smooth_quant.py
- lmdeploy/pytorch/backends/dlinfer/ascend/graph_runner.py
- lmdeploy/pytorch/check_env/__init__.py
- lmdeploy/pytorch/check_env/deeplink.py
- lmdeploy/pytorch/kernels/cuda/__init__.py
- lmdeploy/pytorch/kernels/cuda/w8a8_triton_kernels.py
- lmdeploy/pytorch/kernels/default/__init__.py
- lmdeploy/pytorch/kernels/default/w8a8_kernels.py
- lmdeploy/pytorch/kernels/dispatcher.py
- lmdeploy/pytorch/kernels/dlinfer/__init__.py
- lmdeploy/pytorch/kernels/dlinfer/apply_rotary_pos_emb.py
- lmdeploy/pytorch/models/q_modules.py
- lmdeploy/serve/openai/api_server.py
- lmdeploy/serve/vl_async_engine.py
- lmdeploy/utils.py
DO ADD A NEW COMMIT WHEN MERGE
> merge dev to main branch

- lmdeploy/pytorch/backends/cuda/graph_runner.py
- lmdeploy/pytorch/engine/model_agent.py
> disable sync batch on dp eager mode

- benchmark/profile_generation.py
- benchmark/profile_throughput.py
- lmdeploy/pytorch/backends/cuda/blockedf8_modules.py
- lmdeploy/pytorch/check_env/transformers.py
- lmdeploy/pytorch/kernels/cuda/blocked_gemm_fp8.py
- input padded A and A_scale
- use default gemm_fp8_fp8_bf16_nt
- add build warning
> fix for deepgemm update

- lmdeploy/pytorch/paging/block_trie.py
> Add string before hash tokens in blocktrie

- lmdeploy/pytorch/backends/cuda/moe.py
- lmdeploy/pytorch/backends/cuda/token_dispatcher.py
- lmdeploy/pytorch/kernels/cuda/ep_moe.py
> optimize ep in decoding stage

- lmdeploy/pytorch/kernels/cuda/flashattention.py
- lmdeploy/pytorch/kernels/cuda/fused_moe.py
- tests/pytorch/kernel/test_fused_moe.py
> optimize moe get sorted idx

- lmdeploy/pytorch/engine/engine.py
- lmdeploy/pytorch/engine/model_agent.py
> fix stopping criteria

- .github/workflows/unit-test.yml
- generate.sh
- lmdeploy/model.py
- lmdeploy/serve/async_engine.py
- lmdeploy/serve/vl_async_engine.py
> support List[dict] prompt input without do_preprocess

- README.md
- README_ja.md
- README_zh-CN.md
- docs/en/supported_models/supported_models.md
- docs/zh_cn/supported_models/supported_models.md
- lmdeploy/archs.py
- lmdeploy/model.py
- lmdeploy/pytorch/configurations/llama4.py
- lmdeploy/pytorch/models/llama4.py
- lmdeploy/pytorch/models/module_map.py
- lmdeploy/pytorch/nn/moe.py
- lmdeploy/pytorch/supported_models.py
- lmdeploy/vl/model/builder.py
- lmdeploy/vl/model/llama4.py
- both bf16 and int8
- both Scout and Maverick
> support Llama4

- lmdeploy/pytorch/engine/engine.py
- lmdeploy/pytorch/model_inputs.py
In ascend dev, dynamo will catch multi graph, not the two expected graph(prefill, decode). With `export TORCH_LOGS="dynamo,guards,bytecode"`, I can get multi guards. The diff in two guards is shown in the following figure:
By debugging, I find there are two places where there is no context `"@torch.inference_mode()"` when creating tensors.
Here is the minimal reproduction code:
```python
import torch
import torch_npu
import numpy as np
@torch.inference_mode()
def test_dispatchkey1():
print(f"----- infermode tensor …
```
> fix tensor dispatch in dynamo

- .github/workflows/lint.yml
> fix linting error by upgrade to ubuntu-latest

- lmdeploy/pytorch/backends/cuda/graph_runner.py
- lmdeploy/pytorch/models/internvl.py
- lmdeploy/pytorch/models/utils/micro_batch.py
- requirements/runtime_cuda.txt
Optimize internvit.
Benchmark serving result on **A100 using 4 gpus** with `python benchmark/profile_restful_api.py --backend lmdeploy --base-url http://0.0.0.0:23333 --dataset-name sharegpt --dataset-path /workspace/caikun/benchmark/ShareGPT_V3_unfiltered_cleaned_split.json  --sharegpt-output-len 4 --num-prompts 500 --model OpenGVLab/InternVL2_5-78B`
Benchmark input image use https://raw.githubusercontent.com/open-mmlab/mmdeploy/main/tests/data/tiger.jpeg.
**About 11.5%+ improvement of the prefill phase.**
1. Using torch.compile which will fuse small kernels and use triton to generate efficient mm and conv operators (+save runtime memory).
2. Split batch to overlap communicate and compute.
```
============ Serving Benchmark Result ============
Backend: …
```
> optimize internvit

- lmdeploy/pytorch/nn/linear.py
Fix tp>1 for awq models in pt engine
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions …
> fix awq tp for pytorch engine

- docs/en/multi_modal/qwen2_5_vl.md
- docs/zh_cn/multi_modal/qwen2_5_vl.md
https://github.com/InternLM/lmdeploy/issues/3441
> update qwen2.5-vl-32b docs

- lmdeploy/pytorch/distributed.py
- lmdeploy/pytorch/engine/executor/base.py
- lmdeploy/pytorch/engine/executor/ray_executor.py
> ray async forward execute

- lmdeploy/model.py
- tests/test_lmdeploy/test_model.py
> map internvl3 chat template to builtin chat template internvl2_5

- lmdeploy/pytorch/kernels/cuda/pagedattention.py
> remove paged attention autotune

- README.md
- README_ja.md
- README_zh-CN.md
- docs/en/supported_models/supported_models.md
- docs/zh_cn/supported_models/supported_models.md
- lmdeploy/model.py
- lmdeploy/pytorch/kernels/cuda/apply_rotary_pos_emb.py
- lmdeploy/pytorch/models/phi3.py
- lmdeploy/pytorch/nn/rotary_embedding.py
support [microsoft/Phi-4-mini-instruct](https://huggingface.co/microsoft/Phi-4-mini-instruct) requested by https://github.com/InternLM/lmdeploy/issues/3447
3. If the …
> Support phi4 mini

- lmdeploy/pytorch/backends/cuda/blockedf8_modules.py
> Align forward arguments of deepgemm blockedf8

- builder/manywheel/entrypoint_build.sh
> fix turbomind lib missing to link nccl by exporting nccl path

- lmdeploy/pytorch/engine/executor/ray_executor.py
> Fix disorder of ray execution

- src/turbomind/layers/sampling_layers/LogitsProcessorLayer.cc
- src/turbomind/layers/sampling_layers/StopCriteriaLayer.cc
> fix stop/bad words

- lmdeploy/pytorch/models/qwen3_moe.py
> fix replicate kv for qwen3-moe

- lmdeploy/lite/apis/calibrate.py
- lmdeploy/lite/quantization/awq.py
> support qwen3-dense models awq quantization

- lmdeploy/pytorch/models/qwen3.py
- lmdeploy/pytorch/models/qwen3_moe.py
- lmdeploy/pytorch/nn/linear.py
`nn/linear.py` modifications credit to @RunningLeon 
- qwen3-dense-fp8 tested
- qwen3-moe-fp8 tested
> support qwen3 fp8

- lmdeploy/pytorch/kernels/cuda/pagedattention.py
adjust split_k according to batch size and num sm.
> optimize longcontext decoding

- src/turbomind/engine/model_request.cc
- src/turbomind/kernels/ban_bad_words.cu
- src/turbomind/kernels/reduce_kernel_utils.cuh
- src/turbomind/kernels/sampling_kernels.cu
- src/turbomind/kernels/sampling_penalty_kernels.cu
- src/turbomind/kernels/sampling_topk_kernels.cu
- src/turbomind/kernels/sampling_topp_kernels.cu
- src/turbomind/layers/DynamicDecodeLayer.cc
- src/turbomind/layers/sampling_layers/LogitsProcessorLayer.cc
- src/turbomind/layers/sampling_layers/SamplingLayer.cc
- src/turbomind/layers/sampling_layers/StopCriteriaLayer.cc
- src/turbomind/models/llama/LlamaBatch.cc
- src/turbomind/models/llama/LlamaBatch.h
- src/turbomind/models/llama/LlamaV2.cc
- src/turbomind/models/llama/llama_kernels.cu
- src/turbomind/models/llama/llama_kernels.h
> fix sampling if data overflow after temperature penalty

- lmdeploy/pytorch/engine/executor/ray_executor.py
> reduce ray memory usage

- docker/Dockerfile
- docker/Dockerfile_Hopper
- lmdeploy/pytorch/backends/cuda/moe.py
- lmdeploy/pytorch/backends/cuda/token_dispatcher.py
- lmdeploy/pytorch/models/deepseek_v2.py
> use dlblas

- lmdeploy/pytorch/kernels/cuda/flashattention.py
> fix attention sm86

- docs/en/get_started/ascend/get_started.md
- docs/en/supported_models/supported_models.md
- docs/zh_cn/get_started/ascend/get_started.md
- docs/zh_cn/supported_models/supported_models.md
update doc for  ascend 300I Duo docker image
> update doc for  ascend 300I Duo docker image

- lmdeploy/pytorch/models/deepseek_v2.py
- lmdeploy/pytorch/nn/moe.py
notify-dispatch overlap in prefill
support fp8 in dispatch normal
1. Pre-commit or other linting …
> update two microbatch

- lmdeploy/messages.py
- lmdeploy/pytorch/config.py
- lmdeploy/pytorch/engine/engine.py
- lmdeploy/pytorch/engine/executor/__init__.py
- lmdeploy/pytorch/engine/executor/base.py
- lmdeploy/pytorch/engine/executor/base_worker.py
- lmdeploy/pytorch/engine/executor/mp_executor.py
- lmdeploy/pytorch/engine/executor/ray_executor.py
- lmdeploy/pytorch/engine/executor/uni_executor.py
- lmdeploy/pytorch/engine/model_agent.py
- lmdeploy/pytorch/nn/linear.py
- lmdeploy/serve/openai/api_server.py
- lmdeploy/serve/openai/protocol.py
- lmdeploy/serve/proxy/proxy.py
- lmdeploy/utils.py
https://aicarrier.feishu.cn/wiki/KnZswNvWNiHbjHk6qIYcm6ujnIh
> support update params for pytorch backend from api server

- lmdeploy/pytorch/backends/dlinfer/ascend/op_backend.py
This PR set transdata dynamic shape true, to reduce recompile
> [ascend]set transdata dynamic shape true

- lmdeploy/pytorch/engine/executor/ray_executor.py
- kill workers if release timeout.
- add ray.shutdown
> ray safe exit

- lmdeploy/serve/proxy/proxy.py
> fix proxy server heart beat

- lmdeploy/pytorch/engine/engine.py
> fix dp>1 tp=1 ep=1

- lmdeploy/pytorch/backends/cuda/token_dispatcher.py
- lmdeploy/pytorch/distributed.py
- lmdeploy/pytorch/engine/engine.py
- lmdeploy/pytorch/engine/model_agent.py
- If the inputs in all the DP ranks are dummy inputs, model forward would be skipped.
- refactor forward step pipeline in model agent.
- If tp and ep are not required, dp would be 1.
> Skip dp dummy input forward

- lmdeploy/turbomind/deploy/source_model/llama.py
Solve the problem that the first GPU takes up more memory after startup
If this PR introduces a new feature, it is …
> perform torch.cuda.empty_cache() after conversion

- lmdeploy/serve/async_engine.py
- lmdeploy/serve/openai/api_server.py
> pipeline warmup

- lmdeploy/lite/apis/auto_awq.py
- lmdeploy/lite/apis/calibrate.py
- lmdeploy/lite/apis/smooth_quant.py
- lmdeploy/lite/quantization/awq.py
- lmdeploy/vl/model/qwen2.py
https://github.com/InternLM/lmdeploy/issues/3501 …
> support awq for Qwen2.5-VL 

- lmdeploy/pytorch/configurations/default.py
> fix mixtral on new transformers

- .github/workflows/lint.yml
- lmdeploy/pytorch/paging/eviction_helper/recompute_eviction_helper.py
> [Fix]: reset step after eviction

- .github/workflows/pr_ete_test.yml
- lmdeploy/vl/model/gemma3_vl.py
> Fix batch infer for gemma3vl

- lmdeploy/pytorch/engine/logits_process.py
- lmdeploy/pytorch/engine/model_agent.py
> sampling on the tokenizer's vocab

- lmdeploy/pytorch/models/deepseek_v2.py
- lmdeploy/serve/async_engine.py
- lmdeploy/turbomind/deploy/loader.py
> fix side-effect caused by PR 3590

- lmdeploy/pytorch/engine/engine.py
- lmdeploy/serve/proxy/proxy.py
> update some logs of proxy_server and pt engine

- lmdeploy/pytorch/kernels/cuda/awq_kernels.py
> fix awq kernel

- lmdeploy/pytorch/backends/cuda/op_backend.py
- lmdeploy/pytorch/configurations/utils.py
- lmdeploy/pytorch/kernels/cuda/flash_mla.py
- lmdeploy/pytorch/models/utils/cudagraph.py
> fix flash mla interface

- lmdeploy/pytorch/nn/moe.py
> fix for default quant

- lmdeploy/pytorch/kernels/cuda/blocked_fp8_fused_moe.py
- lmdeploy/pytorch/kernels/cuda/blocked_gemm_fp8.py
> fix blocked fp8 overflow

- lmdeploy/serve/openai/api_server.py
- lmdeploy/serve/openai/protocol.py
> support do_preprocess=False for chat.completions

- lmdeploy/pytorch/engine/executor/base.py
- lmdeploy/pytorch/engine/model_agent.py
> defer building cache engine until weight migration is done

- .github/workflows/pr_ete_test.yml
> [ci] change flash atten installation in pr test

- benchmark/profile_throughput.py
In the PyTorch backend, the `inst.async_end(session_id)` operation does not block the coroutine. Using the same session_id may cause conflicts.
> fix profile_throughput.py

- benchmark/profile_generation.py
> fix profile_generation.py

- docs/en/get_started/installation.md
- docs/zh_cn/get_started/installation.md
- lmdeploy/version.py
> bump version to v0.9.1

- .github/workflows/unit-test.yml
> [CI]: Upgrade to py310 for ut

- lmdeploy/serve/async_engine.py
- lmdeploy/turbomind/turbomind.py
> Fix the logic of calculating max_new_tokens and determining finish_reason

- benchmark/benchmark_serving.py
- benchmark/lmdeploy.yml
- benchmark/profile_restful_api.py
> Generate the benchmark output filename with given arguments

- lmdeploy/pytorch/models/internvl.py
- lmdeploy/pytorch/models/internvl3_hf.py
> fix internvl norm

- lmdeploy/pytorch/config.py
- lmdeploy/pytorch/models/qwen3_moe.py
- tests/pytorch/config/test_hf_overrides.py
- hf_overrides would override keys recursively.
- Add qwen3 yarn support.
> support qwen3 moe yarn and vlm hf_overrides

- lmdeploy/serve/proxy/proxy.py
fix double unshelf when streamming = False
> [PD Disaggregation] fix double unshelf

- lmdeploy/archs.py
- lmdeploy/model.py
- lmdeploy/pytorch/check_env/model.py
- lmdeploy/pytorch/configurations/internvl3_hf.py
- lmdeploy/pytorch/models/internvl3_hf.py
- lmdeploy/pytorch/models/module_map.py
- lmdeploy/pytorch/supported_models.py
- lmdeploy/serve/openai/api_server.py
- lmdeploy/serve/openai/reasoning_parser/qwen_qwq_reasoning_parser.py
- lmdeploy/serve/openai/tool_parser/internlm2_parser.py
- lmdeploy/vl/model/internvl3_hf.py
- tests/test_lmdeploy/test_model.py
> Internvl pt

- lmdeploy/model.py
- tests/test_lmdeploy/test_model.py
> fix chat template with tool call

- lmdeploy/serve/vl_async_engine.py
- lmdeploy/vl/engine.py
- lmdeploy/vl/model/base.py
- lmdeploy/vl/model/cogvlm.py
- lmdeploy/vl/model/deepseek.py
- lmdeploy/vl/model/deepseek_vl2.py
- lmdeploy/vl/model/gemma3_vl.py
- lmdeploy/vl/model/glm_4v.py
- lmdeploy/vl/model/internvl.py
- lmdeploy/vl/model/internvl3_hf.py
- lmdeploy/vl/model/llama4.py
- lmdeploy/vl/model/llava_hf.py
- lmdeploy/vl/model/minicpmv.py
- lmdeploy/vl/model/mllama.py
- lmdeploy/vl/model/molmo.py
- lmdeploy/vl/model/qwen.py
- lmdeploy/vl/model/qwen2.py
- lmdeploy/vl/model/xcomposer2.py
> fix vl nothink mode

- .github/workflows/cuda11.8-whl-release.yml
- .github/workflows/pypi.yml
- setup.py
Make RelWithDebInfo default cmake build type
> fix: make RelWithDebInfo default cmake build type

- docs/en/get_started/installation.md
- docs/zh_cn/get_started/installation.md
- lmdeploy/version.py
> bump version to v0.9.2

- docs/en/llm/proxy_server.md
- docs/zh_cn/llm/proxy_server.md
- https://github.com/InternLM/lmdeploy/issues/3788
> update proxy docs

- lmdeploy/pytorch/configurations/default.py
- lmdeploy/turbomind/deploy/source_model/llama.py
> fix head_dim=None

- lmdeploy/pytorch/kernels/cuda/rms_norm.py
- lmdeploy/pytorch/kernels/cuda/utils.py
optimize rms norm in attention layer (after qkv_proj)
before
after
> Optimize rmsnorm with head_dim=128

- lmdeploy/pytorch/models/internvl3_hf.py
- lmdeploy/pytorch/models/utils/model.py
- lmdeploy/pytorch/weight_loader/model_weight_loader.py
> fix internvl disable_vision_encoder

- lmdeploy/vl/model/qwen2.py
Fix the bug described in issue #3819 
Add `config.text_config.tie_word_embeddings = False`
1. Pre-commit or other linting tools are used to fix the potential …
> fix: set text_config.tie_word_embedding = False in qwen2vl

- lmdeploy/serve/openai/api_server.py
> Fix v1 comp protocol

- docs/en/supported_models/supported_models.md
- docs/zh_cn/supported_models/supported_models.md
- lmdeploy/model.py
- lmdeploy/pytorch/backends/attention.py
- lmdeploy/pytorch/backends/cuda/attention.py
- lmdeploy/pytorch/backends/cuda/moe.py
- lmdeploy/pytorch/backends/dlinfer/attention.py
- lmdeploy/pytorch/backends/dlinfer/moe.py
- lmdeploy/pytorch/backends/moe.py
- lmdeploy/pytorch/configurations/gpt_oss.py
- lmdeploy/pytorch/kernels/cuda/blocked_fp8_fused_moe.py
- lmdeploy/pytorch/kernels/cuda/flashattention.py
- lmdeploy/pytorch/kernels/cuda/fused_moe.py
- lmdeploy/pytorch/kernels/cuda/pagedattention.py
- lmdeploy/pytorch/models/gpt_oss.py
- lmdeploy/pytorch/models/module_map.py
- lmdeploy/pytorch/nn/attention.py
- lmdeploy/pytorch/nn/moe.py
- tests/pytorch/kernel/test_flash_attention.py
- tests/pytorch/kernel/test_fuse_moe_blocked_fp8.py
- tests/pytorch/kernel/test_fused_moe.py
- tests/pytorch/kernel/test_paged_attention.py
> PytorchEngine support gpt-oss bf16

- lmdeploy/pytorch/backends/dlinfer/__init__.py
- lmdeploy/pytorch/backends/selector.py
fix get_backend err for dlinfer backend when device is not ascend
> [dlinfer] fix get_backend err

- docs/en/get_started/installation.md
- docs/zh_cn/get_started/installation.md
- lmdeploy/version.py
> bump version to v0.9.2.post1

- src/turbomind/engine/request_queue.h
address https://github.com/InternLM/lmdeploy/issues/3825
> fix inference on windows platform

- builder/manywheel/Dockerfile_2014
- builder/manywheel/build_all_lmdeploy_builders.sh
- builder/manywheel/build_all_wheel.sh
- src/turbomind/kernels/gemm/tma.cu
> fix prebuild on cuda12.8

- lmdeploy/pytorch/backends/cuda/attention.py
- lmdeploy/pytorch/third_party/flash_attn_interface.py
> fix flash-attn bc

- lmdeploy/pytorch/engine/executor/ray_executor.py
- lmdeploy/pytorch/engine/mp_engine/ray_engine.py
- lmdeploy/pytorch/ray.py
Fix usage when mp_engine_backend = 'ray' and device_type = 'ascend'
1. use get_device_str in lmdeploy.pytorch.ray if necessary
2. add get_resource_kwargs for general ray resources related kwargs
If this PR introduces a new feature, it is better to list some use cases …
> [Fix] ray mp engine on ascend platform

- lmdeploy/pytorch/engine/cache_engine.py
- lmdeploy/pytorch/engine/model_agent.py
> Fix stream assert error when wakeup 30+ times

- README.md
- README_ja.md
- README_zh-CN.md
- docs/en/supported_models/supported_models.md
- docs/zh_cn/supported_models/supported_models.md
- lmdeploy/turbomind/deploy/source_model/internvl.py
- lmdeploy/turbomind/supported_models.py
> support internvl3.5

- lmdeploy/pytorch/engine/engine_checker.py
- lmdeploy/pytorch/engine/mp_engine/zmq_engine.py
- lmdeploy/pytorch/envs.py
Check env requires gpu memory which can not be released.
> check_env in multiprocess

- lmdeploy/pytorch/backends/dlinfer/ascend/graph_runner.py
- lmdeploy/pytorch/backends/dlinfer/ascend/op_backend.py
- lmdeploy/pytorch/engine/executor/ray_executor.py
- lmdeploy/pytorch/envs.py
> [ascend] add env to set rt visable by ray and disable warmup

- lmdeploy/pytorch/engine/engine_checker.py
> disable check_env in multiprocess on dlinfer devices

- lmdeploy/pytorch/backends/dlinfer/qmodules.py
1. DLINER_LINEAR_USE_NN_LAYOUT env var typo
2. weight scale also need transpose
> [dlinfer] fix nn layout typo and scale t

- src/turbomind/kernels/attention/mainloop_sm70.h
- src/turbomind/kernels/core/array_ops.h
- src/turbomind/kernels/gemm/CMakeLists.txt
- src/turbomind/kernels/gemm/convert_v2.cu
- src/turbomind/kernels/gemm/kernel/sm70_s884_dynamic.cu
- src/turbomind/kernels/gemm/registry.cu
- src/turbomind/kernels/gemm/test/reference.cu
- src/turbomind/kernels/gemm/test/test_gemm_v2.cc
- src/turbomind/models/llama/LlamaDenseWeight.cc
> Dispatch MXFP4 weight conversion for sm70 & sm75

- lmdeploy/model.py
The stop_word of "openbmb/MiniCPM-Llama3-V-2_5" is tokenizer.eot_token
> put eot_token to stop_words

- lmdeploy/pytorch/backends/dlinfer/maca/op_backend.py
> [maca] change kv layout from pagedattn to flashattn

- requirements/runtime_cuda.txt
- requirements/serve.txt
> update serve requirement

- docker/Dockerfile
- docker/prepare_wheel.sh
- k8s/deployment.yaml
> remove NCCL_LAUNCH_MODE
